/**
 * Seed plan rows — A.I.M.S. 3-6-9 Tesla Vortex frequencies.
 *
 * NOTE: dollar amounts are NOT set here. The pricing page numbers
 * (e.g. $19.99 / $17.99 / $14.99) are being reassessed and not yet
 * canonical. Plan rows carry the SHAPE (frequency, token allocation,
 * agent limits, taglines) but leave price fields undefined until
 * the pricing committee finalizes.
 *
 * Per memory feedback_billing_correction.md: 3=entry, 6=axis of
 * balance, 9=completion (pay 9, get 12 delivered).
 */

import type { PlanRow } from './types.js';

const NOW = new Date('2026-04-08T00:00:00Z').toISOString();

export const SEED_PLANS: PlanRow[] = [
  // ── 3-month frequency ───────────────────────────────────────────────
  {
    id: 'plan-3mo-individual',
    rowType: 'plan',
    sector: 'plan',
    topic: '3-Month — Individual',
    description: 'Entry point. V.I.B.E. Individual seat.',
    capabilities: ['agentic'],
    tier: 'standard',
    unlockedAt: ['3-month'],
    vibeGroups: ['individual'],
    frequency: '3-month',
    tokenAllocation: 100_000,
    agentLimit: 5,
    concurrentLimit: 2,
    tagline: 'Entry point',
    ppuMultiplier: 1.4,
    lastVerified: NOW,
    active: true,
  },
  {
    id: 'plan-3mo-family',
    rowType: 'plan',
    sector: 'plan',
    topic: '3-Month — Family',
    description: 'Up to 4 seats. 1.5× base.',
    capabilities: ['agentic'],
    tier: 'standard',
    unlockedAt: ['3-month'],
    vibeGroups: ['family'],
    frequency: '3-month',
    tokenAllocation: 100_000,
    agentLimit: 5,
    concurrentLimit: 2,
    tagline: 'Entry point',
    ppuMultiplier: 1.4,
    lastVerified: NOW,
    active: true,
  },
  {
    id: 'plan-3mo-team',
    rowType: 'plan',
    sector: 'plan',
    topic: '3-Month — Team',
    description: '5–20 seats. 2.5× base + per-seat add-on.',
    capabilities: ['agentic'],
    tier: 'standard',
    unlockedAt: ['3-month'],
    vibeGroups: ['team'],
    frequency: '3-month',
    tokenAllocation: 100_000,
    agentLimit: 5,
    concurrentLimit: 2,
    tagline: 'Entry point',
    ppuMultiplier: 1.4,
    lastVerified: NOW,
    active: true,
  },

  // ── 6-month frequency ───────────────────────────────────────────────
  {
    id: 'plan-6mo-individual',
    rowType: 'plan',
    sector: 'plan',
    topic: '6-Month — Individual',
    description: 'Axis of balance. V.I.B.E. Individual seat.',
    capabilities: ['agentic'],
    tier: 'standard',
    unlockedAt: ['6-month'],
    vibeGroups: ['individual'],
    frequency: '6-month',
    tokenAllocation: 250_000,
    agentLimit: 15,
    concurrentLimit: 5,
    tagline: 'Axis of balance',
    ppuMultiplier: 1.4,
    lastVerified: NOW,
    active: true,
  },
  {
    id: 'plan-6mo-family',
    rowType: 'plan',
    sector: 'plan',
    topic: '6-Month — Family',
    capabilities: ['agentic'],
    tier: 'standard',
    unlockedAt: ['6-month'],
    vibeGroups: ['family'],
    frequency: '6-month',
    tokenAllocation: 250_000,
    agentLimit: 15,
    concurrentLimit: 5,
    tagline: 'Axis of balance',
    ppuMultiplier: 1.4,
    lastVerified: NOW,
    active: true,
  },
  {
    id: 'plan-6mo-team',
    rowType: 'plan',
    sector: 'plan',
    topic: '6-Month — Team',
    capabilities: ['agentic'],
    tier: 'standard',
    unlockedAt: ['6-month'],
    vibeGroups: ['team'],
    frequency: '6-month',
    tokenAllocation: 250_000,
    agentLimit: 15,
    concurrentLimit: 5,
    tagline: 'Axis of balance',
    ppuMultiplier: 1.4,
    lastVerified: NOW,
    active: true,
  },

  // ── 9-month frequency (pay 9, get 12) ───────────────────────────────
  {
    id: 'plan-9mo-individual',
    rowType: 'plan',
    sector: 'plan',
    topic: '9-Month — Individual',
    description: 'Completion. Pay 9, get 12 delivered. V.I.B.E. Individual seat.',
    capabilities: ['agentic'],
    tier: 'premium',
    unlockedAt: ['9-month'],
    vibeGroups: ['individual'],
    frequency: '9-month',
    tokenAllocation: 500_000,
    agentLimit: 50,
    concurrentLimit: 25,
    tagline: 'Completion — best rate',
    ppuMultiplier: 1.4,
    lastVerified: NOW,
    active: true,
  },
  {
    id: 'plan-9mo-family',
    rowType: 'plan',
    sector: 'plan',
    topic: '9-Month — Family',
    capabilities: ['agentic'],
    tier: 'premium',
    unlockedAt: ['9-month'],
    vibeGroups: ['family'],
    frequency: '9-month',
    tokenAllocation: 500_000,
    agentLimit: 50,
    concurrentLimit: 25,
    tagline: 'Completion — best rate',
    ppuMultiplier: 1.4,
    lastVerified: NOW,
    active: true,
  },
  {
    id: 'plan-9mo-team',
    rowType: 'plan',
    sector: 'plan',
    topic: '9-Month — Team',
    capabilities: ['agentic'],
    tier: 'premium',
    unlockedAt: ['9-month'],
    vibeGroups: ['team'],
    frequency: '9-month',
    tokenAllocation: 500_000,
    agentLimit: 50,
    concurrentLimit: 25,
    tagline: 'Completion — best rate',
    ppuMultiplier: 1.4,
    lastVerified: NOW,
    active: true,
  },

  // ── Pay-Per-Use ─────────────────────────────────────────────────────
  {
    id: 'plan-ppu',
    rowType: 'plan',
    sector: 'plan',
    topic: 'Pay-Per-Use',
    description: 'Full ecosystem access at higher upcharge vs subscribers. 100 tokens / $1. 1 concurrent. No commitment.',
    capabilities: ['agentic'],
    tier: 'standard',
    unlockedAt: ['ppu'],
    vibeGroups: ['individual', 'family', 'team', 'enterprise'],
    frequency: 'ppu',
    tokenAllocation: 0,         // metered, no included basket
    agentLimit: -1,             // unlimited
    concurrentLimit: 1,
    tagline: 'No commitment · Pay as you go',
    ppuMultiplier: 1.0,         // PPU IS the baseline; subscribers get a discount FROM this
    lastVerified: NOW,
    active: true,
  },

  // ── Enterprise (custom quote) ───────────────────────────────────────
  {
    id: 'plan-enterprise',
    rowType: 'plan',
    sector: 'plan',
    topic: 'Enterprise',
    description: '21+ seats. Custom quote. Includes whitelabel + SOC 2 readiness package + dedicated infra.',
    capabilities: ['agentic'],
    tier: 'flagship',
    unlockedAt: ['9-month', 'ppu'],
    vibeGroups: ['enterprise'],
    frequency: '9-month',
    tokenAllocation: -1,
    agentLimit: -1,
    concurrentLimit: -1,
    tagline: 'Custom — Talk to Sales',
    ppuMultiplier: 1.0,
    lastVerified: NOW,
    active: true,
  },
];
