/**
 * A.I.M.S. Plug Engine
 * Manages dynamic port allocation and URL lifecycle for sandbox container instances.
 * Receives requests from VPS1 (10.0.0.1:3001), provisions ports, and writes
 * nginx upstream configs so each plug gets a routable URL.
 */
'use strict';

const express = require('express');
const Docker  = require('dockerode');
const pino    = require('pino');
const pinoHttp = require('pino-http');
const fs       = require('fs');
const path     = require('path');

const log    = pino({ level: process.env.LOG_LEVEL || 'info' });
const docker = new Docker({ socketPath: process.env.DOCKER_SOCKET || '/var/run/docker.sock' });
const app    = express();

// ─── Config ────────────────────────────────────────────────────────────────
const PORT_START   = parseInt(process.env.PLUG_PORT_START || '51000', 10);
const PORT_END     = parseInt(process.env.PLUG_PORT_END   || '51999', 10);
const NGINX_DIR    = process.env.NGINX_DIR || '/etc/nginx/plugs';
const DATA_DIR     = process.env.DATA_DIR  || '/data';
const DATA_FILE    = path.join(DATA_DIR, 'plugs.json');
const VPS1_URL     = process.env.VPS1_URL  || 'http://10.0.0.1:3001';

// ─── State ─────────────────────────────────────────────────────────────────
let plugs = {};            // { plugId: { port, containerId, createdAt, status } }

function load() {
  try {
    if (fs.existsSync(DATA_FILE)) plugs = JSON.parse(fs.readFileSync(DATA_FILE, 'utf8'));
    log.info({ count: Object.keys(plugs).length }, 'Loaded plug state');
  } catch (e) {
    log.warn({ err: e.message }, 'Could not load plug state, starting fresh');
    plugs = {};
  }
}

function save() {
  fs.mkdirSync(DATA_DIR, { recursive: true });
  fs.writeFileSync(DATA_FILE, JSON.stringify(plugs, null, 2));
}

function nextPort() {
  const used = new Set(Object.values(plugs).map(p => p.port));
  for (let p = PORT_START; p <= PORT_END; p++) {
    if (!used.has(p)) return p;
  }
  throw new Error(`Port pool exhausted (${PORT_START}-${PORT_END})`);
}

function writeNginxUpstream(plugId, port) {
  fs.mkdirSync(NGINX_DIR, { recursive: true });
  const conf = `# auto-generated by plug-engine\nupstream plug_${plugId} { server 127.0.0.1:${port}; }\n`;
  fs.writeFileSync(path.join(NGINX_DIR, `${plugId}.conf`), conf);
}

function removeNginxUpstream(plugId) {
  const f = path.join(NGINX_DIR, `${plugId}.conf`);
  if (fs.existsSync(f)) fs.rmSync(f);
}

// ─── Middleware ─────────────────────────────────────────────────────────────
app.use(pinoHttp({ logger: log }));
app.use(express.json());

// ─── Routes ─────────────────────────────────────────────────────────────────

/** GET /health — liveness probe */
app.get('/health', (_req, res) => res.json({ status: 'ok', plugs: Object.keys(plugs).length }));

/** GET /plugs — list all active plugs */
app.get('/plugs', (_req, res) => res.json(plugs));

/** POST /plugs — allocate a new plug (port + optional container) */
app.post('/plugs', async (req, res) => {
  try {
    const { image, cmd, env = [], plugId: requestedId } = req.body;
    const plugId = requestedId || `plug-${Date.now()}`;
    const port   = nextPort();

    let containerId = null;
    if (image) {
      const container = await docker.createContainer({
        Image: image,
        Cmd: cmd,
        Env: env,
        HostConfig: {
          PortBindings: { '8080/tcp': [{ HostIp: '127.0.0.1', HostPort: String(port) }] },
          AutoRemove: false,
          NetworkMode: 'host',
        },
        Labels: { 'aims.plug': plugId },
      });
      await container.start();
      containerId = container.id;
    }

    plugs[plugId] = { port, containerId, createdAt: new Date().toISOString(), status: 'running' };
    writeNginxUpstream(plugId, port);
    save();

    log.info({ plugId, port, containerId }, 'Plug created');
    res.status(201).json({ plugId, port, url: `http://10.0.0.2:${port}` });
  } catch (err) {
    log.error({ err: err.message }, 'Failed to create plug');
    res.status(500).json({ error: err.message });
  }
});

/** DELETE /plugs/:id — destroy a plug */
app.delete('/plugs/:id', async (req, res) => {
  const { id } = req.params;
  const plug = plugs[id];
  if (!plug) return res.status(404).json({ error: 'Plug not found' });

  try {
    if (plug.containerId) {
      try {
        const c = docker.getContainer(plug.containerId);
        await c.stop({ t: 5 }).catch(() => {});
        await c.remove({ force: true }).catch(() => {});
      } catch (e) {
        log.warn({ err: e.message }, 'Container cleanup failed (may already be gone)');
      }
    }
    removeNginxUpstream(id);
    delete plugs[id];
    save();

    log.info({ plugId: id }, 'Plug removed');
    res.json({ removed: id });
  } catch (err) {
    log.error({ err: err.message }, 'Failed to remove plug');
    res.status(500).json({ error: err.message });
  }
});

/** GET /plugs/:id/status — inspect plug + container health */
app.get('/plugs/:id/status', async (req, res) => {
  const plug = plugs[req.params.id];
  if (!plug) return res.status(404).json({ error: 'Plug not found' });

  let containerStatus = null;
  if (plug.containerId) {
    try {
      const info = await docker.getContainer(plug.containerId).inspect();
      containerStatus = info.State;
    } catch (_e) {
      containerStatus = { Status: 'gone' };
    }
  }

  res.json({ ...plug, containerStatus });
});

// ─── Boot ───────────────────────────────────────────────────────────────────
load();

const port = parseInt(process.env.PORT || '4200', 10);
app.listen(port, '0.0.0.0', () => {
  log.info({ port, portPool: `${PORT_START}-${PORT_END}` }, 'Plug Engine started');
});
