-- ═══════════════════════════════════════════════════════════
-- THE DEPLOY PLATFORM: Memory Layer
-- Conversations, messages, semantic memory, data sources
-- Neon Postgres. No RLS. Enforcement at app level.
-- ═══════════════════════════════════════════════════════════

-- Conversations: persistent threads per user
CREATE TABLE IF NOT EXISTS public.conversations (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id TEXT NOT NULL,
  title TEXT NOT NULL DEFAULT 'New Conversation',
  status TEXT NOT NULL DEFAULT 'active',  -- active, archived
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Messages: every message in every conversation
CREATE TABLE IF NOT EXISTS public.messages (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  conversation_id UUID NOT NULL REFERENCES conversations(id) ON DELETE CASCADE,
  user_id TEXT NOT NULL,
  role TEXT NOT NULL,           -- user, acheevy, system, agent
  agent_name TEXT,              -- which agent responded (null for user messages)
  content TEXT NOT NULL,
  metadata JSONB DEFAULT '{}', -- tokens, cost, model, attachments, etc.
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Memory: semantic long-term memory per user
-- Embeddings generated by Gemini, searchable by similarity
CREATE TABLE IF NOT EXISTS public.memory (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id TEXT NOT NULL,
  content TEXT NOT NULL,
  summary TEXT,                -- short summary for display
  embedding VECTOR(768),       -- Gemini text-embedding-004 dimension
  source_type TEXT DEFAULT 'conversation',  -- conversation, upload, manual
  source_id UUID,              -- reference to conversation or source
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Data sources: user-uploaded or created context (NotebookLM-style)
CREATE TABLE IF NOT EXISTS public.data_sources (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id TEXT NOT NULL,
  name TEXT NOT NULL,
  source_type TEXT NOT NULL,    -- url, document, text, pdf, image
  content TEXT,                 -- raw content or extracted text
  url TEXT,                     -- original URL if applicable
  file_path TEXT,               -- GCS path if uploaded
  metadata JSONB DEFAULT '{}',
  embedding VECTOR(768),        -- embedded for semantic search
  status TEXT DEFAULT 'processing',  -- processing, ready, failed
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Enable pgvector extension for embeddings
CREATE EXTENSION IF NOT EXISTS vector;

-- Indexes
CREATE INDEX IF NOT EXISTS idx_conversations_user ON conversations(user_id, updated_at DESC);
CREATE INDEX IF NOT EXISTS idx_messages_conversation ON messages(conversation_id, created_at);
CREATE INDEX IF NOT EXISTS idx_messages_user ON messages(user_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_memory_user ON memory(user_id);
CREATE INDEX IF NOT EXISTS idx_memory_embedding ON memory USING ivfflat (embedding vector_cosine_ops) WITH (lists = 100);
CREATE INDEX IF NOT EXISTS idx_data_sources_user ON data_sources(user_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_data_sources_embedding ON data_sources USING ivfflat (embedding vector_cosine_ops) WITH (lists = 100);
