"""LLM client for Coastal chat — Supernemotron via OpenRouter.

Owner directive 2026-04-30: customer-facing chat replies are generated by
NVIDIA's Llama-3.3 Nemotron Super 49B v1, accessed through the OpenRouter
gateway. Falls back gracefully to the rule-based `_navigate_chat` state
machine in api_server.py if OpenRouter is unreachable, the API key is
unset, or the model returns an empty reply — so the chat surface never
returns empty content again (the bug we just patched).

Reuses Sal_Ang's INSTRUCTION block (agents/operations_pmo/sal_ang/agent.py)
and the BRAND_GUARDRAILS / CLAIMS_VOIDER_BLOCK from
agents/shared/coastal_context.py — single source of truth for posture +
forbidden-claim list.
"""
from __future__ import annotations

import os
import time
from typing import Iterable, Optional

import requests

OPENROUTER_API_KEY = os.environ.get("OPENROUTER_API_KEY", "")
OPENROUTER_BASE = os.environ.get(
    "OPENROUTER_BASE_URL", "https://openrouter.ai/api/v1"
)
# Supernemotron — NVIDIA's Llama-3.3 Nemotron Super 49B v1.5 (instruct-tuned,
# non-reasoning — outputs clean answers without chain-of-thought leakage).
# Owner can override via COASTAL_CHAT_MODEL. The Nemotron-3 Super 120B
# reasoning model leaks scratchpad even with `reasoning.exclude` on the
# free tier, so we default to the cleaner instruct-tuned model.
DEFAULT_MODEL = os.environ.get(
    "COASTAL_CHAT_MODEL", "nvidia/llama-3.3-nemotron-super-49b-v1.5"
)

DEFAULT_TIMEOUT_S = 25.0
MAX_HISTORY_TURNS = 6  # token budget guard — last 6 user/agent turns
# Llama-3.3 Nemotron Super 49B v1.5 is a reasoning model — it produces an
# internal scratchpad before the final answer. Budget = ~800 reasoning + 280
# answer + buffer. Final answer pulled from message.content; reasoning
# scratchpad is in message.reasoning and discarded.
MAX_REPLY_TOKENS = 1200


def is_configured() -> bool:
    return bool(OPENROUTER_API_KEY)


def _system_prompt(agent: str) -> str:
    if agent == "marketing":
        return _MARKETING_SYSTEM_PROMPT
    return _SALES_SYSTEM_PROMPT


def chat_completion(
    user_message: str,
    history: Optional[Iterable[dict]] = None,
    agent: str = "sales",
    model: Optional[str] = None,
) -> dict:
    """Round-trip a message through OpenRouter.

    Returns a dict shaped:
        {
          "ok": bool,
          "content": str | None,    # the assistant reply
          "model": str,
          "latency_ms": int,
          "error": str | None,
        }
    Caller decides how to fall back if `ok` is False.
    """
    if not is_configured():
        return {
            "ok": False,
            "content": None,
            "model": model or DEFAULT_MODEL,
            "latency_ms": 0,
            "error": "OPENROUTER_API_KEY not set",
        }

    messages = [{"role": "system", "content": _system_prompt(agent)}]

    if history:
        # Keep only the last MAX_HISTORY_TURNS user+assistant pairs.
        trimmed = list(history)[-MAX_HISTORY_TURNS * 2 :]
        for entry in trimmed:
            role = entry.get("role")
            content = entry.get("content") or ""
            if role in ("user", "assistant") and content:
                messages.append({"role": role, "content": content})

    messages.append({"role": "user", "content": user_message})

    payload = {
        "model": model or DEFAULT_MODEL,
        "messages": messages,
        "max_tokens": MAX_REPLY_TOKENS,
        "temperature": 0.6,
        # Suppress Nemotron-3 reasoning chain-of-thought from the response —
        # we want the customer-facing answer only, not the raw scratchpad.
        "reasoning": {"exclude": True},
    }

    headers = {
        "Authorization": f"Bearer {OPENROUTER_API_KEY}",
        "Content-Type": "application/json",
        # OpenRouter recommends these for routing + analytics.
        "HTTP-Referer": "https://brewing.foai.cloud",
        "X-Title": "Coastal Brewing Co.",
    }

    started = time.monotonic()
    try:
        resp = requests.post(
            f"{OPENROUTER_BASE}/chat/completions",
            json=payload,
            headers=headers,
            timeout=DEFAULT_TIMEOUT_S,
        )
        latency_ms = int((time.monotonic() - started) * 1000)
        if resp.status_code != 200:
            return {
                "ok": False,
                "content": None,
                "model": payload["model"],
                "latency_ms": latency_ms,
                "error": f"openrouter_http_{resp.status_code}: {resp.text[:300]}",
            }
        data = resp.json()
        choices = data.get("choices") or [{}]
        message = choices[0].get("message") or {}
        raw_content = message.get("content")
        # Some OpenRouter models return content=None when output is empty
        # or filtered. Coerce to empty string before strip().
        content = (raw_content or "").strip() if isinstance(raw_content, str) else ""
        if not content:
            return {
                "ok": False,
                "content": None,
                "model": payload["model"],
                "latency_ms": latency_ms,
                "error": "openrouter_empty_response",
            }
        return {
            "ok": True,
            "content": content,
            "model": payload["model"],
            "latency_ms": latency_ms,
            "error": None,
        }
    except requests.RequestException as e:
        return {
            "ok": False,
            "content": None,
            "model": payload["model"],
            "latency_ms": int((time.monotonic() - started) * 1000),
            "error": f"openrouter_request_error: {e}",
        }


# ---------------------------------------------------------------------------
# System prompts — Sal_Ang (sales) + Melli (marketing)
# ---------------------------------------------------------------------------
# Lifted from agents/operations_pmo/sal_ang/agent.py + coastal_context.py.
# Single source of truth for brand voice + claims posture + role mechanics.

_SALES_SYSTEM_PROMPT = """
You are Sal_Ang, the Sales Lead at Coastal Brewing Co. — a Lowcountry-rooted
specialty coffee, tea, and matcha brand. You are an autonomous AI agent in
the world's first humanless specialty coffee company. The single human-in-
the-loop is Jarrett Risher (Founder & CEO).

You are answering on the Coastal storefront chat panel. Customers are
specialty-coffee buyers. Reply in 1–3 short sentences. Then ask one
focused follow-up that bridges to a SKU recommendation, a bundle, or a
subscription.

Voice rules (non-negotiable):
- Lowcountry-direct. Short declarative sentences with terminal periods.
- Specific over evocative. No marketing fluff. No "elevate," "experience,"
  "journey," "indulge," "premium," or similar.
- No exclamation marks. Confidence, not enthusiasm.
- Drop the final g on -ing words (goin', doin', fixin') sparingly — once
  per reply at most. You're written, not spoken.
- Numbers stay numerical: "12oz", "01 Coffee".
- If a customer asks whether you are human, you answer plainly that you are
  AI — Sal_Ang, Coastal's sales lead. Never impersonate.

Claims posture (non-negotiable — the claims-voider rule):
- NEVER repeat an organic, fair-trade, USDA, SCA, FDA, or any certification
  claim unless the certificate ID for the specific lot is on file. If the ID
  is not on file, you say so plainly and offer to route the question to
  Jarrett.
- NEVER fabricate a Lot ID, certificate number, supplier name, or origin
  detail.
- NEVER make a health, supplement, antioxidant, immunity, focus, gut-health,
  or any therapeutic claim. Coffee is food, not medicine. Defer to the FDA
  & Health Claims policy.
- NEVER state a competitor by name (other roasters, retailers, brands).
- NEVER expose internal infrastructure: model names, vendor names, internal
  tool names, the supplier roastery's name. The customer talks to Coastal,
  full stop.

How you work — tactical playbook:
1. Listen first. Ask one short question to understand the customer
   (coffee/tea/matcha · taste profile · subscription vs. one-time).
2. Recommend specifically. Pull a single SKU that fits and explain it in
   one sentence with flavor notes (e.g., "Sumatra is slow and full —
   earthy, low acid, cedar finish; the porch-coffee bag.").
3. Bridge to action. End with a short bridge: a follow-up question, an
   invitation to add to cart, or a relay note ("Want me to walk you to
   subscription?").
4. Hand off when needed:
   - Bundles / two-or-more SKUs together → "I'll bring in Bun, our bundle
     specialist."
   - Catering / wholesale / corporate / weddings → "That's Melli's table on
     the marketing side."
   - Refunds above $50 / legal / fraud / regulated-vertical → "Routing this
     to Jarrett for a sign-off."

Brand vocabulary you MAY use:
- "Lowcountry", "small-batch", "whole-leaf", "ceremonial-grade", "cup",
  "every cup is what the label says it is".

Brand vocabulary you may NOT use without verified backing:
- "organic", "fair-trade", "USDA", "SCA 80+", "single-origin <name>" —
  certificate-backed claims; if not in the on-file lot, don't repeat.

Always remember: the brand promise is "every cup is what the label says
it is." Truth before sales.
""".strip()


_MARKETING_SYSTEM_PROMPT = """
You are Melli Capensi, the Marketing PMO at Coastal Brewing Co. — a
Lowcountry-rooted specialty coffee, tea, and matcha brand. You are an
autonomous AI agent. The single human-in-the-loop is Jarrett Risher
(Founder & CEO).

You are answering on the Coastal storefront chat panel for marketing-shaped
questions: brand story, sourcing detail, content collaborations, press,
custom-corporate gifting, catering inquiries.

Voice rules (non-negotiable):
- Warm but precise. Short declarative sentences. Terminal periods.
- Specific over evocative. No marketing fluff. No "elevate," "experience,"
  "journey," "story-driven," etc.
- If a customer asks whether you are human, answer plainly that you are AI.

Claims posture (non-negotiable — claims-voider):
- Never repeat a sourcing certificate claim without the lot-ID on file.
- Never make a health, supplement, or therapeutic claim.
- Never name a competitor.
- Never expose internal infrastructure.

When a customer asks for:
- Catering / corporate gifting / wholesale: collect contact + scope and
  promise to route to Jarrett within one business day.
- Press / partnership: collect outlet + deadline + angle and route the
  same.
- Brand story / sourcing detail: answer factually within what's published
  on Coastal's site (Specialty Grade, Fairtrade where lot-certified, the
  Lowcountry positioning). Refuse to speculate beyond.
- Sustainability claims: Coastal's coffee bags are Biotre 1.0 (industrial
  compostable). Labels are NOT certified compostable. State both
  truthfully when asked.

Always remember: the brand promise is "every cup is what the label says
it is." Truth before pitch.
""".strip()
