/**
 * DMADV — Design, Measure, Analyze, Design, Verify.
 * Used for NEW tier/feature design validation BEFORE launching to real clients.
 * Tests against synthetic podcaster personas generated by Sqwaadrun.
 *
 * DMAIC grades existing deliverables.
 * DMADV validates that a new tier/feature CAN deliver before it ships.
 *
 * Flow: Define requirements → Measure quality metrics → Analyze feasibility
 *       → Design producer workflow → Verify with synthetic personas
 *
 * Nothing launches without DMADV verification passing.
 */

import { gradeDeliverable, type GraderInput } from './grader';
import {
  type Grade,
  type DmadvDesignSpec,
  type DmadvPhase,
  scoreToGrade,
  isShippable,
} from './types';

export interface DmadvInput {
  tierOrFeature: string;
  customerRequirements: string[];
  targetPersonas: string[];
  qualityMetrics: string[];
  costModel: {
    estimatedMonthlyCost: number;
    tierPrice: number;
  };
  producerWorkflow: string[];
  deliverableSet: string[];
  sqwaadrunMissions: string[];
}

export interface DmadvVerificationResult {
  specId: string;
  phase: DmadvPhase;
  canDeliver: boolean;
  projectedMargin: number;
  risks: string[];
  costGaps: string[];
  approvedForLaunch: boolean;
  spec: DmadvDesignSpec;
}

export function runDmadvDefineAndAnalyze(input: DmadvInput): DmadvVerificationResult {
  const specId = `DMADV-${Date.now().toString(36)}`;

  // ── DEFINE ──
  const defined = {
    customerRequirements: input.customerRequirements,
    targetPersonas: input.targetPersonas,
  };

  // ── MEASURE ──
  const projectedMargin = input.costModel.tierPrice > 0
    ? Math.round(((input.costModel.tierPrice - input.costModel.estimatedMonthlyCost) / input.costModel.tierPrice) * 100)
    : 0;

  const measured = {
    qualityMetrics: input.qualityMetrics,
    costModel: {
      estimatedMonthlyCost: input.costModel.estimatedMonthlyCost,
      tierPrice: input.costModel.tierPrice,
      projectedMargin,
    },
  };

  // ── ANALYZE ──
  const risks: string[] = [];
  const costGaps: string[] = [];

  if (projectedMargin < 0) {
    costGaps.push(`Negative margin: cost $${input.costModel.estimatedMonthlyCost}/mo exceeds price $${input.costModel.tierPrice}/mo`);
  } else if (projectedMargin < 15) {
    risks.push(`Thin margin (${projectedMargin}%) — limited room for cost increases`);
  }

  if (input.deliverableSet.length === 0) {
    risks.push('No deliverables defined for this tier');
  }

  if (input.producerWorkflow.length === 0) {
    risks.push('No producer workflow defined — how does the agent execute?');
  }

  if (input.targetPersonas.length === 0) {
    risks.push('No target personas — who is this for?');
  }

  if (input.customerRequirements.length === 0) {
    risks.push('No customer requirements — what does this tier promise?');
  }

  const canDeliver = costGaps.length === 0 &&
    input.deliverableSet.length > 0 &&
    input.producerWorkflow.length > 0;

  // ── DESIGN ──
  const designed = {
    producerWorkflow: input.producerWorkflow,
    deliverableSet: input.deliverableSet,
    sqwaadrunMissions: input.sqwaadrunMissions,
  };

  // ── VERIFY (placeholder — actual verification runs against synthetic personas) ──
  const verified = {
    syntheticPersonasTested: 0,
    passRate: 0,
    averageGrade: 'D' as Grade,
    issues: ['Verification not yet run — call verifyWithSyntheticPersonas()'],
    approvedForLaunch: false,
  };

  const spec: DmadvDesignSpec = {
    specId,
    tierOrFeature: input.tierOrFeature,
    phase: canDeliver ? 'design' : 'analyze',
    defined,
    measured,
    analyzed: { canDeliver, risks, costGaps },
    designed,
    verified,
  };

  return {
    specId,
    phase: spec.phase,
    canDeliver,
    projectedMargin,
    risks,
    costGaps,
    approvedForLaunch: false,
    spec,
  };
}

export function verifyWithSyntheticPersonas(
  spec: DmadvDesignSpec,
  syntheticDeliverables: GraderInput[],
): DmadvDesignSpec {
  const results = syntheticDeliverables.map(d => gradeDeliverable(d));

  const passCount = results.filter(r => isShippable(r.grade)).length;
  const passRate = syntheticDeliverables.length === 0
    ? 0
    : Math.round((passCount / syntheticDeliverables.length) * 100);

  const totalScore = results.reduce((sum, r) => sum + r.score, 0);
  const avgScore = results.length === 0 ? 0 : Math.round(totalScore / results.length);
  const averageGrade = scoreToGrade(avgScore);

  const issues: string[] = [];
  for (const r of results) {
    if (!isShippable(r.grade)) {
      issues.push(`${r.audit.deliverableType} scored ${r.score} (${r.grade}) — below shipping threshold`);
    }
    if (!r.formattingPassed) {
      issues.push(`${r.audit.deliverableType} has formatting issues: ${r.formattingIssues.join(', ')}`);
    }
  }

  // Approved if >= 80% pass rate AND average grade is shippable
  const approvedForLaunch = passRate >= 80 && isShippable(averageGrade);

  return {
    ...spec,
    phase: 'verify',
    verified: {
      syntheticPersonasTested: syntheticDeliverables.length,
      passRate,
      averageGrade,
      issues,
      approvedForLaunch,
    },
  };
}
