/**
 * Per|Form NFL Draft Seed Data — 2026 NFL Draft
 *
 * Top draft-eligible prospects and NFL team needs.
 * This seed data bootstraps the draft engine. Once seeded,
 * prospects are enriched via Brave Search and CFBD API.
 *
 * NOTE: The 2025 class (Ward, Hunter, Sanders, Carter, etc.) is now in
 * the NFL. See REDRAFT_2025_PROSPECTS for rookie season re-evaluation.
 *
 * Tiers:
 *   TOP_5     — Consensus top 5 pick
 *   TOP_15    — First half of round 1
 *   FIRST_ROUND — Late round 1
 *   DAY_2     — Rounds 2-3
 *   DAY_3     — Rounds 4-7
 *   PRIORITY_UDFA — Top undrafted free agents
 *   UDFA      — Undrafted free agent
 */

export interface SeedDraftProspect {
  firstName: string;
  lastName: string;
  position: string;
  college: string;
  conference?: string;
  classYear: string;
  eligibility?: string;
  height?: string;
  weight?: number;
  paiScore: number;
  tier: string;
  performance: number;
  athleticism: number;
  intangibles: number;
  overallRank: number;
  positionRank: number;
  trend: string;
  scoutMemo?: string;
  tags?: string;
  comparisons?: string;
  collegeStats?: string;
  combineInvite?: boolean;
  seniorBowl?: boolean;
  projectedRound?: number;
  projectedPick?: number;
  bullCase?: string;
  bearCase?: string;
  mediationVerdict?: string;
  debateWinner?: string;
  enrichedBy?: string;
}

// ─────────────────────────────────────────────────────────────
// 2026 NFL Draft — Top 32 Prospects (Real Players, Real Data)
// Combine: Feb 23 – Mar 2, 2026 | Draft: April 2026
// ─────────────────────────────────────────────────────────────

export const SEED_DRAFT_PROSPECTS: SeedDraftProspect[] = [
  // ── TOP_5 ─────────────────────────────────────────────────
  {
    firstName: 'Fernando',
    lastName: 'Mendoza',
    position: 'QB',
    college: 'Indiana',
    conference: 'Big Ten',
    classYear: 'Senior',
    eligibility: 'RS-Senior',
    height: "6'3\"",
    weight: 220,
    paiScore: 101,
    tier: 'TOP_5',
    performance: 99,
    athleticism: 92,
    intangibles: 99,
    overallRank: 1,
    positionRank: 1,
    trend: 'STEADY',
    scoutMemo: "2025 Heisman Trophy winner who led Indiana to an undefeated season and National Championship. Elite pocket passer with accuracy, mobility, and composure that translates directly to the NFL. The most complete QB prospect since Andrew Luck.",
    tags: JSON.stringify(['heisman', 'national-champion', 'pocket-passer', 'accurate', 'mobile', 'winner']),
    comparisons: JSON.stringify(['Andrew Luck completeness', 'Joe Burrow composure', 'Peyton Manning processing']),
    combineInvite: true,
    projectedRound: 1,
    projectedPick: 1,
    bullCase: "Mendoza did something no one has ever done at Indiana — went undefeated, won the Heisman, and brought home a national championship. His accuracy, pocket presence, and ability to extend plays make him the safest QB pick in years.",
    bearCase: "Indiana's strength of schedule, even in the Big Ten, doesn't match what elite QBs typically face. Can his accuracy hold up against NFL pass rushes? Smaller school pedigree raises questions about adjustment curve.",
    mediationVerdict: "Bull wins decisively. National championship QB with Heisman credentials and Big Ten-tested film. The pedigree concern is invalid — he beat the Big Ten's best and won it all. QB1.",
    debateWinner: 'BULL',
    enrichedBy: 'manual',
  },
  {
    firstName: 'Caleb',
    lastName: 'Downs',
    position: 'S',
    college: 'Ohio State',
    conference: 'Big Ten',
    classYear: 'Junior',
    eligibility: 'Junior (declared)',
    height: "6'0\"",
    weight: 200,
    paiScore: 96,
    tier: 'TOP_5',
    performance: 97,
    athleticism: 96,
    intangibles: 95,
    overallRank: 2,
    positionRank: 1,
    trend: 'STEADY',
    scoutMemo: "The best safety prospect in years. Elite instincts, turnover generation, and versatility. Plays deep safety, box, nickel — anywhere you put him, he impacts the game. Often cited as the #1 overall prospect regardless of position.",
    tags: JSON.stringify(['ball-hawk', 'versatile', 'instincts', 'tackling', 'turnover-machine', 'leadership']),
    comparisons: JSON.stringify(['Ed Reed instincts', 'Derwin James versatility', 'Sean Taylor physicality']),
    combineInvite: true,
    projectedRound: 1,
    projectedPick: 2,
    bullCase: "Downs is the best defensive prospect in this draft. His ability to generate turnovers, cover, and tackle makes him a defensive game-changer from Day 1. Positional value is the only argument against him at #2.",
    bearCase: "Safety is a devalued position in today's NFL. When's the last time a safety went top 3? His impact may not justify the pick over a premium position like EDGE or QB.",
    mediationVerdict: "Bull wins. Talent transcends positional value. Downs transforms a defense the way Ed Reed did. If you're picking for impact, not convention, he's as safe as it gets.",
    debateWinner: 'BULL',
    enrichedBy: 'manual',
  },
  {
    firstName: 'Rueben',
    lastName: 'Bain Jr.',
    position: 'EDGE',
    college: 'Miami (FL)',
    conference: 'ACC',
    classYear: 'Junior',
    eligibility: 'Junior (declared)',
    height: "6'4\"",
    weight: 255,
    paiScore: 94,
    tier: 'TOP_5',
    performance: 94,
    athleticism: 95,
    intangibles: 92,
    overallRank: 3,
    positionRank: 1,
    trend: 'UP',
    scoutMemo: "Dominant pass rusher with elite film. Not just a situational rusher — strong against the run, sets the edge, and collapses the pocket. Combined with Akheem Mesidor to give Miami one of the best pass rush duos in college football. Complete defensive end.",
    tags: JSON.stringify(['pass-rusher', 'complete-de', 'run-defense', 'motor', 'acc-dominant']),
    comparisons: JSON.stringify(['Myles Garrett power', 'Nick Bosa technique', 'Khalil Mack motor']),
    combineInvite: true,
    projectedRound: 1,
    projectedPick: 3,
    bullCase: "Bain is a complete defensive end. His pass rush film is elite AND his run defense sets him apart from every other EDGE in this class. Day 1 starter who impacts immediately.",
    bearCase: "ACC competition level is a step below the SEC and Big Ten. Can his dominance translate against NFL-caliber offensive tackles? Some want to see more explosive first-step data from the combine.",
    mediationVerdict: "Bull wins. The film is undeniable. ACC competition concerns are overblown — Miami played a tough schedule. Bain is as safe as any EDGE in this class.",
    debateWinner: 'BULL',
    enrichedBy: 'manual',
  },
  {
    firstName: 'T.J.',
    lastName: 'Parker',
    position: 'EDGE',
    college: 'Clemson',
    conference: 'ACC',
    classYear: 'Junior',
    eligibility: 'Junior (declared)',
    height: "6'5\"",
    weight: 260,
    paiScore: 93,
    tier: 'TOP_5',
    performance: 93,
    athleticism: 94,
    intangibles: 91,
    overallRank: 4,
    positionRank: 2,
    trend: 'STEADY',
    scoutMemo: "Led Power Four edge rushers in sacks in 2024. Devastating bull-rush — the best in this class. Length and power combination is rare. Clemson continues to produce elite defensive linemen.",
    tags: JSON.stringify(['bull-rush', 'power', 'length', 'sack-artist', 'clemson-pedigree']),
    comparisons: JSON.stringify(['Jadeveon Clowney power', 'DeMarcus Ware pass rush', 'Aidan Hutchinson motor']),
    combineInvite: true,
    projectedRound: 1,
    projectedPick: 4,
    enrichedBy: 'manual',
  },
  {
    firstName: 'Francis',
    lastName: 'Mauigoa',
    position: 'OT',
    college: 'Miami (FL)',
    conference: 'ACC',
    classYear: 'Junior',
    eligibility: 'Junior (declared)',
    height: "6'5\"",
    weight: 330,
    paiScore: 91,
    tier: 'TOP_5',
    performance: 91,
    athleticism: 89,
    intangibles: 92,
    overallRank: 5,
    positionRank: 1,
    trend: 'STEADY',
    scoutMemo: "Top offensive tackle in the 2026 class. Plays with nastiness — finishes blocks and pancakes defenders. Versatile: plays tackle and can kick inside to guard. Complete offensive lineman with an edge.",
    tags: JSON.stringify(['nasty', 'finisher', 'versatile-ol', 'pancakes', 'attitude']),
    comparisons: JSON.stringify(['Quenton Nelson nastiness', 'Trent Williams athleticism']),
    combineInvite: true,
    projectedRound: 1,
    projectedPick: 5,
    enrichedBy: 'manual',
  },

  // ── TOP_15 ────────────────────────────────────────────────
  {
    firstName: 'Arvell',
    lastName: 'Reese',
    position: 'LB',
    college: 'Ohio State',
    conference: 'Big Ten',
    classYear: 'Junior',
    eligibility: 'Junior (declared)',
    height: "6'3\"",
    weight: 240,
    paiScore: 91,
    tier: 'TOP_15',
    performance: 90,
    athleticism: 93,
    intangibles: 89,
    overallRank: 6,
    positionRank: 1,
    trend: 'UP',
    scoutMemo: "Explosive and versatile — plays both off-ball LB and EDGE. Physicality and speed combination is rare in this class. Ohio State's defense asked him to do everything and he delivered.",
    tags: JSON.stringify(['hybrid', 'explosive', 'versatile', 'physical', 'osu-pedigree']),
    comparisons: JSON.stringify(['Micah Parsons versatility', 'Patrick Queen speed']),
    combineInvite: true,
    projectedRound: 1,
    projectedPick: 7,
    enrichedBy: 'manual',
  },
  {
    firstName: 'Jeremiyah',
    lastName: 'Love',
    position: 'RB',
    college: 'Notre Dame',
    conference: 'Independent',
    classYear: 'Junior',
    eligibility: 'Junior (declared)',
    height: "5'11\"",
    weight: 210,
    paiScore: 90,
    tier: 'TOP_15',
    performance: 93,
    athleticism: 94,
    intangibles: 84,
    overallRank: 7,
    positionRank: 1,
    trend: 'UP',
    scoutMemo: "Dynamic running back with home-run speed and explosiveness. Effective receiver out of the backfield. Notre Dame featured him as the centerpiece of their offense. One cut and gone.",
    tags: JSON.stringify(['speed', 'explosiveness', 'home-run', 'receiving-back', 'dynamic']),
    comparisons: JSON.stringify(['Chris Johnson speed', 'Alvin Kamara versatility']),
    combineInvite: true,
    projectedRound: 1,
    projectedPick: 8,
    bullCase: "Love has home-run ability that makes offensive coordinators dream. His speed and explosiveness are elite, and he catches the ball out of the backfield. Three-down back potential.",
    bearCase: "Running back positional value remains questionable in the first round. Notre Dame's schedule doesn't include conference championships. Can he handle a full NFL workload at 210 lbs?",
    mediationVerdict: "Split. The talent is undeniable but the positional value debate is real. Love is RB1 but may need the right landing spot to justify a top-10 pick.",
    debateWinner: 'SPLIT',
    enrichedBy: 'manual',
  },
  {
    firstName: 'Makai',
    lastName: 'Lemon',
    position: 'WR',
    college: 'USC',
    conference: 'Big Ten',
    classYear: 'Junior',
    eligibility: 'Junior (declared)',
    height: "5'11\"",
    weight: 185,
    paiScore: 89,
    tier: 'TOP_15',
    performance: 90,
    athleticism: 91,
    intangibles: 86,
    overallRank: 8,
    positionRank: 1,
    trend: 'UP',
    scoutMemo: "Route-running technician with contested-catch ability. The most complete receiver in this class — wins at every level of the field. USC product with big-game experience.",
    tags: JSON.stringify(['route-runner', 'contested-catch', 'complete-wr', 'usc-pedigree']),
    comparisons: JSON.stringify(['Keenan Allen route-running', 'DeAndre Hopkins contested catches']),
    combineInvite: true,
    projectedRound: 1,
    projectedPick: 9,
    enrichedBy: 'manual',
  },
  {
    firstName: 'Kenyon',
    lastName: 'Sadiq',
    position: 'TE',
    college: 'Oregon',
    conference: 'Big Ten',
    classYear: 'Junior',
    eligibility: 'Junior (declared)',
    height: "6'5\"",
    weight: 250,
    paiScore: 88,
    tier: 'TOP_15',
    performance: 89,
    athleticism: 88,
    intangibles: 87,
    overallRank: 9,
    positionRank: 1,
    trend: 'STEADY',
    scoutMemo: "Best tight end in the 2026 class. Red zone weapon with blocking ability — does everything you want from a modern TE. Running, blocking, and pass-catching are all at a high level.",
    tags: JSON.stringify(['complete-te', 'red-zone', 'blocking', 'receiving', 'yac']),
    comparisons: JSON.stringify(['George Kittle all-around', 'Mark Andrews red-zone usage']),
    combineInvite: true,
    projectedRound: 1,
    projectedPick: 12,
    enrichedBy: 'manual',
  },
  {
    firstName: 'Kadyn',
    lastName: 'Proctor',
    position: 'OT',
    college: 'Alabama',
    conference: 'SEC',
    classYear: 'Junior',
    eligibility: 'Junior (declared)',
    height: "6'7\"",
    weight: 335,
    paiScore: 87,
    tier: 'TOP_15',
    performance: 87,
    athleticism: 86,
    intangibles: 89,
    overallRank: 10,
    positionRank: 2,
    trend: 'STEADY',
    scoutMemo: "Enormous tackle prospect with excellent feet and agility for his size. Excels in pass protection and run blocking. SEC-tested against the best defensive lines in college football.",
    tags: JSON.stringify(['massive', 'feet', 'pass-protector', 'sec-tested', 'run-blocker']),
    comparisons: JSON.stringify(['Orlando Brown size', 'Laremy Tunsil technique']),
    combineInvite: true,
    projectedRound: 1,
    projectedPick: 14,
    enrichedBy: 'manual',
  },
  {
    firstName: 'David',
    lastName: 'Bailey',
    position: 'EDGE',
    college: 'Texas Tech',
    conference: 'Big 12',
    classYear: 'Senior',
    eligibility: 'RS-Senior',
    height: "6'4\"",
    weight: 265,
    paiScore: 87,
    tier: 'TOP_15',
    performance: 89,
    athleticism: 88,
    intangibles: 84,
    overallRank: 11,
    positionRank: 3,
    trend: 'UP',
    scoutMemo: "Led the FBS in sacks in his final season. Difference-maker against the run — not just a pass rush specialist. Texas Tech's best defensive player in years.",
    tags: JSON.stringify(['sack-leader', 'fbs-leader', 'run-defense', 'productive']),
    comparisons: JSON.stringify(['Chandler Jones production', 'Cameron Jordan run defense']),
    combineInvite: true,
    projectedRound: 1,
    projectedPick: 15,
    enrichedBy: 'manual',
  },
  {
    firstName: 'Akheem',
    lastName: 'Mesidor',
    position: 'EDGE',
    college: 'Miami (FL)',
    conference: 'ACC',
    classYear: 'Senior',
    eligibility: 'RS-Senior',
    height: "6'3\"",
    weight: 260,
    paiScore: 86,
    tier: 'TOP_15',
    performance: 87,
    athleticism: 87,
    intangibles: 83,
    overallRank: 12,
    positionRank: 4,
    trend: 'UP',
    scoutMemo: "10.5 sacks in his final year. Versatile — plays both edge and interior. Paired with Rueben Bain to form one of the most dominant pass rush duos in college football. Miami's defensive line factory continues.",
    tags: JSON.stringify(['versatile-dl', 'interior-flex', 'sack-production', 'miami-duo']),
    comparisons: JSON.stringify(['Aaron Donald inside move', 'Chris Jones versatility']),
    combineInvite: true,
    projectedRound: 1,
    projectedPick: 17,
    enrichedBy: 'manual',
  },
  {
    firstName: 'Connor',
    lastName: 'Lew',
    position: 'C',
    college: 'Auburn',
    conference: 'SEC',
    classYear: 'Junior',
    eligibility: 'Junior (declared)',
    height: "6'3\"",
    weight: 300,
    paiScore: 84,
    tier: 'TOP_15',
    performance: 85,
    athleticism: 82,
    intangibles: 86,
    overallRank: 13,
    positionRank: 1,
    trend: 'DOWN',
    scoutMemo: "Technical center with strong leadership and awareness. SEC-tested. Suffered ACL injury in October 2025 — recovery timeline is key. Pre-injury, he was the consensus top center in the class.",
    tags: JSON.stringify(['technical', 'leadership', 'acl-injury', 'sec-tested', 'awareness']),
    comparisons: JSON.stringify(['Jason Kelce technique', 'Tyler Linderbaum awareness']),
    combineInvite: true,
    projectedRound: 1,
    projectedPick: 20,
    bullCase: "Pre-injury, Lew was the best center prospect in years. His technique and leadership are elite. ACL recovery is routine now — he'll be ready for training camp.",
    bearCase: "ACL tear in October 2025 changes everything. Can he pass combine medicals? Centers rarely go first round. The injury drops him to Day 2.",
    mediationVerdict: "Split. The talent pre-injury was first-round caliber. Medical checks at the combine will determine his draft stock. High risk, high reward.",
    debateWinner: 'SPLIT',
    enrichedBy: 'manual',
  },

  // ── FIRST_ROUND ───────────────────────────────────────────
  {
    firstName: 'Ty',
    lastName: 'Simpson',
    position: 'QB',
    college: 'Alabama',
    conference: 'SEC',
    classYear: 'Junior',
    eligibility: 'Junior (declared)',
    height: "6'1\"",
    weight: 215,
    paiScore: 84,
    tier: 'FIRST_ROUND',
    performance: 84,
    athleticism: 86,
    intangibles: 82,
    overallRank: 14,
    positionRank: 2,
    trend: 'DOWN',
    scoutMemo: "Well-rounded QB with adequate arm strength and accuracy. Late-season injuries and inconsistencies caused some evaluators to pause. SEC pedigree is valuable but questions remain about his ceiling.",
    tags: JSON.stringify(['well-rounded', 'sec-qb', 'inconsistent', 'injury-concern']),
    comparisons: JSON.stringify(['Dak Prescott steadiness', 'Kirk Cousins accuracy']),
    combineInvite: true,
    projectedRound: 1,
    projectedPick: 22,
    enrichedBy: 'manual',
  },
  {
    firstName: 'Carson',
    lastName: 'Beck',
    position: 'QB',
    college: 'Miami (FL)',
    conference: 'ACC',
    classYear: 'Senior',
    eligibility: 'RS-Senior',
    height: "6'4\"",
    weight: 225,
    paiScore: 82,
    tier: 'FIRST_ROUND',
    performance: 82,
    athleticism: 80,
    intangibles: 83,
    overallRank: 15,
    positionRank: 3,
    trend: 'STEADY',
    scoutMemo: "Transferred from Georgia to Miami. Adjusting to a new system but the arm talent and experience are there. Started for a national championship program. Questions about why he left Georgia.",
    tags: JSON.stringify(['transfer', 'georgia-pedigree', 'arm-talent', 'experience']),
    comparisons: JSON.stringify(['Matt Ryan poise', 'Matthew Stafford arm']),
    combineInvite: true,
    projectedRound: 1,
    projectedPick: 25,
    enrichedBy: 'manual',
  },
  {
    firstName: 'Garrett',
    lastName: 'Nussmeier',
    position: 'QB',
    college: 'LSU',
    conference: 'SEC',
    classYear: 'Junior',
    eligibility: 'Junior (declared)',
    height: "6'2\"",
    weight: 210,
    paiScore: 81,
    tier: 'FIRST_ROUND',
    performance: 82,
    athleticism: 79,
    intangibles: 81,
    overallRank: 16,
    positionRank: 4,
    trend: 'STEADY',
    scoutMemo: "LSU's franchise QB with arm talent and SEC pedigree. Joe Burrow's shadow looms large but Nussmeier has carved his own identity. Decision-making and consistency are his draft questions.",
    tags: JSON.stringify(['arm-talent', 'lsu-pedigree', 'sec-qb', 'gunslinger']),
    comparisons: JSON.stringify(['Joe Burrow poise', 'Drew Brees accuracy']),
    combineInvite: true,
    projectedRound: 1,
    projectedPick: 28,
    enrichedBy: 'manual',
  },
  {
    firstName: 'Taylen',
    lastName: 'Green',
    position: 'QB',
    college: 'Arkansas',
    conference: 'SEC',
    classYear: 'Junior',
    eligibility: 'Junior (declared)',
    height: "6'5\"",
    weight: 230,
    paiScore: 80,
    tier: 'FIRST_ROUND',
    performance: 79,
    athleticism: 88,
    intangibles: 75,
    overallRank: 17,
    positionRank: 5,
    trend: 'UP',
    scoutMemo: "Physical specimen at QB. Massive frame with dual-threat ability. Raw passer who needs development but the athletic tools are NFL starter caliber. Transferred from Boise State to Arkansas.",
    tags: JSON.stringify(['physical', 'dual-threat', 'raw', 'upside', 'athletic-freak']),
    comparisons: JSON.stringify(['Josh Allen build', 'Cam Newton athleticism']),
    combineInvite: true,
    projectedRound: 1,
    projectedPick: 30,
    enrichedBy: 'manual',
  },

  // ── ADDITIONAL FIRST_ROUND CALIBER (from Athletic beat writer evaluations, Feb 2026) ──
  {
    firstName: 'Carnell',
    lastName: 'Tate',
    position: 'WR',
    college: 'Ohio State',
    conference: 'Big Ten',
    classYear: 'Junior',
    eligibility: 'Junior (declared)',
    height: "6'3\"",
    weight: 195,
    paiScore: 88,
    tier: 'TOP_15',
    performance: 90,
    athleticism: 89,
    intangibles: 85,
    overallRank: 10,
    positionRank: 1,
    trend: 'UP',
    scoutMemo: "Exceptional route runner with zero recorded drops on 51 catches in 2025 (per PFF). Size, route-running fundamentals, and athleticism make him the WR1 in this class. Reliable contested-catch ability.",
    tags: JSON.stringify(['route-runner', 'zero-drops', 'contested-catch', 'osu-pedigree', 'wr1']),
    comparisons: JSON.stringify(['George Pickens build', 'AJ Green type']),
    combineInvite: true,
    projectedRound: 1,
    projectedPick: 9,
    bullCase: "Zero drops on 51 catches. Best WR in the class. Size, route-running, and reliability at the catch point are all elite. Teams with QB investments want a safety blanket like Tate.",
    bearCase: "Ohio State has produced WR busts before. Production has to be put in context of elite surrounding talent. Is he truly WR1 or benefiting from scheme?",
    mediationVerdict: "Bull wins. The zero-drop stat alone separates him. The film backs it up — Tate is the real deal.",
    debateWinner: 'BULL',
    enrichedBy: 'manual',
  },
  {
    firstName: 'Spencer',
    lastName: 'Fano',
    position: 'OT',
    college: 'Utah',
    conference: 'Big 12',
    classYear: 'Junior',
    eligibility: 'Junior (declared)',
    height: "6'7\"",
    weight: 315,
    paiScore: 87,
    tier: 'TOP_15',
    performance: 88,
    athleticism: 87,
    intangibles: 86,
    overallRank: 11,
    positionRank: 1,
    trend: 'STEADY',
    scoutMemo: "Athletic throughout his lower half, mirrors pass-rush assignments with ease. Well-balanced skill set with physicality as a run blocker. Played right tackle over final two college seasons with some left side experience. Cornerstone piece for an OL rebuild.",
    tags: JSON.stringify(['athletic', 'balanced', 'run-blocker', 'cornerstone', 'utah-proven']),
    comparisons: JSON.stringify(['Penei Sewell balance', 'Lane Johnson versatility']),
    combineInvite: true,
    projectedRound: 1,
    projectedPick: 6,
    enrichedBy: 'manual',
  },
  {
    firstName: 'Sonny',
    lastName: 'Styles',
    position: 'LB',
    college: 'Ohio State',
    conference: 'Big Ten',
    classYear: 'Junior',
    eligibility: 'Junior (declared)',
    height: "6'5\"",
    weight: 243,
    paiScore: 88,
    tier: 'TOP_15',
    performance: 89,
    athleticism: 91,
    intangibles: 85,
    overallRank: 9,
    positionRank: 2,
    trend: 'UP',
    scoutMemo: "Transitioned from safety to LB and dominated. Background as a DB gives him elite coverage ability. Incredibly athletic and rangy — always attacking downhill. Missed only 1 tackle in 2025. Stifles RBs, TEs, and WRs.",
    tags: JSON.stringify(['safety-convert', 'athletic', 'coverage-lb', 'zero-missed-tackles', 'osu-pedigree']),
    comparisons: JSON.stringify(['Micah Parsons athleticism', 'Patrick Willis violence']),
    combineInvite: true,
    projectedRound: 1,
    projectedPick: 10,
    bullCase: "Former safety playing LB = elite coverage skills. ONE missed tackle in 2025. At 6'5\" 243 he's a matchup nightmare. Three-down LB from Day 1.",
    bearCase: "LBs are not a premium position. He's still learning the position. Run defense needs to catch up to his coverage abilities.",
    mediationVerdict: "Bull wins on talent but bear has a point on positional value. The coverage ability at his size is too rare to pass up.",
    debateWinner: 'BULL',
    enrichedBy: 'manual',
  },
  {
    firstName: 'Mansoor',
    lastName: 'Delane',
    position: 'CB',
    college: 'LSU',
    conference: 'SEC',
    classYear: 'Junior',
    eligibility: 'Junior (declared)',
    height: "6'0\"",
    weight: 185,
    paiScore: 87,
    tier: 'TOP_15',
    performance: 89,
    athleticism: 88,
    intangibles: 84,
    overallRank: 12,
    positionRank: 1,
    trend: 'UP',
    scoutMemo: "Best corner in college football in 2025. Did not allow a TD or commit a penalty all season. Savvy fundamentals in press-man. Instinctual and patient — stays in-phase. Excels in press and off-man. Week 1 starter in the NFL.",
    tags: JSON.stringify(['lockdown', 'zero-tds-allowed', 'press-man', 'nfl-ready', 'lsu-db']),
    comparisons: JSON.stringify(['Sauce Gardner technique', 'Marshon Lattimore press']),
    combineInvite: true,
    projectedRound: 1,
    projectedPick: 11,
    enrichedBy: 'manual',
  },
  {
    firstName: 'Jermod',
    lastName: 'McCoy',
    position: 'CB',
    college: 'Tennessee',
    conference: 'SEC',
    classYear: 'Junior',
    eligibility: 'Junior (declared)',
    height: "6'1\"",
    weight: 190,
    paiScore: 86,
    tier: 'TOP_15',
    performance: 85,
    athleticism: 90,
    intangibles: 82,
    overallRank: 7,
    positionRank: 2,
    trend: 'DOWN',
    scoutMemo: "Top CB prospect but missed all of 2025 due to torn ACL (January 2025). More than 12 months removed. Elite athlete with terrific ball skills when healthy — 4 INTs in 2024. Medical checks at combine will be critical.",
    tags: JSON.stringify(['acl-recovery', 'elite-athlete', 'ball-skills', 'medical-flag', 'sec-cb']),
    comparisons: JSON.stringify(['Jaycee Horn upside', 'Pat Surtain II ball skills']),
    combineInvite: true,
    projectedRound: 1,
    projectedPick: 12,
    bullCase: "When healthy, McCoy is the best CB in this class. ACL recovery is routine now — 12+ months out. The ball skills and athleticism are elite.",
    bearCase: "Missed entire 2025 season. ACL tears change athletes. Teams drafting in the top 15 can't afford medical risks.",
    mediationVerdict: "Split. Everything hinges on combine medicals. If he passes, he's CB1. If there are any red flags, he slides to Day 2.",
    debateWinner: 'SPLIT',
    enrichedBy: 'manual',
  },
  {
    firstName: 'Vega',
    lastName: 'Ioane',
    position: 'IOL',
    college: 'Penn State',
    conference: 'Big Ten',
    classYear: 'Senior',
    eligibility: 'RS-Senior',
    height: "6'4\"",
    weight: 315,
    paiScore: 85,
    tier: 'FIRST_ROUND',
    performance: 87,
    athleticism: 83,
    intangibles: 86,
    overallRank: 14,
    positionRank: 1,
    trend: 'STEADY',
    scoutMemo: "Consensus top guard prospect. Tough, nasty, physical — blocks through the whistle. People mover with eye-popping power. Instant starter with Pro Bowl upside. Would be an immediate upgrade at either guard spot.",
    tags: JSON.stringify(['guard', 'nasty', 'people-mover', 'pro-bowl-upside', 'instant-starter']),
    comparisons: JSON.stringify(['Quenton Nelson power', 'Joel Bitonio technique']),
    combineInvite: true,
    projectedRound: 1,
    projectedPick: 14,
    enrichedBy: 'manual',
  },
  {
    firstName: 'Jordyn',
    lastName: 'Tyson',
    position: 'WR',
    college: 'Arizona State',
    conference: 'Big 12',
    classYear: 'Junior',
    eligibility: 'Junior (declared)',
    height: "6'2\"",
    weight: 200,
    paiScore: 85,
    tier: 'FIRST_ROUND',
    performance: 87,
    athleticism: 86,
    intangibles: 82,
    overallRank: 15,
    positionRank: 2,
    trend: 'STEADY',
    scoutMemo: "True X-receiver. Dominant at the catch point with alpha mentality in contested situations. Remarkable body control and mid-flight adjustments. Injury history (torn ACL 2022, collarbone/hamstring) gives some teams pause but talent is top-shelf.",
    tags: JSON.stringify(['x-receiver', 'contested-catch', 'alpha', 'body-control', 'medical-flag']),
    comparisons: JSON.stringify(['Mike Evans contested catches', 'DeAndre Hopkins hands']),
    combineInvite: true,
    projectedRound: 1,
    projectedPick: 15,
    enrichedBy: 'manual',
  },
  {
    firstName: 'Denzel',
    lastName: 'Boston',
    position: 'WR',
    college: 'Washington',
    conference: 'Big Ten',
    classYear: 'Junior',
    eligibility: 'Junior (declared)',
    height: "6'4\"",
    weight: 209,
    paiScore: 84,
    tier: 'FIRST_ROUND',
    performance: 86,
    athleticism: 85,
    intangibles: 82,
    overallRank: 16,
    positionRank: 3,
    trend: 'STEADY',
    scoutMemo: "Long-striding athlete dominant at the catch point — 80-20 advantage on 50-50 balls. Over 1,000 yards and 20 receiving TDs across last 2 seasons. Big-bodied WR who wins through physicality.",
    tags: JSON.stringify(['big-bodied', '50-50-balls', 'touchdowns', 'physical-wr']),
    comparisons: JSON.stringify(['Michael Pittman Jr.', 'Tee Higgins']),
    combineInvite: true,
    projectedRound: 1,
    projectedPick: 16,
    enrichedBy: 'manual',
  },
  {
    firstName: 'Monroe',
    lastName: 'Freeling',
    position: 'OT',
    college: 'Georgia',
    conference: 'SEC',
    classYear: 'Junior',
    eligibility: 'Junior (declared)',
    height: "6'7\"",
    weight: 315,
    paiScore: 84,
    tier: 'FIRST_ROUND',
    performance: 83,
    athleticism: 87,
    intangibles: 82,
    overallRank: 17,
    positionRank: 3,
    trend: 'UP',
    scoutMemo: "Just 16 career starts (declared after junior season). Athleticism, quickness, and length are evident. High upside worth exploring. Patience required as he develops. 34-inch arms. Franchise tackle potential if given time.",
    tags: JSON.stringify(['raw-upside', 'athletic', 'length', 'georgia-pedigree', '34-inch-arms']),
    comparisons: JSON.stringify(['Jedrick Wills upside', 'Andrew Thomas development']),
    combineInvite: true,
    projectedRound: 1,
    projectedPick: 17,
    enrichedBy: 'manual',
  },
  {
    firstName: 'Peter',
    lastName: 'Woods',
    position: 'DT',
    college: 'Clemson',
    conference: 'ACC',
    classYear: 'Junior',
    eligibility: 'Junior (declared)',
    height: "6'3\"",
    weight: 310,
    paiScore: 84,
    tier: 'FIRST_ROUND',
    performance: 82,
    athleticism: 89,
    intangibles: 80,
    overallRank: 18,
    positionRank: 1,
    trend: 'DOWN',
    scoutMemo: "Was #1 overall prospect entering 2025 season — production dipped (3 sacks, 2.5 TFL). Clemson's defense struggled overall. High-level flashes still present. Moves laterally like a much smaller player at 310 lbs. Violent hands. Rare power/athleticism combo.",
    tags: JSON.stringify(['fallen-from-#1', 'lateral-quickness', 'power', 'disruptive', 'underperformed']),
    comparisons: JSON.stringify(['Jeffery Simmons', 'Quinnen Williams']),
    combineInvite: true,
    projectedRound: 1,
    projectedPick: 18,
    bullCase: "Was the consensus #1 prospect entering 2025. The talent hasn't gone anywhere — Clemson's entire defense struggled. Combine will remind everyone why he was #1.",
    bearCase: "3 sacks and 2.5 TFL for a supposed #1 overall prospect? Production matters. You can't excuse an entire season of underwhelming play.",
    mediationVerdict: "Split. The physical tools are undeniable but the production dip is concerning. Combine performance will be decisive.",
    debateWinner: 'SPLIT',
    enrichedBy: 'manual',
  },
  {
    firstName: 'CJ',
    lastName: 'Allen',
    position: 'LB',
    college: 'Georgia',
    conference: 'SEC',
    classYear: 'Junior',
    eligibility: 'Junior (declared)',
    height: "6'1\"",
    weight: 235,
    paiScore: 83,
    tier: 'FIRST_ROUND',
    performance: 85,
    athleticism: 84,
    intangibles: 80,
    overallRank: 19,
    positionRank: 3,
    trend: 'STEADY',
    scoutMemo: "Outstanding instincts. Physical — triggers downhill with violence. Athleticism and acceleration to cover the entire field. Latest in a long line of elite Georgia linebackers.",
    tags: JSON.stringify(['instincts', 'physical', 'georgia-lb-factory', 'downhill']),
    comparisons: JSON.stringify(['Roquan Smith', 'Nakobe Dean instincts']),
    combineInvite: true,
    projectedRound: 1,
    projectedPick: 20,
    enrichedBy: 'manual',
  },
  {
    firstName: 'Cashius',
    lastName: 'Howell',
    position: 'EDGE',
    college: 'Texas A&M',
    conference: 'SEC',
    classYear: 'Senior',
    eligibility: 'RS-Senior',
    height: "6'2\"",
    weight: 248,
    paiScore: 83,
    tier: 'FIRST_ROUND',
    performance: 85,
    athleticism: 84,
    intangibles: 80,
    overallRank: 20,
    positionRank: 5,
    trend: 'UP',
    scoutMemo: "SEC Defensive Player of the Year. 25 sacks in three seasons, 11.5 in 2025. Doesn't have ideal size at 6-2/248 but track record of production against elite competition is undeniable. Immediate impact on passing downs.",
    tags: JSON.stringify(['sec-dpoy', 'production', 'undersized', 'pass-rush-specialist']),
    comparisons: JSON.stringify(['T.J. Watt motor', 'Khalil Mack burst']),
    combineInvite: true,
    projectedRound: 1,
    projectedPick: 21,
    enrichedBy: 'manual',
  },
  {
    firstName: 'Keldric',
    lastName: 'Faulk',
    position: 'EDGE',
    college: 'Auburn',
    conference: 'SEC',
    classYear: 'Sophomore',
    eligibility: 'RS-Sophomore (declared)',
    height: "6'6\"",
    weight: 280,
    paiScore: 82,
    tier: 'FIRST_ROUND',
    performance: 80,
    athleticism: 86,
    intangibles: 80,
    overallRank: 21,
    positionRank: 6,
    trend: 'STEADY',
    scoutMemo: "Won't turn 21 until Sept 7 — youngest first-rounder in the class. Long, strong, and athletic frame. High floor as a run defender. Pass-rush production needs to increase but the traits are tantalizing. 20-year-old developmental talent with massive ceiling.",
    tags: JSON.stringify(['youngest', 'developmental', 'long', 'athletic-frame', 'run-defender']),
    comparisons: JSON.stringify(['Myles Garrett build', 'Brian Burns length']),
    combineInvite: true,
    projectedRound: 1,
    projectedPick: 22,
    enrichedBy: 'manual',
  },
  {
    firstName: 'KC',
    lastName: 'Concepcion',
    position: 'WR',
    college: 'Texas A&M',
    conference: 'SEC',
    classYear: 'Junior',
    eligibility: 'Junior (declared)',
    height: "5'11\"",
    weight: 190,
    paiScore: 81,
    tier: 'FIRST_ROUND',
    performance: 83,
    athleticism: 84,
    intangibles: 77,
    overallRank: 22,
    positionRank: 4,
    trend: 'UP',
    scoutMemo: "Generates explosive plays with short-area quickness and open-field elusiveness. Improved as route runner in 2025. Drops have been an occasional issue but the explosive playmaking ability is undeniable.",
    tags: JSON.stringify(['explosive', 'quickness', 'yac-threat', 'drop-concern']),
    comparisons: JSON.stringify(['Zay Flowers', 'Tyreek Hill quickness']),
    combineInvite: true,
    projectedRound: 1,
    projectedPick: 24,
    enrichedBy: 'manual',
  },
  {
    firstName: 'R Mason',
    lastName: 'Thomas',
    position: 'EDGE',
    college: 'Oklahoma',
    conference: 'SEC',
    classYear: 'Junior',
    eligibility: 'Junior (declared)',
    height: "6'2\"",
    weight: 249,
    paiScore: 81,
    tier: 'FIRST_ROUND',
    performance: 82,
    athleticism: 84,
    intangibles: 78,
    overallRank: 23,
    positionRank: 7,
    trend: 'UP',
    scoutMemo: "Explosive, athletic, and strong. Good versatility — can move around and capitalize on mismatches. Impact edge player who can immediately bolster a defensive front.",
    tags: JSON.stringify(['explosive', 'versatile', 'mismatch', 'athletic']),
    comparisons: JSON.stringify(['Haason Reddick versatility']),
    combineInvite: true,
    projectedRound: 1,
    projectedPick: 26,
    enrichedBy: 'manual',
  },
  {
    firstName: 'Caleb',
    lastName: 'Lomu',
    position: 'OT',
    college: 'Utah',
    conference: 'Big 12',
    classYear: 'Junior',
    eligibility: 'Junior (declared)',
    height: "6'6\"",
    weight: 304,
    paiScore: 80,
    tier: 'FIRST_ROUND',
    performance: 81,
    athleticism: 83,
    intangibles: 77,
    overallRank: 24,
    positionRank: 4,
    trend: 'UP',
    scoutMemo: "Two-year starter at Utah who made clear strides in year two. Foot quickness indicates edge protection ability. Developmental arc shows more upside to explore. Should eventually serve as a quality bookend tackle.",
    tags: JSON.stringify(['developing', 'foot-quickness', 'utah-oline', 'upside']),
    comparisons: JSON.stringify(['Garett Bolles development arc']),
    combineInvite: true,
    projectedRound: 1,
    projectedPick: 28,
    enrichedBy: 'manual',
  },
  {
    firstName: 'Omar',
    lastName: 'Cooper Jr.',
    position: 'WR',
    college: 'Indiana',
    conference: 'Big Ten',
    classYear: 'Senior',
    eligibility: 'RS-Senior',
    height: "6'0\"",
    weight: 195,
    paiScore: 80,
    tier: 'FIRST_ROUND',
    performance: 82,
    athleticism: 81,
    intangibles: 78,
    overallRank: 25,
    positionRank: 5,
    trend: 'UP',
    scoutMemo: "Well-rounded skill set, effective route runner. Strong hands with consistent run-after-catch success. Tough, physical receiver. Should work out of slot in NFL. Perfect fit for offenses needing middle-of-the-field production.",
    tags: JSON.stringify(['slot-wr', 'rac-threat', 'physical', 'well-rounded']),
    comparisons: JSON.stringify(['Cooper Kupp slot work', 'Amon-Ra St. Brown toughness']),
    combineInvite: true,
    projectedRound: 1,
    projectedPick: 30,
    enrichedBy: 'manual',
  },
  {
    firstName: 'Zion',
    lastName: 'Young',
    position: 'EDGE',
    college: 'Missouri',
    conference: 'SEC',
    classYear: 'Senior',
    eligibility: 'RS-Senior',
    height: "6'5\"",
    weight: 270,
    paiScore: 79,
    tier: 'FIRST_ROUND',
    performance: 81,
    athleticism: 80,
    intangibles: 77,
    overallRank: 26,
    positionRank: 8,
    trend: 'UP',
    scoutMemo: "NFL-ready size with desirable length and strength. Career-high 6.5 sacks. Disruptive at the Senior Bowl. Well put-together pass rusher. Lacks above-average athleticism and burst but compensates with technique and power.",
    tags: JSON.stringify(['nfl-size', 'senior-bowl-standout', 'technique', 'power']),
    comparisons: JSON.stringify(['Cameron Jordan power']),
    combineInvite: true,
    seniorBowl: true,
    projectedRound: 1,
    projectedPick: 31,
    enrichedBy: 'manual',
  },
  {
    firstName: 'Avieon',
    lastName: 'Terrell',
    position: 'CB',
    college: 'Clemson',
    conference: 'ACC',
    classYear: 'Junior',
    eligibility: 'Junior (declared)',
    height: "6'1\"",
    weight: 195,
    paiScore: 83,
    tier: 'FIRST_ROUND',
    performance: 84,
    athleticism: 86,
    intangibles: 80,
    overallRank: 18,
    positionRank: 3,
    trend: 'STEADY',
    scoutMemo: "Younger brother of Falcons CB A.J. Terrell. Natural movement skills, incredibly competitive at the catch point. 25 career pass breakups, 11 forced turnovers. Some scouts see nickel corner but we believe he can play outside.",
    tags: JSON.stringify(['pedigree', 'ball-skills', 'competitive', 'turnovers']),
    comparisons: JSON.stringify(['A.J. Terrell bloodline', 'Devon Witherspoon competitiveness']),
    combineInvite: true,
    projectedRound: 1,
    projectedPick: 32,
    enrichedBy: 'manual',
  },
  {
    firstName: 'Colton',
    lastName: 'Hood',
    position: 'CB',
    college: 'Tennessee',
    conference: 'SEC',
    classYear: 'Junior',
    eligibility: 'Junior (declared)',
    height: "6'0\"",
    weight: 190,
    paiScore: 81,
    tier: 'FIRST_ROUND',
    performance: 82,
    athleticism: 83,
    intangibles: 78,
    overallRank: 27,
    positionRank: 4,
    trend: 'STEADY',
    scoutMemo: "Approaches every press-man rep with a physical mindset. Confidence throughout frame. Sticky cover-man with 9 passes defensed in 2025. Instincts are a work in progress but the physicality and technique are there.",
    tags: JSON.stringify(['press-man', 'physical', 'sticky', 'sec-cb']),
    comparisons: JSON.stringify(["Tre'Davious White physicality"]),
    combineInvite: true,
    projectedRound: 1,
    projectedPick: 29,
    enrichedBy: 'manual',
  },
];

// ─────────────────────────────────────────────────────────────
// 2025 NFL Draft REDRAFT — Rookie Season Re-Evaluation
// These players are NOW IN THE NFL. Graded by rookie performance.
// ─────────────────────────────────────────────────────────────

export interface RedraftProspect extends SeedDraftProspect {
  nflTeam: string;
  draftPick: string;
  rookieStats?: string;
  rookieGrade: number;
  rookieAssessment?: string;
  injuryNote?: string;
}

export const REDRAFT_2025_PROSPECTS: RedraftProspect[] = [
  {
    firstName: 'Cam',
    lastName: 'Ward',
    position: 'QB',
    college: 'Miami (FL)',
    conference: 'ACC',
    classYear: 'Senior',
    height: "6'2\"",
    weight: 223,
    paiScore: 96,
    tier: 'TOP_5',
    performance: 92,
    athleticism: 92,
    intangibles: 90,
    overallRank: 1,
    positionRank: 1,
    trend: 'STEADY',
    nflTeam: 'Tennessee Titans',
    draftPick: '#1 Overall',
    rookieStats: JSON.stringify({
      'GP': 17, 'COMP': 323, 'ATT': 540, 'COMP%': '59.8%',
      'YDS': 3169, 'TD': 15, 'INT': 7, 'RUSH_YDS': 159,
      'RUSH_TD': 2, 'RTG': 80.2
    }),
    rookieGrade: 72,
    rookieAssessment: "Typical rookie QB season. 59.8% completion rate is a concern (was 74%+ in college). Started all 17 games. Best game: Week 12 (91.0 RTG, 256 YDS, 1 TD, 0 INT). Trajectory is upward.",
    enrichedBy: 'verified',
  },
  {
    firstName: 'Travis',
    lastName: 'Hunter',
    position: 'CB/WR',
    college: 'Colorado',
    conference: 'Big 12',
    classYear: 'Junior',
    height: "6'0\"",
    weight: 188,
    paiScore: 101,
    tier: 'TOP_5',
    performance: 97,
    athleticism: 96,
    intangibles: 97,
    overallRank: 2,
    positionRank: 1,
    trend: 'DOWN',
    nflTeam: 'Jacksonville Jaguars',
    draftPick: '#2 Overall',
    rookieStats: JSON.stringify({
      'GP': 7, 'REC': 28, 'REC_YDS': 298, 'REC_TD': 1,
      'TARGETS': 45, 'OFF_SNAP%': '67%', 'DEF_SNAP%': '36%'
    }),
    rookieGrade: 68,
    rookieAssessment: "Season ended Week 9 — torn LCL (non-contact, practice). In 7 games: 28 REC, 298 YDS, 1 TD. Breakout Week 7: 8 REC, 101 YDS, 1 TD + PBU on defense. Jaguars plan for 2026: CB1 + part-time WR. Full health expected.",
    injuryNote: "Torn LCL — non-contact, Week 9 practice. Season-ending surgery Nov 11, 2025.",
    enrichedBy: 'verified',
  },
  {
    firstName: 'Shedeur',
    lastName: 'Sanders',
    position: 'QB',
    college: 'Colorado',
    conference: 'Big 12',
    classYear: 'Senior',
    height: "6'2\"",
    weight: 215,
    paiScore: 91,
    tier: 'TOP_5',
    performance: 93,
    athleticism: 88,
    intangibles: 96,
    overallRank: 3,
    positionRank: 2,
    trend: 'DOWN',
    nflTeam: 'Cleveland Browns',
    draftPick: '#144 Overall (Round 5)',
    rookieStats: JSON.stringify({ 'NOTE': 'Draft slide from consensus 1st round to 5th round (#144)' }),
    rookieGrade: 0,
    rookieAssessment: "Pre-draft AGI flagged Known Concerns at 3.2/10 — highest of any top QB. The draft-day fall to Round 5 was driven by off-field perception, scheme fit questions, and Deion factor. Per|Form's AGI system caught the warning signs that consensus boards missed.",
    enrichedBy: 'verified',
  },
];

// ─────────────────────────────────────────────────────────────
// NFL Team Needs — 2026 Draft Order
// Based on 2025 NFL season final standings.
// Source: The Athletic beat writer mock draft (Feb 19, 2026)
// Draft: April 23-25, 2026 — Pittsburgh, PA
// ─────────────────────────────────────────────────────────────

export interface TeamNeed {
  team: string;
  abbrev: string;
  projectedPick: number;
  primaryNeeds: string[];
  secondaryNeeds: string[];
  tradeLikelihood: 'LOW' | 'MEDIUM' | 'HIGH';
}

export const NFL_TEAM_NEEDS_2026: TeamNeed[] = [
  { team: 'Las Vegas Raiders', abbrev: 'LV', projectedPick: 1, primaryNeeds: ['QB', 'EDGE', 'WR'], secondaryNeeds: ['OT', 'CB'], tradeLikelihood: 'MEDIUM' },
  { team: 'New York Jets', abbrev: 'NYJ', projectedPick: 2, primaryNeeds: ['QB', 'EDGE', 'LB'], secondaryNeeds: ['WR', 'CB'], tradeLikelihood: 'MEDIUM' },
  { team: 'Arizona Cardinals', abbrev: 'ARI', projectedPick: 3, primaryNeeds: ['OT', 'QB', 'EDGE'], secondaryNeeds: ['WR', 'CB'], tradeLikelihood: 'MEDIUM' },
  { team: 'Tennessee Titans', abbrev: 'TEN', projectedPick: 4, primaryNeeds: ['EDGE', 'OT', 'WR'], secondaryNeeds: ['LB', 'DT'], tradeLikelihood: 'MEDIUM' },
  { team: 'New York Giants', abbrev: 'NYG', projectedPick: 5, primaryNeeds: ['S', 'OT', 'EDGE'], secondaryNeeds: ['WR', 'LB'], tradeLikelihood: 'MEDIUM' },
  { team: 'Cleveland Browns', abbrev: 'CLE', projectedPick: 6, primaryNeeds: ['OT', 'QB', 'WR'], secondaryNeeds: ['EDGE', 'CB'], tradeLikelihood: 'LOW' },
  { team: 'Washington Commanders', abbrev: 'WAS', projectedPick: 7, primaryNeeds: ['EDGE', 'CB', 'LB'], secondaryNeeds: ['WR', 'DT'], tradeLikelihood: 'LOW' },
  { team: 'New Orleans Saints', abbrev: 'NO', projectedPick: 8, primaryNeeds: ['RB', 'WR', 'EDGE'], secondaryNeeds: ['OT', 'CB'], tradeLikelihood: 'LOW' },
  { team: 'Kansas City Chiefs', abbrev: 'KC', projectedPick: 9, primaryNeeds: ['WR', 'EDGE', 'CB'], secondaryNeeds: ['OT', 'LB'], tradeLikelihood: 'LOW' },
  { team: 'Cincinnati Bengals', abbrev: 'CIN', projectedPick: 10, primaryNeeds: ['LB', 'CB', 'EDGE'], secondaryNeeds: ['DT', 'S'], tradeLikelihood: 'LOW' },
  { team: 'Miami Dolphins', abbrev: 'MIA', projectedPick: 11, primaryNeeds: ['CB', 'EDGE', 'OT'], secondaryNeeds: ['WR', 'S'], tradeLikelihood: 'LOW' },
  { team: 'Dallas Cowboys', abbrev: 'DAL', projectedPick: 12, primaryNeeds: ['CB', 'LB', 'EDGE'], secondaryNeeds: ['S', 'WR'], tradeLikelihood: 'MEDIUM' },
  { team: 'Los Angeles Rams', abbrev: 'LAR', projectedPick: 13, primaryNeeds: ['CB', 'WR', 'EDGE'], secondaryNeeds: ['OT', 'LB'], tradeLikelihood: 'LOW' },
  { team: 'Baltimore Ravens', abbrev: 'BAL', projectedPick: 14, primaryNeeds: ['IOL', 'EDGE', 'WR'], secondaryNeeds: ['CB', 'S'], tradeLikelihood: 'LOW' },
  { team: 'Tampa Bay Buccaneers', abbrev: 'TB', projectedPick: 15, primaryNeeds: ['EDGE', 'CB', 'LB'], secondaryNeeds: ['WR', 'OT'], tradeLikelihood: 'MEDIUM' },
  { team: 'Indianapolis Colts', abbrev: 'IND', projectedPick: 16, primaryNeeds: ['LB', 'WR', 'CB'], secondaryNeeds: ['EDGE', 'S'], tradeLikelihood: 'MEDIUM' },
  { team: 'Detroit Lions', abbrev: 'DET', projectedPick: 17, primaryNeeds: ['OT', 'EDGE', 'CB'], secondaryNeeds: ['DT', 'LB'], tradeLikelihood: 'MEDIUM' },
  { team: 'Minnesota Vikings', abbrev: 'MIN', projectedPick: 18, primaryNeeds: ['DT', 'EDGE', 'CB'], secondaryNeeds: ['WR', 'LB'], tradeLikelihood: 'LOW' },
  { team: 'Carolina Panthers', abbrev: 'CAR', projectedPick: 19, primaryNeeds: ['EDGE', 'OT', 'WR'], secondaryNeeds: ['LB', 'CB'], tradeLikelihood: 'LOW' },
  { team: 'Green Bay Packers', abbrev: 'GB', projectedPick: 20, primaryNeeds: ['DT', 'EDGE', 'CB'], secondaryNeeds: ['WR', 'LB'], tradeLikelihood: 'MEDIUM' },
  { team: 'Pittsburgh Steelers', abbrev: 'PIT', projectedPick: 21, primaryNeeds: ['WR', 'QB', 'EDGE'], secondaryNeeds: ['OT', 'CB'], tradeLikelihood: 'HIGH' },
  { team: 'Los Angeles Chargers', abbrev: 'LAC', projectedPick: 22, primaryNeeds: ['EDGE', 'WR', 'CB'], secondaryNeeds: ['OT', 'LB'], tradeLikelihood: 'LOW' },
  { team: 'Philadelphia Eagles', abbrev: 'PHI', projectedPick: 23, primaryNeeds: ['TE', 'CB', 'EDGE'], secondaryNeeds: ['WR', 'OT'], tradeLikelihood: 'MEDIUM' },
  { team: 'Jacksonville Jaguars', abbrev: 'JAX', projectedPick: 24, primaryNeeds: ['CB', 'OT', 'EDGE'], secondaryNeeds: ['WR', 'LB'], tradeLikelihood: 'LOW' },
  { team: 'Chicago Bears', abbrev: 'CHI', projectedPick: 25, primaryNeeds: ['OT', 'DT', 'EDGE'], secondaryNeeds: ['CB', 'LB'], tradeLikelihood: 'LOW' },
  { team: 'Buffalo Bills', abbrev: 'BUF', projectedPick: 26, primaryNeeds: ['EDGE', 'WR', 'CB'], secondaryNeeds: ['LB', 'S'], tradeLikelihood: 'LOW' },
  { team: 'San Francisco 49ers', abbrev: 'SF', projectedPick: 27, primaryNeeds: ['EDGE', 'CB', 'OT'], secondaryNeeds: ['WR', 'LB'], tradeLikelihood: 'LOW' },
  { team: 'Houston Texans', abbrev: 'HOU', projectedPick: 28, primaryNeeds: ['OT', 'CB', 'EDGE'], secondaryNeeds: ['WR', 'S'], tradeLikelihood: 'LOW' },
  { team: 'Los Angeles Rams', abbrev: 'LAR', projectedPick: 29, primaryNeeds: ['CB', 'EDGE', 'LB'], secondaryNeeds: ['DT', 'S'], tradeLikelihood: 'LOW' },
  { team: 'Denver Broncos', abbrev: 'DEN', projectedPick: 30, primaryNeeds: ['WR', 'EDGE', 'CB'], secondaryNeeds: ['OT', 'LB'], tradeLikelihood: 'LOW' },
  { team: 'New England Patriots', abbrev: 'NE', projectedPick: 31, primaryNeeds: ['EDGE', 'WR', 'OT'], secondaryNeeds: ['LB', 'S'], tradeLikelihood: 'LOW' },
  { team: 'Seattle Seahawks', abbrev: 'SEA', projectedPick: 32, primaryNeeds: ['CB', 'EDGE', 'OT'], secondaryNeeds: ['WR', 'S'], tradeLikelihood: 'LOW' },
];
