// frontend/components/luc/LucEstimatePanel.tsx
import React from "react";
import { LucEstimate } from "@/lib/luc/luc.stub";

interface Props {
  estimate: LucEstimate;
}

export function LucEstimatePanel({ estimate }: Props) {
  return (
    <div className="space-y-6">
      <div className="flex items-end justify-between border-b border-wireframe-stroke pb-4">
        <div>
          <p className="text-[10px] uppercase tracking-widest text-white/30 font-display">Estimated Workflow Cost</p>
          <h2 className="text-3xl font-bold text-white font-display">${estimate.totalUsd.toFixed(2)}</h2>
        </div>
        <div className="text-right">
          <p className="text-[10px] uppercase tracking-widest text-white/30 font-display">Total Tokens</p>
          <p className="text-sm font-mono text-gold">{(estimate.totalTokens / 1000).toFixed(0)}k</p>
        </div>
      </div>

      <div className="space-y-3">
        {estimate.breakdown.map((item) => (
          <div key={item.label} className="flex items-center justify-between rounded-xl bg-white/5 p-3 text-sm">
            <span className="text-white/70">{item.label}</span>
            <div className="flex gap-4 font-mono text-xs">
              <span className="text-white/30">{(item.tokens / 1000).toFixed(0)}k tkn</span>
              <span className="text-white font-semibold">${item.usd.toFixed(2)}</span>
            </div>
          </div>
        ))}
      </div>

      <div className="rounded-2xl border border-gold/10 bg-gold/5 p-4">
        <h4 className="text-[10px] font-bold uppercase tracking-widest text-gold mb-3">Orchestrator Selection</h4>
        <div className="grid gap-2">
          {estimate.modelOptions.map((opt) => (
            <button key={opt.name} className="flex flex-col rounded-xl border border-wireframe-stroke bg-black/40 p-3 text-left transition-all hover:border-gold/30 group">
              <div className="flex justify-between items-center">
                <span className="text-xs font-semibold text-white group-hover:text-gold">{opt.name}</span>
                <span className="text-[10px] text-white/30">x{opt.costMultiplier} cost</span>
              </div>
              <p className="text-[10px] text-white/40 mt-1">{opt.description}</p>
            </button>
          ))}
        </div>
      </div>

      <p className="text-[9px] text-white/20 italic text-center">
        * Estimates generated by LUC usage calculator. Actual costs may vary based on response length and branching.
      </p>
    </div>
  );
}
