/**
 * LUC Constants - Stable Service Keys and Configuration
 * @version 2.0.0
 *
 * PRONUNCIATION: "LUKE" (not L-U-C)
 *
 * This file defines all stable service keys, unit semantics, and default
 * configuration values. These are the foundation for metering and billing.
 */

// ─────────────────────────────────────────────────────────────────────────────
// Service Key Registry (Stable, Never Change Once Published)
// ─────────────────────────────────────────────────────────────────────────────

export const SERVICE_KEYS = {
  // LLM Token Metering
  LLM_TOKENS_IN: "llm_tokens_in",
  LLM_TOKENS_OUT: "llm_tokens_out",

  // Workflow Execution
  N8N_EXECUTIONS: "n8n_executions",
  NODE_RUNTIME_SECONDS: "node_runtime_seconds",
  SWARM_CYCLES: "swarm_cycles",

  // External APIs
  BRAVE_QUERIES: "brave_queries",

  // Voice/Audio
  VOICE_CHARS: "voice_chars",
  STT_MINUTES: "stt_minutes",

  // Infrastructure
  CONTAINER_HOURS: "container_hours",
  STORAGE_GB_MONTH: "storage_gb_month",
  BANDWIDTH_GB: "bandwidth_gb",

  // Agent Operations
  BOOMER_ANG_INVOCATIONS: "boomer_ang_invocations",
  AGENT_EXECUTIONS: "agent_executions",

  // Deployments
  DEPLOY_OPERATIONS: "deploy_operations",

  // Custom/Generic
  API_CALLS: "api_calls",
} as const;

export type ServiceKey = (typeof SERVICE_KEYS)[keyof typeof SERVICE_KEYS];

// ─────────────────────────────────────────────────────────────────────────────
// Service Metadata
// ─────────────────────────────────────────────────────────────────────────────

export interface ServiceDefinition {
  key: ServiceKey;
  name: string;
  description: string;
  unit: string;
  unitPlural: string;
  category: ServiceCategory;
  defaultRate: number; // Default cost per unit in credits
  meterType: "count" | "duration" | "volume";
}

export type ServiceCategory =
  | "llm"
  | "workflow"
  | "voice"
  | "infrastructure"
  | "agent"
  | "deployment"
  | "api";

export const SERVICE_CATALOG: Record<ServiceKey, ServiceDefinition> = {
  [SERVICE_KEYS.LLM_TOKENS_IN]: {
    key: SERVICE_KEYS.LLM_TOKENS_IN,
    name: "LLM Input Tokens",
    description: "Tokens sent to language models",
    unit: "token",
    unitPlural: "tokens",
    category: "llm",
    defaultRate: 0.001,
    meterType: "count",
  },
  [SERVICE_KEYS.LLM_TOKENS_OUT]: {
    key: SERVICE_KEYS.LLM_TOKENS_OUT,
    name: "LLM Output Tokens",
    description: "Tokens generated by language models",
    unit: "token",
    unitPlural: "tokens",
    category: "llm",
    defaultRate: 0.003,
    meterType: "count",
  },
  [SERVICE_KEYS.N8N_EXECUTIONS]: {
    key: SERVICE_KEYS.N8N_EXECUTIONS,
    name: "n8n Workflow Executions",
    description: "Workflow runs on n8n automation platform",
    unit: "execution",
    unitPlural: "executions",
    category: "workflow",
    defaultRate: 0.01,
    meterType: "count",
  },
  [SERVICE_KEYS.NODE_RUNTIME_SECONDS]: {
    key: SERVICE_KEYS.NODE_RUNTIME_SECONDS,
    name: "Node Runtime",
    description: "Compute time for workflow nodes",
    unit: "second",
    unitPlural: "seconds",
    category: "workflow",
    defaultRate: 0.0001,
    meterType: "duration",
  },
  [SERVICE_KEYS.SWARM_CYCLES]: {
    key: SERVICE_KEYS.SWARM_CYCLES,
    name: "Swarm Cycles",
    description: "Agent swarm coordination cycles",
    unit: "cycle",
    unitPlural: "cycles",
    category: "agent",
    defaultRate: 0.05,
    meterType: "count",
  },
  [SERVICE_KEYS.BRAVE_QUERIES]: {
    key: SERVICE_KEYS.BRAVE_QUERIES,
    name: "Brave Search Queries",
    description: "Web search queries via Brave API",
    unit: "query",
    unitPlural: "queries",
    category: "api",
    defaultRate: 0.005,
    meterType: "count",
  },
  [SERVICE_KEYS.VOICE_CHARS]: {
    key: SERVICE_KEYS.VOICE_CHARS,
    name: "Voice Characters",
    description: "Characters synthesized to speech",
    unit: "character",
    unitPlural: "characters",
    category: "voice",
    defaultRate: 0.00001,
    meterType: "count",
  },
  [SERVICE_KEYS.STT_MINUTES]: {
    key: SERVICE_KEYS.STT_MINUTES,
    name: "Speech-to-Text Minutes",
    description: "Audio transcription duration",
    unit: "minute",
    unitPlural: "minutes",
    category: "voice",
    defaultRate: 0.006,
    meterType: "duration",
  },
  [SERVICE_KEYS.CONTAINER_HOURS]: {
    key: SERVICE_KEYS.CONTAINER_HOURS,
    name: "Container Hours",
    description: "Container runtime hours",
    unit: "hour",
    unitPlural: "hours",
    category: "infrastructure",
    defaultRate: 0.05,
    meterType: "duration",
  },
  [SERVICE_KEYS.STORAGE_GB_MONTH]: {
    key: SERVICE_KEYS.STORAGE_GB_MONTH,
    name: "Storage (GB/month)",
    description: "Cloud storage allocation",
    unit: "GB-month",
    unitPlural: "GB-months",
    category: "infrastructure",
    defaultRate: 0.02,
    meterType: "volume",
  },
  [SERVICE_KEYS.BANDWIDTH_GB]: {
    key: SERVICE_KEYS.BANDWIDTH_GB,
    name: "Bandwidth (GB)",
    description: "Data transfer volume",
    unit: "GB",
    unitPlural: "GB",
    category: "infrastructure",
    defaultRate: 0.08,
    meterType: "volume",
  },
  [SERVICE_KEYS.BOOMER_ANG_INVOCATIONS]: {
    key: SERVICE_KEYS.BOOMER_ANG_INVOCATIONS,
    name: "Boomer_Ang Invocations",
    description: "Agent supervisor invocations",
    unit: "invocation",
    unitPlural: "invocations",
    category: "agent",
    defaultRate: 0.02,
    meterType: "count",
  },
  [SERVICE_KEYS.AGENT_EXECUTIONS]: {
    key: SERVICE_KEYS.AGENT_EXECUTIONS,
    name: "Agent Executions",
    description: "Individual agent task executions",
    unit: "execution",
    unitPlural: "executions",
    category: "agent",
    defaultRate: 0.01,
    meterType: "count",
  },
  [SERVICE_KEYS.DEPLOY_OPERATIONS]: {
    key: SERVICE_KEYS.DEPLOY_OPERATIONS,
    name: "Deploy Operations",
    description: "Deployment pipeline operations",
    unit: "operation",
    unitPlural: "operations",
    category: "deployment",
    defaultRate: 0.1,
    meterType: "count",
  },
  [SERVICE_KEYS.API_CALLS]: {
    key: SERVICE_KEYS.API_CALLS,
    name: "API Calls",
    description: "Generic API call metering",
    unit: "call",
    unitPlural: "calls",
    category: "api",
    defaultRate: 0.001,
    meterType: "count",
  },
};

// ─────────────────────────────────────────────────────────────────────────────
// Default Configuration
// ─────────────────────────────────────────────────────────────────────────────

export const LUC_DEFAULTS = {
  // Warning thresholds (percentage of quota)
  SOFT_WARN_THRESHOLD: 0.8, // 80% - show warning
  HARD_WARN_THRESHOLD: 0.95, // 95% - show critical warning
  OVERAGE_BUFFER: 0.1, // 10% - allow this much overage before blocking

  // Billing cycle
  BILLING_CYCLE_DAYS: 30,

  // Rate limiting
  MAX_EVENTS_PER_SECOND: 100,
  MAX_BATCH_SIZE: 1000,

  // Retention
  USAGE_EVENT_RETENTION_DAYS: 90,
  AUDIT_LOG_RETENTION_DAYS: 365,

  // Aggregation
  AGGREGATION_INTERVAL_MINUTES: 5,
} as const;

// ─────────────────────────────────────────────────────────────────────────────
// Plan Definitions (Policy-Driven, Not Hardcoded in Services)
// ─────────────────────────────────────────────────────────────────────────────

export const PLAN_IDS = {
  P2P: "p2p",
  COFFEE: "coffee",
  DATA_ENTRY: "data_entry",
  PRO: "pro",
  ENTERPRISE: "enterprise",
} as const;

export type PlanId = (typeof PLAN_IDS)[keyof typeof PLAN_IDS];

/**
 * Plan quota multipliers (relative to base limits).
 * No tier uses -1. Enterprise gets the highest multiplier (1000x base).
 * Actual limits are stored in policy storage, not here.
 */
export const PLAN_MULTIPLIERS: Record<PlanId, number> = {
  [PLAN_IDS.P2P]: 1,
  [PLAN_IDS.COFFEE]: 5,
  [PLAN_IDS.DATA_ENTRY]: 25,
  [PLAN_IDS.PRO]: 100,
  [PLAN_IDS.ENTERPRISE]: 1000,
};

// ─────────────────────────────────────────────────────────────────────────────
// Overage Policies
// ─────────────────────────────────────────────────────────────────────────────

export const OVERAGE_POLICIES = {
  BLOCK: "block", // Hard stop at quota
  ALLOW_OVERAGE: "allow_overage", // Allow with overage charges
  SOFT_LIMIT: "soft_limit", // Warn but allow (for enterprise)
} as const;

export type OveragePolicy = (typeof OVERAGE_POLICIES)[keyof typeof OVERAGE_POLICIES];

// ─────────────────────────────────────────────────────────────────────────────
// Tool Categories (for UI grouping)
// ─────────────────────────────────────────────────────────────────────────────

export const TOOL_CATEGORIES = {
  AI: "ai",
  AUTOMATION: "automation",
  VOICE: "voice",
  INFRASTRUCTURE: "infrastructure",
  AGENTS: "agents",
  DEPLOYMENT: "deployment",
} as const;

export type ToolCategory = (typeof TOOL_CATEGORIES)[keyof typeof TOOL_CATEGORIES];

// Map service keys to tool categories
export const SERVICE_TO_CATEGORY: Record<ServiceKey, ToolCategory> = {
  [SERVICE_KEYS.LLM_TOKENS_IN]: TOOL_CATEGORIES.AI,
  [SERVICE_KEYS.LLM_TOKENS_OUT]: TOOL_CATEGORIES.AI,
  [SERVICE_KEYS.N8N_EXECUTIONS]: TOOL_CATEGORIES.AUTOMATION,
  [SERVICE_KEYS.NODE_RUNTIME_SECONDS]: TOOL_CATEGORIES.AUTOMATION,
  [SERVICE_KEYS.SWARM_CYCLES]: TOOL_CATEGORIES.AGENTS,
  [SERVICE_KEYS.BRAVE_QUERIES]: TOOL_CATEGORIES.AI,
  [SERVICE_KEYS.VOICE_CHARS]: TOOL_CATEGORIES.VOICE,
  [SERVICE_KEYS.STT_MINUTES]: TOOL_CATEGORIES.VOICE,
  [SERVICE_KEYS.CONTAINER_HOURS]: TOOL_CATEGORIES.INFRASTRUCTURE,
  [SERVICE_KEYS.STORAGE_GB_MONTH]: TOOL_CATEGORIES.INFRASTRUCTURE,
  [SERVICE_KEYS.BANDWIDTH_GB]: TOOL_CATEGORIES.INFRASTRUCTURE,
  [SERVICE_KEYS.BOOMER_ANG_INVOCATIONS]: TOOL_CATEGORIES.AGENTS,
  [SERVICE_KEYS.AGENT_EXECUTIONS]: TOOL_CATEGORIES.AGENTS,
  [SERVICE_KEYS.DEPLOY_OPERATIONS]: TOOL_CATEGORIES.DEPLOYMENT,
  [SERVICE_KEYS.API_CALLS]: TOOL_CATEGORIES.AUTOMATION,
};
