/**
 * Initial seed rows for the Tool Warehouse.
 *
 * Covers the structurally-important tools per 2026-04-17 arbitration:
 *  - 4 Orchestration tier (ACHEEVY, NTNTN, Chronicle, Researcher)
 *  - 4 Integration tier (Suna AI, RTRVR AI, Manus AI [INTERNAL], Rytr AI)
 *  - 3 Plug Factory (Buildsmith, Picker_Ang, House of ANG)
 *  - 17 House of ANG specialists mapped to SmelterOS Foundry tier
 *
 * The remaining 293 External Integrations land in a data-only follow-up
 * PR to keep this review tractable.
 */

import type { ToolSeed } from './schema.js';

export const SEED_TOOLS: ToolSeed[] = [
  // ── Tier 1: Orchestration ─────────────────────────────────────────

  {
    id: 'acheevy',
    name: 'ACHEEVY',
    tier: 'orchestration',
    category: 'Digital CEO / user-facing voice',
    description: 'Primary orchestrator for RFP→BAMARAM workflow. Delegates via acheevy_delegate MCP tool. Collaborates with Picker_Ang at Step 3 and Buildsmith at Step 7.',
    license: 'proprietary',
    vendor: 'ACHIEVEMOR',
    priority: 'critical',
    circuitBreakerId: 'CB_ACHEEVY',
    healthEndpoint: 'http://localhost:8000/health',
    ownerAng: 'self',
    capabilities: ['orchestration', 'charter_writing', 'hitl_gate', 'delegation'],
  },
  {
    id: 'ntntn',
    name: 'NTNTN',
    tier: 'orchestration',
    category: 'Conscience / HITL gates',
    description: 'Quality assurance, HITL gates, V.I.B.E. 99.5% virtue-alignment validation. Ethical override authority at threshold 0.995.',
    license: 'proprietary',
    vendor: 'ACHIEVEMOR',
    priority: 'critical',
    circuitBreakerId: 'CB_NTNTN',
    healthEndpoint: 'http://localhost:8002/health',
    capabilities: ['hitl_gate', 'virtue_alignment', 'ethical_override'],
  },
  {
    id: 'chronicle',
    name: 'Chronicle Logger',
    tier: 'orchestration',
    category: 'Dual-artifact logging',
    description: 'Writes to Charter (customer-safe) and Ledger (internal) in parallel. Maintains Rationale Ledger + Story Baton refs.',
    license: 'proprietary',
    vendor: 'ACHIEVEMOR',
    priority: 'critical',
    circuitBreakerId: 'CB_CHRONICLE',
    healthEndpoint: 'http://localhost:8003/health',
    ownerAng: 'Chronicle_Ang',
    capabilities: ['logging', 'dual_surface', 'audit_trail'],
  },
  {
    id: 'researcher',
    name: 'Researcher Agent',
    tier: 'orchestration',
    category: 'Research + data gathering',
    description: 'Research and data gathering for RFP → BAMARAM workflow. Feeds TTD-DR diffusion loop.',
    license: 'proprietary',
    vendor: 'ACHIEVEMOR',
    priority: 'high',
    circuitBreakerId: 'CB_RESEARCHER',
    healthEndpoint: 'http://localhost:8004/health',
    ownerAng: 'Research_Ang',
    capabilities: ['research', 'data_gathering'],
  },

  // ── Tier 2: Integration (2026-04-17 arbitration additions) ────────

  {
    id: 'suna_ai',
    name: 'Suna AI',
    tier: 'integration',
    category: 'Autonomous Agent Framework',
    description: 'Browser automation (Playwright), file management, web crawling, code execution, multi-tool orchestration. Self-hosted or cloud.',
    license: 'apache_2_0',
    repoUrl: 'https://github.com/kortix-ai/suna',
    vendor: 'Kortix',
    priority: 'high',
    status: 'active',
    circuitBreakerId: 'CB_SUNA_AI',
    capabilities: ['browser_automation', 'web_scraping', 'multi_tool', 'code_execution'],
    costModel: { type: 'open_source_or_cloud', selfHosted: 'free' },
    addedToWarehouse: '2026-04-17',
  },
  {
    id: 'rtrvr_ai',
    name: 'RTRVR AI',
    tier: 'integration',
    category: 'Local Browser Agent',
    description: 'FREE local browser execution via Gemini API. Multi-tab parallel workflows, bot-detection bypass, #1 on Halluminate Web Bench.',
    license: 'freemium',
    vendor: 'RTRVR',
    priority: 'medium',
    status: 'active',
    circuitBreakerId: 'CB_RTRVR_AI',
    capabilities: ['browser_automation', 'form_automation', 'local_execution'],
    costModel: { type: 'free', note: 'Gemini API free tier' },
    addedToWarehouse: '2026-04-17',
  },
  {
    id: 'manus_ai',
    name: 'Manus AI',
    tier: 'integration',
    category: 'Autonomous General Intelligence (INTERNAL ONLY)',
    description: 'Dynamic goal decomposition, multi-tool coordination across 500+ tools, multimodal processing. Used internally by ACHEEVY/Buildsmith for specialized workflows.',
    internalOnly: true,
    customerSafeLabel: 'External Tool Coordination',
    license: 'commercial',
    vendor: 'Manus AI',
    priority: 'critical',
    status: 'active',
    circuitBreakerId: 'CB_MANUS_AI',
    capabilities: ['goal_decomposition', 'multi_tool', 'multimodal', 'video_analysis'],
    costModel: { type: 'usage', goalDecomposition: '$0.02-0.10', workflow: '$0.50-5.00' },
    addedToWarehouse: '2026-04-17',
    metadata: {
      enforcementNote:
        'NEVER surface in Charter/UI/marketing/ACHEEVY replies/customer BoM. ' +
        'Use customer_safe_label or swap to Suna AI equivalent for customer copy.',
    },
  },
  {
    id: 'rytr_ai',
    name: 'Rytr AI',
    tier: 'integration',
    category: 'Content Generation (Fallback)',
    description: '40+ content use cases, 30+ languages, 20+ tones. Fallback content generator when Claude/GPT unavailable.',
    license: 'freemium',
    vendor: 'Rytr',
    priority: 'low',
    status: 'active',
    circuitBreakerId: 'CB_RYTR_AI',
    capabilities: ['content_generation', 'multilingual', 'serp_analysis'],
    costModel: { type: 'freemium', free: '10k chars/mo', paid: '$9/mo unlimited' },
    addedToWarehouse: '2026-04-17',
  },

  // ── Tier 3: Plug Factory ──────────────────────────────────────────

  {
    id: 'buildsmith',
    name: 'Buildsmith',
    tier: 'plug_factory',
    category: 'Build execution',
    description: 'Receives Bill of Materials from Picker_Ang, executes plug construction, emits SBOM + scan evidence for Farmer QA.',
    license: 'proprietary',
    vendor: 'ACHIEVEMOR',
    priority: 'critical',
    circuitBreakerId: 'CB_BUILDSMITH',
    healthEndpoint: 'http://localhost:8006/health',
    capabilities: ['plug_construction', 'sbom_emission', 'build_pipeline'],
  },
  {
    id: 'picker_ang',
    name: 'Picker_Ang',
    tier: 'plug_factory',
    category: 'Tool selection (Step 3 Commercial Proposal)',
    description: 'Scans the 325-tool warehouse at RFP→BAMARAM Step 3. Emits Bill of Materials JSON + Security Addendum. IIR scoring (Impact / Integration-fit / Risk). Delivered by PR 4.',
    license: 'proprietary',
    vendor: 'ACHIEVEMOR',
    priority: 'critical',
    status: 'experimental',                               // not shipped until PR 4
    circuitBreakerId: 'CB_PICKER_ANG',
    healthEndpoint: 'http://localhost:8005/health',
    capabilities: ['tool_routing', 'bom_emission', 'iir_scoring'],
  },
  {
    id: 'house_of_ang',
    name: 'House of ANG',
    tier: 'plug_factory',
    category: 'Aggregator for 17 Boomer_Ang specialists',
    description: 'The official home of all Boomer_Angs. Dispatches specialist work to 17 tier-organized agents. See docs/canon/boomer_angs_unified_roster.md.',
    license: 'proprietary',
    vendor: 'ACHIEVEMOR',
    priority: 'critical',
    circuitBreakerId: 'CB_HOUSE_OF_ANG',
    healthEndpoint: 'http://localhost:8007/health',
    capabilities: ['specialist_dispatch', 'aggregation'],
  },

  // ── Tier 6: SmelterOS Foundry — House of ANG 17 specialists ───────

  {
    id: 'research_ang',
    name: 'Research_Ang',
    tier: 'smelter_os_foundry',
    category: 'Tier 1 Core Infrastructure',
    description: 'Search and research framework specialist. Deep web search, academic/docs research, competitive intelligence, multi-source synthesis.',
    license: 'mit',
    repoUrl: 'https://github.com/IntelligentInternet/ii-researcher',
    vendor: 'IntelligentInternet',
    stars: 471,
    priority: 'high',
    ownerAng: 'Research_Ang',
    capabilities: ['research', 'search', 'synthesis'],
  },
  {
    id: 'code_ang',
    name: 'Code_Ang',
    tier: 'smelter_os_foundry',
    category: 'Tier 1 Core Infrastructure',
    description: 'Intelligent agent deployment and full-stack code generation. AI agent architecture, API design, IaC implementation.',
    license: 'mit',
    repoUrl: 'https://github.com/IntelligentInternet/ii-agent',
    vendor: 'IntelligentInternet',
    stars: 2900,
    priority: 'high',
    ownerAng: 'Code_Ang',
    capabilities: ['code_generation', 'agent_architecture', 'full_stack'],
  },
  {
    id: 'multi_ang',
    name: 'Multi_Ang',
    tier: 'smelter_os_foundry',
    category: 'Tier 1 Core Infrastructure',
    description: 'Multi-agent team coordination, shared context and memory, workflow orchestration. CommonGround collaboration fabric.',
    license: 'mit',
    repoUrl: 'https://github.com/IntelligentInternet/CommonGround',
    vendor: 'IntelligentInternet',
    stars: 390,
    priority: 'high',
    ownerAng: 'Multi_Ang',
    capabilities: ['multi_agent', 'collaboration', 'shared_memory'],
  },
  {
    id: 'chronicle_ang',
    name: 'Chronicle_Ang',
    tier: 'smelter_os_foundry',
    category: 'Tier 1 Core Infrastructure',
    description: 'Timeline processing, Rationale Ledger, evidence archiving. MCP integration.',
    license: 'mit',
    repoUrl: 'https://github.com/IntelligentInternet/Common_Chronicle',
    vendor: 'IntelligentInternet',
    stars: 23,
    priority: 'high',
    ownerAng: 'Chronicle_Ang',
    capabilities: ['timeline', 'rationale_ledger', 'evidence_anchoring'],
  },
  {
    id: 'terminal_ang',
    name: 'Terminal_Ang',
    tier: 'smelter_os_foundry',
    category: 'Tier 2 Service',
    description: 'Terminal AI operations via gemini-cli.',
    license: 'apache_2_0',
    repoUrl: 'https://github.com/google-gemini/gemini-cli',
    vendor: 'Google',
    stars: 8100,
    priority: 'medium',
    ownerAng: 'Terminal_Ang',
    capabilities: ['terminal', 'cli_automation'],
  },
  {
    id: 'gateway_ang',
    name: 'Gateway_Ang',
    tier: 'smelter_os_foundry',
    category: 'Tier 2 Service',
    description: 'Unified LLM API gateway (litellm).',
    license: 'mit',
    repoUrl: 'https://github.com/BerriAI/litellm',
    vendor: 'BerriAI',
    priority: 'medium',
    ownerAng: 'Gateway_Ang',
    capabilities: ['llm_gateway', 'provider_agnostic'],
  },
  {
    id: 'data_ang',
    name: 'Data_Ang',
    tier: 'smelter_os_foundry',
    category: 'Tier 2 Service',
    description: 'Dataset management and RAG via II-Commons.',
    license: 'mit',
    vendor: 'IntelligentInternet',
    stars: 29,
    priority: 'medium',
    ownerAng: 'Data_Ang',
    capabilities: ['dataset_management', 'rag'],
  },
  {
    id: 'present_ang',
    name: 'Present_Ang',
    tier: 'smelter_os_foundry',
    category: 'Tier 2 Service',
    description: 'HTML presentations via reveal.js.',
    license: 'mit',
    repoUrl: 'https://github.com/hakimel/reveal.js',
    vendor: 'Hakim El Hattab',
    stars: 17000,
    priority: 'medium',
    ownerAng: 'Present_Ang',
    capabilities: ['presentation', 'html_slides'],
  },
  {
    id: 'docs_ang',
    name: 'Docs_Ang',
    tier: 'smelter_os_foundry',
    category: 'Tier 2 Service',
    description: 'Documentation systems (Symbioism-Nextra).',
    license: 'mit',
    vendor: 'Symbioism',
    stars: 21,
    priority: 'medium',
    ownerAng: 'Docs_Ang',
    capabilities: ['documentation'],
  },
  {
    id: 'intel_ang',
    name: 'Intel_Ang',
    tier: 'smelter_os_foundry',
    category: 'Tier 2 Service',
    description: 'Strategic intelligence (Symbioism-TLE).',
    license: 'mit',
    vendor: 'Symbioism',
    stars: 12,
    priority: 'medium',
    ownerAng: 'Intel_Ang',
    capabilities: ['strategic_intelligence'],
  },
  {
    id: 'storage_ang',
    name: 'Storage_Ang',
    tier: 'smelter_os_foundry',
    category: 'Tier 3 Utility',
    description: 'GCP storage integration.',
    license: 'proprietary',
    vendor: 'Google',
    priority: 'medium',
    ownerAng: 'Storage_Ang',
    capabilities: ['storage', 'gcs'],
  },
  {
    id: 'learn_ang',
    name: 'Learn_Ang',
    tier: 'smelter_os_foundry',
    category: 'Tier 3 Utility',
    description: 'Multi-domain RL datasets for training-data curation.',
    license: 'mit',
    stars: 27,
    priority: 'low',
    ownerAng: 'Learn_Ang',
    capabilities: ['rl_datasets', 'training_data'],
  },
  {
    id: 'rl_ang',
    name: 'RL_Ang',
    tier: 'smelter_os_foundry',
    category: 'Tier 3 Utility',
    description: 'Volcano Engine RL optimization.',
    license: 'apache_2_0',
    vendor: 'Volcano Engine',
    stars: 7,
    priority: 'low',
    ownerAng: 'RL_Ang',
    capabilities: ['reinforcement_learning'],
  },
  {
    id: 'mcp_ang',
    name: 'MCP_Ang',
    tier: 'smelter_os_foundry',
    category: 'Tier 3 Utility',
    description: 'Codex-to-MCP conversion.',
    license: 'mit',
    priority: 'low',
    ownerAng: 'MCP_Ang',
    capabilities: ['mcp_conversion'],
  },
  {
    id: 'bridge_ang',
    name: 'Bridge_Ang',
    tier: 'smelter_os_foundry',
    category: 'Tier 3 Utility',
    description: 'API bridge ecosystem — inter-service integration.',
    license: 'mit',
    stars: 108,
    priority: 'medium',
    ownerAng: 'Bridge_Ang',
    capabilities: ['api_bridge', 'integration'],
  },
  {
    id: 'community_ang',
    name: 'Community_Ang',
    tier: 'smelter_os_foundry',
    category: 'Tier 3 Utility',
    description: 'Agent showcase gallery + community surface.',
    license: 'mit',
    stars: 16,
    priority: 'low',
    ownerAng: 'Community_Ang',
    capabilities: ['community', 'showcase'],
  },
  {
    id: 'cot_ang',
    name: 'CoT_Ang',
    tier: 'smelter_os_foundry',
    category: 'Tier 3 Utility',
    description: 'Chain-of-Thought synchronization.',
    license: 'unknown',
    priority: 'low',
    ownerAng: 'CoT_Ang',
    status: 'experimental',
    capabilities: ['chain_of_thought', 'reasoning_sync'],
  },
];
