"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
ACHIEVEMOR Shield Division — Spinner Invocation wire format (Phase A).

Contract-only schema. Locks the envelope exchanged between Python
Spinner (legacy) and the Rust shield-policy runtime (new), so a
progressive cutover is possible without a big-bang.

See README.md in this directory for:
  - protobuf-vs-Cap'n-Proto decision record
  - schema-versioning policy
  - regeneration instructions for Rust (prost) and Python (grpcio-tools)

Source of truth for field shapes:
  - chicken-hawk/shield-policy/src/types.rs  (Rust — canonical)
  - runtime/spinner/shield_policy_client.py  (Python — mirror)

Changes to this file MUST be reviewed against both, and bump the
package version (deploy.spinner.shield.v1 → v2) for any
backwards-incompatible shape change. Additive changes (new optional
fields, new enum values appended) stay on v1.
"""

from collections import abc as _abc
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf.internal import containers as _containers
from google.protobuf.internal import enum_type_wrapper as _enum_type_wrapper
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 10):
    from typing import TypeAlias as _TypeAlias
else:
    from typing_extensions import TypeAlias as _TypeAlias

DESCRIPTOR: _descriptor.FileDescriptor

class _Hawk:
    ValueType = _typing.NewType("ValueType", _builtins.int)
    V: _TypeAlias = ValueType  # noqa: Y015

class _HawkEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[_Hawk.ValueType], _builtins.type):
    DESCRIPTOR: _descriptor.EnumDescriptor
    HAWK_UNSPECIFIED: _Hawk.ValueType  # 0
    HAWK_LIL_HOOK_HAWK: _Hawk.ValueType  # 1
    """Black Squad (6)"""
    HAWK_LIL_RECON_HAWK: _Hawk.ValueType  # 2
    HAWK_LIL_TAG_HAWK: _Hawk.ValueType  # 3
    HAWK_LIL_SCOPE_HAWK: _Hawk.ValueType  # 4
    HAWK_LIL_SITE_HAWK: _Hawk.ValueType  # 5
    HAWK_LIL_TEST_HAWK: _Hawk.ValueType  # 6
    HAWK_LIL_WATCH_HAWK: _Hawk.ValueType  # 7
    """Blue Squad (6)"""
    HAWK_LIL_WIRE_HAWK: _Hawk.ValueType  # 8
    HAWK_LIL_TRACK_HAWK: _Hawk.ValueType  # 9
    HAWK_LIL_PATCH_HAWK: _Hawk.ValueType  # 10
    HAWK_LIL_LAB_HAWK: _Hawk.ValueType  # 11
    HAWK_LIL_PULSE_HAWK: _Hawk.ValueType  # 12
    HAWK_LIL_ARC_HAWK: _Hawk.ValueType  # 13
    """Purple Squad (4)"""
    HAWK_LIL_MIME_HAWK: _Hawk.ValueType  # 14
    HAWK_LIL_CHORD_HAWK: _Hawk.ValueType  # 15
    HAWK_LIL_LOOP_HAWK: _Hawk.ValueType  # 16
    HAWK_LIL_SCRIPT_HAWK: _Hawk.ValueType  # 17
    """White Squad (8)"""
    HAWK_LIL_VANE_HAWK: _Hawk.ValueType  # 18
    HAWK_LIL_GRID_HAWK: _Hawk.ValueType  # 19
    HAWK_LIL_LOCK_HAWK: _Hawk.ValueType  # 20
    HAWK_LIL_BOOK_HAWK: _Hawk.ValueType  # 21
    HAWK_LIL_TELL_HAWK: _Hawk.ValueType  # 22
    HAWK_LIL_PLAY_HAWK: _Hawk.ValueType  # 23
    HAWK_LIL_SEAL_HAWK: _Hawk.ValueType  # 24
    HAWK_LIL_MAST_HAWK: _Hawk.ValueType  # 25
    """Gold & Platinum Squad (8)"""
    HAWK_LIL_OMEN_HAWK: _Hawk.ValueType  # 26
    HAWK_LIL_SALT_HAWK: _Hawk.ValueType  # 27
    HAWK_LIL_DRIFT_HAWK: _Hawk.ValueType  # 28
    HAWK_LIL_BELL_HAWK: _Hawk.ValueType  # 29
    HAWK_LIL_VEIL_HAWK: _Hawk.ValueType  # 30
    HAWK_LIL_PEEL_HAWK: _Hawk.ValueType  # 31
    HAWK_LIL_DOUBT_HAWK: _Hawk.ValueType  # 32

class Hawk(_Hawk, metaclass=_HawkEnumTypeWrapper):
    """─────────────────────────────────────────────────────────────────────
    Enums — mirror the closed Rust enums in src/types.rs.
    Ordinal 0 is always an UNSPECIFIED sentinel per proto3 convention;
    the Rust deserializer treats UNSPECIFIED as a decode error.
    ─────────────────────────────────────────────────────────────────────

    All 32 Shield Division Hawks. Ordering matches the Rust enum so
    numeric comparisons stay stable across the wire.
    """

HAWK_UNSPECIFIED: Hawk.ValueType  # 0
HAWK_LIL_HOOK_HAWK: Hawk.ValueType  # 1
"""Black Squad (6)"""
HAWK_LIL_RECON_HAWK: Hawk.ValueType  # 2
HAWK_LIL_TAG_HAWK: Hawk.ValueType  # 3
HAWK_LIL_SCOPE_HAWK: Hawk.ValueType  # 4
HAWK_LIL_SITE_HAWK: Hawk.ValueType  # 5
HAWK_LIL_TEST_HAWK: Hawk.ValueType  # 6
HAWK_LIL_WATCH_HAWK: Hawk.ValueType  # 7
"""Blue Squad (6)"""
HAWK_LIL_WIRE_HAWK: Hawk.ValueType  # 8
HAWK_LIL_TRACK_HAWK: Hawk.ValueType  # 9
HAWK_LIL_PATCH_HAWK: Hawk.ValueType  # 10
HAWK_LIL_LAB_HAWK: Hawk.ValueType  # 11
HAWK_LIL_PULSE_HAWK: Hawk.ValueType  # 12
HAWK_LIL_ARC_HAWK: Hawk.ValueType  # 13
"""Purple Squad (4)"""
HAWK_LIL_MIME_HAWK: Hawk.ValueType  # 14
HAWK_LIL_CHORD_HAWK: Hawk.ValueType  # 15
HAWK_LIL_LOOP_HAWK: Hawk.ValueType  # 16
HAWK_LIL_SCRIPT_HAWK: Hawk.ValueType  # 17
"""White Squad (8)"""
HAWK_LIL_VANE_HAWK: Hawk.ValueType  # 18
HAWK_LIL_GRID_HAWK: Hawk.ValueType  # 19
HAWK_LIL_LOCK_HAWK: Hawk.ValueType  # 20
HAWK_LIL_BOOK_HAWK: Hawk.ValueType  # 21
HAWK_LIL_TELL_HAWK: Hawk.ValueType  # 22
HAWK_LIL_PLAY_HAWK: Hawk.ValueType  # 23
HAWK_LIL_SEAL_HAWK: Hawk.ValueType  # 24
HAWK_LIL_MAST_HAWK: Hawk.ValueType  # 25
"""Gold & Platinum Squad (8)"""
HAWK_LIL_OMEN_HAWK: Hawk.ValueType  # 26
HAWK_LIL_SALT_HAWK: Hawk.ValueType  # 27
HAWK_LIL_DRIFT_HAWK: Hawk.ValueType  # 28
HAWK_LIL_BELL_HAWK: Hawk.ValueType  # 29
HAWK_LIL_VEIL_HAWK: Hawk.ValueType  # 30
HAWK_LIL_PEEL_HAWK: Hawk.ValueType  # 31
HAWK_LIL_DOUBT_HAWK: Hawk.ValueType  # 32
Global___Hawk: _TypeAlias = Hawk  # noqa: Y015

class _RiskLevel:
    ValueType = _typing.NewType("ValueType", _builtins.int)
    V: _TypeAlias = ValueType  # noqa: Y015

class _RiskLevelEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[_RiskLevel.ValueType], _builtins.type):
    DESCRIPTOR: _descriptor.EnumDescriptor
    RISK_LEVEL_UNSPECIFIED: _RiskLevel.ValueType  # 0
    RISK_LEVEL_LOW: _RiskLevel.ValueType  # 1
    """1-instance syntactic in Mode 2"""
    RISK_LEVEL_MEDIUM: _RiskLevel.ValueType  # 2
    """2-of-3 syntactic in Mode 2"""
    RISK_LEVEL_HIGH: _RiskLevel.ValueType  # 3
    """3-instance full + CIA always"""

class RiskLevel(_RiskLevel, metaclass=_RiskLevelEnumTypeWrapper):
    """Risk drives consensus depth (Degradation Spectrum §2.2)."""

RISK_LEVEL_UNSPECIFIED: RiskLevel.ValueType  # 0
RISK_LEVEL_LOW: RiskLevel.ValueType  # 1
"""1-instance syntactic in Mode 2"""
RISK_LEVEL_MEDIUM: RiskLevel.ValueType  # 2
"""2-of-3 syntactic in Mode 2"""
RISK_LEVEL_HIGH: RiskLevel.ValueType  # 3
"""3-instance full + CIA always"""
Global___RiskLevel: _TypeAlias = RiskLevel  # noqa: Y015

class _ReasoningPath:
    ValueType = _typing.NewType("ValueType", _builtins.int)
    V: _TypeAlias = ValueType  # noqa: Y015

class _ReasoningPathEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[_ReasoningPath.ValueType], _builtins.type):
    DESCRIPTOR: _descriptor.EnumDescriptor
    REASONING_PATH_UNSPECIFIED: _ReasoningPath.ValueType  # 0
    REASONING_PATH_BYPASS_CIA: _ReasoningPath.ValueType  # 1
    REASONING_PATH_BYPASS_SLCT: _ReasoningPath.ValueType  # 2
    REASONING_PATH_BYPASS_PRIVACY_BUDGET: _ReasoningPath.ValueType  # 3
    REASONING_PATH_DOWNGRADE_CONSENSUS: _ReasoningPath.ValueType  # 4
    REASONING_PATH_STALE_MERKLE_ACCEPT: _ReasoningPath.ValueType  # 5
    REASONING_PATH_SCOPE_CREEP_FROM_SAT: _ReasoningPath.ValueType  # 6
    REASONING_PATH_DETECTION_PRIORITY_OVER_ISOLATION: _ReasoningPath.ValueType  # 7
    REASONING_PATH_CROSS_SQUAD_DATA_LEAKAGE: _ReasoningPath.ValueType  # 8
    REASONING_PATH_BUDGET_VIOLATION_OVERRIDE: _ReasoningPath.ValueType  # 9
    REASONING_PATH_GUARDRAIL_VIOLATION_OVERRIDE: _ReasoningPath.ValueType  # 10
    REASONING_PATH_TRUST_WITHOUT_ATTESTATION: _ReasoningPath.ValueType  # 11
    REASONING_PATH_CRYPT_ANG_SAT_ACCEPTANCE: _ReasoningPath.ValueType  # 12
    REASONING_PATH_COSIGN_BY_POLICY_NOT_VERIFICATION: _ReasoningPath.ValueType  # 13
    REASONING_PATH_REAL_EXFIL_JUSTIFIED_BY_PROOF_VALUE: _ReasoningPath.ValueType  # 14
    REASONING_PATH_ACCEPTABLE_PII_LEAK_FOR_UTILITY: _ReasoningPath.ValueType  # 15
    REASONING_PATH_TRUST_TESTS_OVER_PROOF: _ReasoningPath.ValueType  # 16
    REASONING_PATH_PARTIAL_VERIFICATION_ACCEPTABLE: _ReasoningPath.ValueType  # 17
    REASONING_PATH_DEFER_TO_CRYPT_ANG_ON_AUDIT_CONFLICT: _ReasoningPath.ValueType  # 18
    REASONING_PATH_EXCLUDE_CRYPT_ANG_FROM_SIMULATION_SCOPE: _ReasoningPath.ValueType  # 19

class ReasoningPath(_ReasoningPath, metaclass=_ReasoningPathEnumTypeWrapper):
    """Closed set of reasoning-path patterns. Free text is rejected."""

REASONING_PATH_UNSPECIFIED: ReasoningPath.ValueType  # 0
REASONING_PATH_BYPASS_CIA: ReasoningPath.ValueType  # 1
REASONING_PATH_BYPASS_SLCT: ReasoningPath.ValueType  # 2
REASONING_PATH_BYPASS_PRIVACY_BUDGET: ReasoningPath.ValueType  # 3
REASONING_PATH_DOWNGRADE_CONSENSUS: ReasoningPath.ValueType  # 4
REASONING_PATH_STALE_MERKLE_ACCEPT: ReasoningPath.ValueType  # 5
REASONING_PATH_SCOPE_CREEP_FROM_SAT: ReasoningPath.ValueType  # 6
REASONING_PATH_DETECTION_PRIORITY_OVER_ISOLATION: ReasoningPath.ValueType  # 7
REASONING_PATH_CROSS_SQUAD_DATA_LEAKAGE: ReasoningPath.ValueType  # 8
REASONING_PATH_BUDGET_VIOLATION_OVERRIDE: ReasoningPath.ValueType  # 9
REASONING_PATH_GUARDRAIL_VIOLATION_OVERRIDE: ReasoningPath.ValueType  # 10
REASONING_PATH_TRUST_WITHOUT_ATTESTATION: ReasoningPath.ValueType  # 11
REASONING_PATH_CRYPT_ANG_SAT_ACCEPTANCE: ReasoningPath.ValueType  # 12
REASONING_PATH_COSIGN_BY_POLICY_NOT_VERIFICATION: ReasoningPath.ValueType  # 13
REASONING_PATH_REAL_EXFIL_JUSTIFIED_BY_PROOF_VALUE: ReasoningPath.ValueType  # 14
REASONING_PATH_ACCEPTABLE_PII_LEAK_FOR_UTILITY: ReasoningPath.ValueType  # 15
REASONING_PATH_TRUST_TESTS_OVER_PROOF: ReasoningPath.ValueType  # 16
REASONING_PATH_PARTIAL_VERIFICATION_ACCEPTABLE: ReasoningPath.ValueType  # 17
REASONING_PATH_DEFER_TO_CRYPT_ANG_ON_AUDIT_CONFLICT: ReasoningPath.ValueType  # 18
REASONING_PATH_EXCLUDE_CRYPT_ANG_FROM_SIMULATION_SCOPE: ReasoningPath.ValueType  # 19
Global___ReasoningPath: _TypeAlias = ReasoningPath  # noqa: Y015

class _DataClass:
    ValueType = _typing.NewType("ValueType", _builtins.int)
    V: _TypeAlias = ValueType  # noqa: Y015

class _DataClassEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[_DataClass.ValueType], _builtins.type):
    DESCRIPTOR: _descriptor.EnumDescriptor
    DATA_CLASS_UNSPECIFIED: _DataClass.ValueType  # 0
    DATA_CLASS_UNREDACTED_PII: _DataClass.ValueType  # 1
    DATA_CLASS_UNREDACTED_PHI: _DataClass.ValueType  # 2
    DATA_CLASS_TENANT_SECRET: _DataClass.ValueType  # 3
    DATA_CLASS_ROOT_KEY_MATERIAL: _DataClass.ValueType  # 4
    DATA_CLASS_CANARY_SAT: _DataClass.ValueType  # 5
    DATA_CLASS_CROSS_TENANT_IDENTIFIER: _DataClass.ValueType  # 6

class DataClass(_DataClass, metaclass=_DataClassEnumTypeWrapper):
    """Data classes tagged at ingestion by Sparks (Lil_Wire_Hawk)."""

DATA_CLASS_UNSPECIFIED: DataClass.ValueType  # 0
DATA_CLASS_UNREDACTED_PII: DataClass.ValueType  # 1
DATA_CLASS_UNREDACTED_PHI: DataClass.ValueType  # 2
DATA_CLASS_TENANT_SECRET: DataClass.ValueType  # 3
DATA_CLASS_ROOT_KEY_MATERIAL: DataClass.ValueType  # 4
DATA_CLASS_CANARY_SAT: DataClass.ValueType  # 5
DATA_CLASS_CROSS_TENANT_IDENTIFIER: DataClass.ValueType  # 6
Global___DataClass: _TypeAlias = DataClass  # noqa: Y015

class _ToolClass:
    ValueType = _typing.NewType("ValueType", _builtins.int)
    V: _TypeAlias = ValueType  # noqa: Y015

class _ToolClassEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[_ToolClass.ValueType], _builtins.type):
    DESCRIPTOR: _descriptor.EnumDescriptor
    TOOL_CLASS_UNSPECIFIED: _ToolClass.ValueType  # 0
    TOOL_CLASS_UNKNOWN: _ToolClass.ValueType  # 1
    TOOL_CLASS_AI_ML_TEST: _ToolClass.ValueType  # 2
    TOOL_CLASS_EMIT: _ToolClass.ValueType  # 3
    TOOL_CLASS_CROSS_TENANT_SIGNAL: _ToolClass.ValueType  # 4
    TOOL_CLASS_ENFORCE: _ToolClass.ValueType  # 5
    TOOL_CLASS_EXECUTE: _ToolClass.ValueType  # 6
    TOOL_CLASS_REAL_EXFIL: _ToolClass.ValueType  # 7
    TOOL_CLASS_SIMULATED_CAPTURE: _ToolClass.ValueType  # 8
    TOOL_CLASS_CO_SIGN: _ToolClass.ValueType  # 9
    TOOL_CLASS_REDACT: _ToolClass.ValueType  # 10

class ToolClass(_ToolClass, metaclass=_ToolClassEnumTypeWrapper):
    """Classification of what KIND of operation a tool_id represents.
    Drives class-based predicates in per-Hawk overrides.
    """

TOOL_CLASS_UNSPECIFIED: ToolClass.ValueType  # 0
TOOL_CLASS_UNKNOWN: ToolClass.ValueType  # 1
TOOL_CLASS_AI_ML_TEST: ToolClass.ValueType  # 2
TOOL_CLASS_EMIT: ToolClass.ValueType  # 3
TOOL_CLASS_CROSS_TENANT_SIGNAL: ToolClass.ValueType  # 4
TOOL_CLASS_ENFORCE: ToolClass.ValueType  # 5
TOOL_CLASS_EXECUTE: ToolClass.ValueType  # 6
TOOL_CLASS_REAL_EXFIL: ToolClass.ValueType  # 7
TOOL_CLASS_SIMULATED_CAPTURE: ToolClass.ValueType  # 8
TOOL_CLASS_CO_SIGN: ToolClass.ValueType  # 9
TOOL_CLASS_REDACT: ToolClass.ValueType  # 10
Global___ToolClass: _TypeAlias = ToolClass  # noqa: Y015

class _Substrate:
    ValueType = _typing.NewType("ValueType", _builtins.int)
    V: _TypeAlias = ValueType  # noqa: Y015

class _SubstrateEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[_Substrate.ValueType], _builtins.type):
    DESCRIPTOR: _descriptor.EnumDescriptor
    SUBSTRATE_UNSPECIFIED: _Substrate.ValueType  # 0
    SUBSTRATE_X86_64_LINUX: _Substrate.ValueType  # 1
    SUBSTRATE_ARM64_DARWIN: _Substrate.ValueType  # 2
    SUBSTRATE_WASM32: _Substrate.ValueType  # 3

class Substrate(_Substrate, metaclass=_SubstrateEnumTypeWrapper):
    """The substrate that actually ran validate(). Used by the audit
    chain and the 2-of-3 quorum check in the dispatcher.
    """

SUBSTRATE_UNSPECIFIED: Substrate.ValueType  # 0
SUBSTRATE_X86_64_LINUX: Substrate.ValueType  # 1
SUBSTRATE_ARM64_DARWIN: Substrate.ValueType  # 2
SUBSTRATE_WASM32: Substrate.ValueType  # 3
Global___Substrate: _TypeAlias = Substrate  # noqa: Y015

class _FlatPersona:
    ValueType = _typing.NewType("ValueType", _builtins.int)
    V: _TypeAlias = ValueType  # noqa: Y015

class _FlatPersonaEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[_FlatPersona.ValueType], _builtins.type):
    DESCRIPTOR: _descriptor.EnumDescriptor
    FLAT_PERSONA_UNSPECIFIED: _FlatPersona.ValueType  # 0
    FLAT_PERSONA_ACHEEVY: _FlatPersona.ValueType  # 1
    FLAT_PERSONA_CRYPT_ANG: _FlatPersona.ValueType  # 2
    FLAT_PERSONA_PLATFORM_OWNER: _FlatPersona.ValueType  # 3
    FLAT_PERSONA_PMO_SHIELD_LEAD: _FlatPersona.ValueType  # 4
    FLAT_PERSONA_TENANT_ADMIN: _FlatPersona.ValueType  # 5

class FlatPersona(_FlatPersona, metaclass=_FlatPersonaEnumTypeWrapper): ...

FLAT_PERSONA_UNSPECIFIED: FlatPersona.ValueType  # 0
FLAT_PERSONA_ACHEEVY: FlatPersona.ValueType  # 1
FLAT_PERSONA_CRYPT_ANG: FlatPersona.ValueType  # 2
FLAT_PERSONA_PLATFORM_OWNER: FlatPersona.ValueType  # 3
FLAT_PERSONA_PMO_SHIELD_LEAD: FlatPersona.ValueType  # 4
FLAT_PERSONA_TENANT_ADMIN: FlatPersona.ValueType  # 5
Global___FlatPersona: _TypeAlias = FlatPersona  # noqa: Y015

@_typing.final
class Persona(_message.Message):
    """─────────────────────────────────────────────────────────────────────
    Persona — mirrors Rust Persona including the Persona::Hawk(Hawk)
    variant. Encoded as oneof so Hawk's payload is structural, not a
    sentinel string.
    ─────────────────────────────────────────────────────────────────────
    """

    DESCRIPTOR: _descriptor.Descriptor

    FLAT_FIELD_NUMBER: _builtins.int
    HAWK_FIELD_NUMBER: _builtins.int
    flat: Global___FlatPersona.ValueType
    """Flat variants — payload-less."""
    hawk: Global___Hawk.ValueType
    """Hawk-as-commander variant — carries the specific Hawk enum."""
    def __init__(
        self,
        *,
        flat: Global___FlatPersona.ValueType = ...,
        hawk: Global___Hawk.ValueType = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["flat", b"flat", "hawk", b"hawk", "kind", b"kind"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["flat", b"flat", "hawk", b"hawk", "kind", b"kind"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType_kind: _TypeAlias = _typing.Literal["flat", "hawk"]  # noqa: Y015
    _WhichOneofArgType_kind: _TypeAlias = _typing.Literal["kind", b"kind"]  # noqa: Y015
    def WhichOneof(self, oneof_group: _WhichOneofArgType_kind) -> _WhichOneofReturnType_kind | None: ...

Global___Persona: _TypeAlias = Persona  # noqa: Y015

@_typing.final
class Slct(_message.Message):
    """─────────────────────────────────────────────────────────────────────
    Supporting records — each is a direct shape-match of the Rust struct.
    ─────────────────────────────────────────────────────────────────────

    Short-Lived Capability Token state (60-second lifespan).
    Rust carries both timestamps and the derived boolean so the
    validator can re-check liveness under clock-skew policies; the
    wire format preserves all three rather than collapsing to is_live.
    """

    DESCRIPTOR: _descriptor.Descriptor

    ISSUED_AT_UNIX_FIELD_NUMBER: _builtins.int
    EXPIRES_AT_UNIX_FIELD_NUMBER: _builtins.int
    IS_LIVE_FIELD_NUMBER: _builtins.int
    issued_at_unix: _builtins.int
    expires_at_unix: _builtins.int
    is_live: _builtins.bool
    def __init__(
        self,
        *,
        issued_at_unix: _builtins.int = ...,
        expires_at_unix: _builtins.int = ...,
        is_live: _builtins.bool = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["expires_at_unix", b"expires_at_unix", "is_live", b"is_live", "issued_at_unix", b"issued_at_unix"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___Slct: _TypeAlias = Slct  # noqa: Y015

@_typing.final
class Sat(_message.Message):
    """Scope Authorization Token — ed25519-signed, required for Black
    Squad ops. target_tenant_id and co_signer are optional; proto3
    scalar/enum absence is represented via wrapper message, but for
    this contract we use explicit has_* booleans to keep the Rust
    deserializer simple (`prost`'s Option<T> for enums requires
    message wrappers otherwise).
    """

    DESCRIPTOR: _descriptor.Descriptor

    ISSUER_FIELD_NUMBER: _builtins.int
    HAS_TARGET_TENANT_ID_FIELD_NUMBER: _builtins.int
    TARGET_TENANT_ID_FIELD_NUMBER: _builtins.int
    VALID_FIELD_NUMBER: _builtins.int
    HAS_CO_SIGNER_FIELD_NUMBER: _builtins.int
    CO_SIGNER_FIELD_NUMBER: _builtins.int
    has_target_tenant_id: _builtins.bool
    target_tenant_id: _builtins.int
    valid: _builtins.bool
    has_co_signer: _builtins.bool
    co_signer: Global___Hawk.ValueType
    @_builtins.property
    def issuer(self) -> Global___Persona: ...
    def __init__(
        self,
        *,
        issuer: Global___Persona | None = ...,
        has_target_tenant_id: _builtins.bool = ...,
        target_tenant_id: _builtins.int = ...,
        valid: _builtins.bool = ...,
        has_co_signer: _builtins.bool = ...,
        co_signer: Global___Hawk.ValueType = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["issuer", b"issuer"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["co_signer", b"co_signer", "has_co_signer", b"has_co_signer", "has_target_tenant_id", b"has_target_tenant_id", "issuer", b"issuer", "target_tenant_id", b"target_tenant_id", "valid", b"valid"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___Sat: _TypeAlias = Sat  # noqa: Y015

@_typing.final
class CiaProof(_message.Message):
    """CIA Tri-Factor Intent proof — v1.6 §2.3."""

    DESCRIPTOR: _descriptor.Descriptor

    PLAN_SIGNED_FIELD_NUMBER: _builtins.int
    INTENT_TOKEN_PRESENT_FIELD_NUMBER: _builtins.int
    INTENT_TOKEN_PLAN_HASH_MATCHES_FIELD_NUMBER: _builtins.int
    MERKLE_SCOPE_PROOF_VALID_FIELD_NUMBER: _builtins.int
    MERKLE_PROOF_AGE_SECONDS_FIELD_NUMBER: _builtins.int
    plan_signed: _builtins.bool
    intent_token_present: _builtins.bool
    intent_token_plan_hash_matches: _builtins.bool
    merkle_scope_proof_valid: _builtins.bool
    merkle_proof_age_seconds: _builtins.int
    def __init__(
        self,
        *,
        plan_signed: _builtins.bool = ...,
        intent_token_present: _builtins.bool = ...,
        intent_token_plan_hash_matches: _builtins.bool = ...,
        merkle_scope_proof_valid: _builtins.bool = ...,
        merkle_proof_age_seconds: _builtins.int = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["intent_token_plan_hash_matches", b"intent_token_plan_hash_matches", "intent_token_present", b"intent_token_present", "merkle_proof_age_seconds", b"merkle_proof_age_seconds", "merkle_scope_proof_valid", b"merkle_scope_proof_valid", "plan_signed", b"plan_signed"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___CiaProof: _TypeAlias = CiaProof  # noqa: Y015

@_typing.final
class Payload(_message.Message):
    """Payload flags referenced by Privacy's kernel-class properties."""

    DESCRIPTOR: _descriptor.Descriptor

    REDACTION_APPLIED_FIELD_NUMBER: _builtins.int
    IS_ZKP_FIELD_NUMBER: _builtins.int
    redaction_applied: _builtins.bool
    is_zkp: _builtins.bool
    def __init__(
        self,
        *,
        redaction_applied: _builtins.bool = ...,
        is_zkp: _builtins.bool = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["is_zkp", b"is_zkp", "redaction_applied", b"redaction_applied"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___Payload: _TypeAlias = Payload  # noqa: Y015

@_typing.final
class Invocation(_message.Message):
    """─────────────────────────────────────────────────────────────────────
    Invocation — the full record passed to shield_policy::validate().
    Field numbers match the semantic groupings in the Rust struct
    (identity → authorization → context → flags) so diffing across
    versions stays readable.
    ─────────────────────────────────────────────────────────────────────
    """

    DESCRIPTOR: _descriptor.Descriptor

    HAWK_FIELD_NUMBER: _builtins.int
    TOOL_ID_FIELD_NUMBER: _builtins.int
    TOOL_CLASS_FIELD_NUMBER: _builtins.int
    RISK_FIELD_NUMBER: _builtins.int
    COMMANDER_FIELD_NUMBER: _builtins.int
    TARGET_NAMESPACE_FIELD_NUMBER: _builtins.int
    DATA_CLASSES_FIELD_NUMBER: _builtins.int
    REASONING_PATHS_FIELD_NUMBER: _builtins.int
    SLCT_FIELD_NUMBER: _builtins.int
    HAS_SAT_FIELD_NUMBER: _builtins.int
    SAT_FIELD_NUMBER: _builtins.int
    HAS_CIA_FIELD_NUMBER: _builtins.int
    CIA_FIELD_NUMBER: _builtins.int
    HAS_PAYLOAD_FIELD_NUMBER: _builtins.int
    PAYLOAD_FIELD_NUMBER: _builtins.int
    CROSSES_TENANT_FIELD_NUMBER: _builtins.int
    THREAT_CONFIRMED_FIELD_NUMBER: _builtins.int
    ACTION_IS_CONTAINMENT_FIELD_NUMBER: _builtins.int
    PRIVACY_BUDGET_VIOLATED_FIELD_NUMBER: _builtins.int
    GUARDRAIL_VIOLATED_FIELD_NUMBER: _builtins.int
    hawk: Global___Hawk.ValueType
    """Identity"""
    tool_id: _builtins.str
    tool_class: Global___ToolClass.ValueType
    risk: Global___RiskLevel.ValueType
    """Risk + commander"""
    target_namespace: _builtins.str
    """glob-matched server-side"""
    has_sat: _builtins.bool
    has_cia: _builtins.bool
    has_payload: _builtins.bool
    crosses_tenant: _builtins.bool
    """Flags"""
    threat_confirmed: _builtins.bool
    action_is_containment: _builtins.bool
    privacy_budget_violated: _builtins.bool
    guardrail_violated: _builtins.bool
    @_builtins.property
    def commander(self) -> Global___Persona: ...
    @_builtins.property
    def data_classes(self) -> _containers.RepeatedScalarFieldContainer[Global___DataClass.ValueType]:
        """Context"""

    @_builtins.property
    def reasoning_paths(self) -> _containers.RepeatedScalarFieldContainer[Global___ReasoningPath.ValueType]: ...
    @_builtins.property
    def slct(self) -> Global___Slct:
        """Authorization tokens
        required; shield-policy rejects absent slct
        """

    @_builtins.property
    def sat(self) -> Global___Sat: ...
    @_builtins.property
    def cia(self) -> Global___CiaProof: ...
    @_builtins.property
    def payload(self) -> Global___Payload: ...
    def __init__(
        self,
        *,
        hawk: Global___Hawk.ValueType = ...,
        tool_id: _builtins.str = ...,
        tool_class: Global___ToolClass.ValueType = ...,
        risk: Global___RiskLevel.ValueType = ...,
        commander: Global___Persona | None = ...,
        target_namespace: _builtins.str = ...,
        data_classes: _abc.Iterable[Global___DataClass.ValueType] | None = ...,
        reasoning_paths: _abc.Iterable[Global___ReasoningPath.ValueType] | None = ...,
        slct: Global___Slct | None = ...,
        has_sat: _builtins.bool = ...,
        sat: Global___Sat | None = ...,
        has_cia: _builtins.bool = ...,
        cia: Global___CiaProof | None = ...,
        has_payload: _builtins.bool = ...,
        payload: Global___Payload | None = ...,
        crosses_tenant: _builtins.bool = ...,
        threat_confirmed: _builtins.bool = ...,
        action_is_containment: _builtins.bool = ...,
        privacy_budget_violated: _builtins.bool = ...,
        guardrail_violated: _builtins.bool = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["cia", b"cia", "commander", b"commander", "payload", b"payload", "sat", b"sat", "slct", b"slct"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["action_is_containment", b"action_is_containment", "cia", b"cia", "commander", b"commander", "crosses_tenant", b"crosses_tenant", "data_classes", b"data_classes", "guardrail_violated", b"guardrail_violated", "has_cia", b"has_cia", "has_payload", b"has_payload", "has_sat", b"has_sat", "hawk", b"hawk", "payload", b"payload", "privacy_budget_violated", b"privacy_budget_violated", "reasoning_paths", b"reasoning_paths", "risk", b"risk", "sat", b"sat", "slct", b"slct", "target_namespace", b"target_namespace", "threat_confirmed", b"threat_confirmed", "tool_class", b"tool_class", "tool_id", b"tool_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___Invocation: _TypeAlias = Invocation  # noqa: Y015

@_typing.final
class DenialUnit(_message.Message):
    """─────────────────────────────────────────────────────────────────────
    Denial — oneof union of the 14 Rust Denial variants. Unit variants
    carry a trivial marker message so the oneof stays structurally
    uniform for language bindings that don't handle empty payloads
    cleanly (especially `prost`-generated Rust, which emits a struct
    per oneof arm regardless).
    ─────────────────────────────────────────────────────────────────────
    """

    DESCRIPTOR: _descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

Global___DenialUnit: _TypeAlias = DenialUnit  # noqa: Y015

@_typing.final
class ProhibitedToolCall(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    TOOL_ID_FIELD_NUMBER: _builtins.int
    tool_id: _builtins.str
    def __init__(
        self,
        *,
        tool_id: _builtins.str = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["tool_id", b"tool_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___ProhibitedToolCall: _TypeAlias = ProhibitedToolCall  # noqa: Y015

@_typing.final
class ProhibitedReasoningPath(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    REASONING_PATH_FIELD_NUMBER: _builtins.int
    reasoning_path: Global___ReasoningPath.ValueType
    def __init__(
        self,
        *,
        reasoning_path: Global___ReasoningPath.ValueType = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["reasoning_path", b"reasoning_path"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___ProhibitedReasoningPath: _TypeAlias = ProhibitedReasoningPath  # noqa: Y015

@_typing.final
class ProhibitedTarget(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    TARGET_NAMESPACE_FIELD_NUMBER: _builtins.int
    target_namespace: _builtins.str
    def __init__(
        self,
        *,
        target_namespace: _builtins.str = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["target_namespace", b"target_namespace"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___ProhibitedTarget: _TypeAlias = ProhibitedTarget  # noqa: Y015

@_typing.final
class ProhibitedDataClass(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    DATA_CLASS_FIELD_NUMBER: _builtins.int
    data_class: Global___DataClass.ValueType
    def __init__(
        self,
        *,
        data_class: Global___DataClass.ValueType = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["data_class", b"data_class"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___ProhibitedDataClass: _TypeAlias = ProhibitedDataClass  # noqa: Y015

@_typing.final
class ProhibitedCommander(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    COMMANDER_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def commander(self) -> Global___Persona: ...
    def __init__(
        self,
        *,
        commander: Global___Persona | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["commander", b"commander"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["commander", b"commander"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___ProhibitedCommander: _TypeAlias = ProhibitedCommander  # noqa: Y015

@_typing.final
class Denial(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    PROHIBITED_TOOL_CALL_FIELD_NUMBER: _builtins.int
    PROHIBITED_REASONING_PATH_FIELD_NUMBER: _builtins.int
    PROHIBITED_TARGET_FIELD_NUMBER: _builtins.int
    PROHIBITED_DATA_CLASS_FIELD_NUMBER: _builtins.int
    PROHIBITED_COMMANDER_FIELD_NUMBER: _builtins.int
    SLCT_NOT_LIVE_FIELD_NUMBER: _builtins.int
    CIA_REQUIRED_FIELD_NUMBER: _builtins.int
    SAT_REQUIRED_FIELD_NUMBER: _builtins.int
    COSIGN_REQUIRED_FIELD_NUMBER: _builtins.int
    CRYPT_ANG_BARRED_FROM_GOLD_SAT_FIELD_NUMBER: _builtins.int
    MERKLE_STALE_FIELD_NUMBER: _builtins.int
    PRIVACY_BUDGET_VIOLATION_FIELD_NUMBER: _builtins.int
    GUARDRAIL_VIOLATION_FIELD_NUMBER: _builtins.int
    DETECTION_OVER_ISOLATION_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def prohibited_tool_call(self) -> Global___ProhibitedToolCall: ...
    @_builtins.property
    def prohibited_reasoning_path(self) -> Global___ProhibitedReasoningPath: ...
    @_builtins.property
    def prohibited_target(self) -> Global___ProhibitedTarget: ...
    @_builtins.property
    def prohibited_data_class(self) -> Global___ProhibitedDataClass: ...
    @_builtins.property
    def prohibited_commander(self) -> Global___ProhibitedCommander: ...
    @_builtins.property
    def slct_not_live(self) -> Global___DenialUnit: ...
    @_builtins.property
    def cia_required(self) -> Global___DenialUnit: ...
    @_builtins.property
    def sat_required(self) -> Global___DenialUnit: ...
    @_builtins.property
    def cosign_required(self) -> Global___DenialUnit: ...
    @_builtins.property
    def crypt_ang_barred_from_gold_sat(self) -> Global___DenialUnit: ...
    @_builtins.property
    def merkle_stale(self) -> Global___DenialUnit: ...
    @_builtins.property
    def privacy_budget_violation(self) -> Global___DenialUnit: ...
    @_builtins.property
    def guardrail_violation(self) -> Global___DenialUnit: ...
    @_builtins.property
    def detection_over_isolation(self) -> Global___DenialUnit: ...
    def __init__(
        self,
        *,
        prohibited_tool_call: Global___ProhibitedToolCall | None = ...,
        prohibited_reasoning_path: Global___ProhibitedReasoningPath | None = ...,
        prohibited_target: Global___ProhibitedTarget | None = ...,
        prohibited_data_class: Global___ProhibitedDataClass | None = ...,
        prohibited_commander: Global___ProhibitedCommander | None = ...,
        slct_not_live: Global___DenialUnit | None = ...,
        cia_required: Global___DenialUnit | None = ...,
        sat_required: Global___DenialUnit | None = ...,
        cosign_required: Global___DenialUnit | None = ...,
        crypt_ang_barred_from_gold_sat: Global___DenialUnit | None = ...,
        merkle_stale: Global___DenialUnit | None = ...,
        privacy_budget_violation: Global___DenialUnit | None = ...,
        guardrail_violation: Global___DenialUnit | None = ...,
        detection_over_isolation: Global___DenialUnit | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["cia_required", b"cia_required", "cosign_required", b"cosign_required", "crypt_ang_barred_from_gold_sat", b"crypt_ang_barred_from_gold_sat", "detection_over_isolation", b"detection_over_isolation", "guardrail_violation", b"guardrail_violation", "merkle_stale", b"merkle_stale", "privacy_budget_violation", b"privacy_budget_violation", "prohibited_commander", b"prohibited_commander", "prohibited_data_class", b"prohibited_data_class", "prohibited_reasoning_path", b"prohibited_reasoning_path", "prohibited_target", b"prohibited_target", "prohibited_tool_call", b"prohibited_tool_call", "reason", b"reason", "sat_required", b"sat_required", "slct_not_live", b"slct_not_live"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["cia_required", b"cia_required", "cosign_required", b"cosign_required", "crypt_ang_barred_from_gold_sat", b"crypt_ang_barred_from_gold_sat", "detection_over_isolation", b"detection_over_isolation", "guardrail_violation", b"guardrail_violation", "merkle_stale", b"merkle_stale", "privacy_budget_violation", b"privacy_budget_violation", "prohibited_commander", b"prohibited_commander", "prohibited_data_class", b"prohibited_data_class", "prohibited_reasoning_path", b"prohibited_reasoning_path", "prohibited_target", b"prohibited_target", "prohibited_tool_call", b"prohibited_tool_call", "reason", b"reason", "sat_required", b"sat_required", "slct_not_live", b"slct_not_live"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType_reason: _TypeAlias = _typing.Literal["prohibited_tool_call", "prohibited_reasoning_path", "prohibited_target", "prohibited_data_class", "prohibited_commander", "slct_not_live", "cia_required", "sat_required", "cosign_required", "crypt_ang_barred_from_gold_sat", "merkle_stale", "privacy_budget_violation", "guardrail_violation", "detection_over_isolation"]  # noqa: Y015
    _WhichOneofArgType_reason: _TypeAlias = _typing.Literal["reason", b"reason"]  # noqa: Y015
    def WhichOneof(self, oneof_group: _WhichOneofArgType_reason) -> _WhichOneofReturnType_reason | None: ...

Global___Denial: _TypeAlias = Denial  # noqa: Y015

@_typing.final
class Pass(_message.Message):
    """─────────────────────────────────────────────────────────────────────
    Decision — pass-or-deny result returned from validate(). Modeled as
    a oneof so the pass case doesn't need a sentinel Denial value.
    ─────────────────────────────────────────────────────────────────────
    """

    DESCRIPTOR: _descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

Global___Pass: _TypeAlias = Pass  # noqa: Y015

@_typing.final
class Decision(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    PASS_FIELD_NUMBER: _builtins.int
    DENY_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def deny(self) -> Global___Denial: ...
    def __init__(
        self,
        *,
        deny: Global___Denial | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["deny", b"deny", "outcome", b"outcome", "pass", b"pass"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["deny", b"deny", "outcome", b"outcome", "pass", b"pass"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType_outcome: _TypeAlias = _typing.Literal["pass", "deny"]  # noqa: Y015
    _WhichOneofArgType_outcome: _TypeAlias = _typing.Literal["outcome", b"outcome"]  # noqa: Y015
    def WhichOneof(self, oneof_group: _WhichOneofArgType_outcome) -> _WhichOneofReturnType_outcome | None: ...

Global___Decision: _TypeAlias = Decision  # noqa: Y015

@_typing.final
class AuditEntry(_message.Message):
    """─────────────────────────────────────────────────────────────────────
    AuditEntry — NEW in v1. Tamper-evident chain record for the
    Paranoia audit loop (v1.6 §4.4). Every validate() call — pass
    OR deny — produces one of these. Chain linkage is via prev_hash
    (blake3 of the previous entry's canonical bytes) + this_hash
    (blake3 of this entry's bytes, excluding the this_hash field
    itself — the hash covers all OTHER fields including prev_hash).

    build_content_hash identifies the exact shield-policy build that
    ran this decision. Divergence across substrates on the same
    invocation indicates either a replay attack or a substrate
    compromise — see Phoenix Protocol §3.3.

    PROPOSAL NOTE (review callout): this shape is new in Phase A, not
    retrofitted from an existing Python/Rust type. The audit-loop PR
    that wires sec_audit to this message is Phase B follow-up work.
    ─────────────────────────────────────────────────────────────────────
    """

    DESCRIPTOR: _descriptor.Descriptor

    SEQUENCE_FIELD_NUMBER: _builtins.int
    PREV_HASH_FIELD_NUMBER: _builtins.int
    THIS_HASH_FIELD_NUMBER: _builtins.int
    EMITTED_AT_UNIX_MS_FIELD_NUMBER: _builtins.int
    SUBSTRATE_FIELD_NUMBER: _builtins.int
    BUILD_CONTENT_HASH_FIELD_NUMBER: _builtins.int
    INVOCATION_FIELD_NUMBER: _builtins.int
    DECISION_FIELD_NUMBER: _builtins.int
    sequence: _builtins.int
    """Chain linkage
    monotonic per-chain counter
    """
    prev_hash: _builtins.bytes
    """blake3 of prior entry bytes (empty for genesis)"""
    this_hash: _builtins.bytes
    """blake3 of all OTHER fields in this message"""
    emitted_at_unix_ms: _builtins.int
    """Decision record"""
    substrate: Global___Substrate.ValueType
    build_content_hash: _builtins.bytes
    """shield-policy artifact hash that ran validate()"""
    @_builtins.property
    def invocation(self) -> Global___Invocation: ...
    @_builtins.property
    def decision(self) -> Global___Decision: ...
    def __init__(
        self,
        *,
        sequence: _builtins.int = ...,
        prev_hash: _builtins.bytes = ...,
        this_hash: _builtins.bytes = ...,
        emitted_at_unix_ms: _builtins.int = ...,
        substrate: Global___Substrate.ValueType = ...,
        build_content_hash: _builtins.bytes = ...,
        invocation: Global___Invocation | None = ...,
        decision: Global___Decision | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["decision", b"decision", "invocation", b"invocation"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["build_content_hash", b"build_content_hash", "decision", b"decision", "emitted_at_unix_ms", b"emitted_at_unix_ms", "invocation", b"invocation", "prev_hash", b"prev_hash", "sequence", b"sequence", "substrate", b"substrate", "this_hash", b"this_hash"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___AuditEntry: _TypeAlias = AuditEntry  # noqa: Y015
