/**
 * Project Scaffolder — File Manifest Generator for A.I.M.S.
 *
 * Consumes a ProjectSpec (from the Template Library or custom intake) and
 * produces a complete ScaffoldResult containing every file the new project
 * needs: pages, API routes, DB models, configs, Docker, README, and more.
 *
 * Engineer_Ang invokes the Scaffolder after ORACLE gate-checks pass.
 * The output is handed to the build pipeline for compilation and deployment.
 *
 * — by: ACHIEVEMOR
 */

import logger from '../logger';
import { ProjectSpec } from '../db';

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

export type ScaffoldedFileType =
  | 'page'
  | 'component'
  | 'api'
  | 'model'
  | 'config'
  | 'style'
  | 'test'
  | 'util';

export interface ScaffoldedFile {
  path: string;
  content: string;
  type: ScaffoldedFileType;
  description: string;
}

export interface ScaffoldResult {
  projectName: string;
  totalFiles: number;
  files: ScaffoldedFile[];
  techStack: { frontend: string; backend: string; database: string };
  dockerConfig: string;
  envTemplate: string;
  readmeContent: string;
}

export interface BrandingOptions {
  primaryColor: string;
  logo?: string;
}

// Re-export ProjectSpec for consumers that import only from scaffolder
export type { ProjectSpec };

// ---------------------------------------------------------------------------
// Helpers — File Content Generators
// ---------------------------------------------------------------------------

function toTitleCase(slug: string): string {
  return slug
    .split(/[-_]/)
    .map(w => w.charAt(0).toUpperCase() + w.slice(1))
    .join(' ');
}

function toPascalCase(slug: string): string {
  return slug
    .split(/[-_]/)
    .map(w => w.charAt(0).toUpperCase() + w.slice(1))
    .join('');
}

function toCamelCase(slug: string): string {
  const pascal = toPascalCase(slug);
  return pascal.charAt(0).toLowerCase() + pascal.slice(1);
}

// ---------------------------------------------------------------------------
// Page Generator
// ---------------------------------------------------------------------------

function generatePage(pageName: string, projectName: string): ScaffoldedFile {
  const pascal = toPascalCase(pageName);
  const title = toTitleCase(pageName);
  const route = pageName === 'home' ? '' : pageName;

  const content = `// Auto-generated by A.I.M.S. Scaffolder — by: ACHIEVEMOR
import React from 'react';

export const metadata = {
  title: '${title} | ${toTitleCase(projectName)}',
  description: '${title} page for ${toTitleCase(projectName)}',
};

export default function ${pascal}Page() {
  return (
    <div className="min-h-screen bg-gray-50 p-8">
      <header className="mb-8">
        <h1 className="text-3xl font-bold text-gray-900">${title}</h1>
        <p className="mt-2 text-gray-600">
          Welcome to the ${title.toLowerCase()} section.
        </p>
      </header>

      <main className="mx-auto max-w-7xl">
        {/* TODO: Implement ${title.toLowerCase()} content */}
        <div className="rounded-lg border border-gray-200 bg-white p-6 shadow-sm">
          <p className="text-gray-500">
            ${title} content goes here. Built with A.I.M.S.
          </p>
        </div>
      </main>
    </div>
  );
}
`;

  return {
    path: `src/app/${route ? route + '/' : ''}page.tsx`,
    content,
    type: 'page',
    description: `${title} page component`,
  };
}

// ---------------------------------------------------------------------------
// Layout Generator
// ---------------------------------------------------------------------------

function generateLayout(projectName: string, pages: string[], branding?: BrandingOptions): ScaffoldedFile {
  const navItems = pages
    .map(p => {
      const href = p === 'home' ? '/' : `/${p}`;
      return `        <a href="${href}" className="rounded-md px-3 py-2 text-sm font-medium text-gray-700 hover:bg-gray-100 hover:text-gray-900">${toTitleCase(p)}</a>`;
    })
    .join('\n');

  const primaryColor = branding?.primaryColor ?? '#2563eb';

  const content = `// Auto-generated by A.I.M.S. Scaffolder — by: ACHIEVEMOR
import React from 'react';
import type { Metadata } from 'next';
import './globals.css';

export const metadata: Metadata = {
  title: '${toTitleCase(projectName)}',
  description: '${toTitleCase(projectName)} — built with A.I.M.S. by ACHIEVEMOR',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className="min-h-screen bg-gray-50 antialiased">
        {/* Navigation */}
        <nav className="border-b border-gray-200 bg-white shadow-sm">
          <div className="mx-auto flex max-w-7xl items-center justify-between px-4 py-3">
            <a href="/" className="text-xl font-bold" style={{ color: '${primaryColor}' }}>
              ${toTitleCase(projectName)}
            </a>
            <div className="flex items-center space-x-1">
${navItems}
            </div>
          </div>
        </nav>

        {/* Page Content */}
        <main>{children}</main>

        {/* Footer */}
        <footer className="mt-auto border-t border-gray-200 bg-white py-6 text-center text-sm text-gray-500">
          &copy; {new Date().getFullYear()} ${toTitleCase(projectName)}. Built with A.I.M.S. by ACHIEVEMOR.
        </footer>
      </body>
    </html>
  );
}
`;

  return {
    path: 'src/app/layout.tsx',
    content,
    type: 'page',
    description: 'Root layout with navigation and footer',
  };
}

// ---------------------------------------------------------------------------
// Global Styles Generator
// ---------------------------------------------------------------------------

function generateGlobalCSS(branding?: BrandingOptions): ScaffoldedFile {
  const primaryColor = branding?.primaryColor ?? '#2563eb';

  const content = `/* Auto-generated by A.I.M.S. Scaffolder — by: ACHIEVEMOR */
@tailwind base;
@tailwind components;
@tailwind utilities;

:root {
  --color-primary: ${primaryColor};
  --color-bg: #f9fafb;
  --color-surface: #ffffff;
  --color-text: #111827;
  --color-text-muted: #6b7280;
  --color-border: #e5e7eb;
}

body {
  color: var(--color-text);
  background-color: var(--color-bg);
}

/* Utility: focus ring */
.focus-ring {
  @apply focus:outline-none focus:ring-2 focus:ring-offset-2;
  --tw-ring-color: var(--color-primary);
}
`;

  return {
    path: 'src/app/globals.css',
    content,
    type: 'style',
    description: 'Global CSS with Tailwind directives and CSS variables',
  };
}

// ---------------------------------------------------------------------------
// Tailwind Config Generator
// ---------------------------------------------------------------------------

function generateTailwindConfig(branding?: BrandingOptions): ScaffoldedFile {
  const primaryColor = branding?.primaryColor ?? '#2563eb';

  const content = `// Auto-generated by A.I.M.S. Scaffolder — by: ACHIEVEMOR
import type { Config } from 'tailwindcss';

const config: Config = {
  content: ['./src/**/*.{js,ts,jsx,tsx,mdx}'],
  theme: {
    extend: {
      colors: {
        primary: {
          DEFAULT: '${primaryColor}',
          50: '${primaryColor}0d',
          100: '${primaryColor}1a',
          200: '${primaryColor}33',
          500: '${primaryColor}',
          600: '${primaryColor}e6',
          700: '${primaryColor}cc',
        },
      },
    },
  },
  plugins: [],
};

export default config;
`;

  return {
    path: 'tailwind.config.ts',
    content,
    type: 'config',
    description: 'Tailwind CSS configuration with branding colors',
  };
}

// ---------------------------------------------------------------------------
// API Route Generator
// ---------------------------------------------------------------------------

function generateApiRoute(route: string): ScaffoldedFile {
  // Convert /api/foo/:id -> api/foo/[id]/route.ts
  const segments = route
    .replace(/^\//, '')
    .split('/')
    .map(seg => (seg.startsWith(':') ? `[${seg.slice(1)}]` : seg));

  const filePath = `src/app/${segments.join('/')}/route.ts`;
  const routeName = toPascalCase(segments.filter(s => !s.startsWith('[') && s !== 'api').join('-'));

  const hasParam = segments.some(s => s.startsWith('['));
  const paramName = hasParam
    ? segments.find(s => s.startsWith('['))?.replace(/[[\]]/g, '') ?? 'id'
    : null;

  const paramType = paramName
    ? `\ninterface RouteParams {\n  params: { ${paramName}: string };\n}\n`
    : '';

  const getHandler = paramName
    ? `export async function GET(_req: Request, { params }: RouteParams) {
  const { ${paramName} } = params;
  // TODO: Fetch ${routeName} by ${paramName}
  return Response.json({ ${paramName}, message: '${routeName} retrieved' });
}`
    : `export async function GET() {
  // TODO: Fetch ${routeName} list
  return Response.json({ data: [], message: '${routeName} list retrieved' });
}`;

  const postHandler = paramName
    ? ''
    : `

export async function POST(req: Request) {
  const body = await req.json();
  // TODO: Create ${routeName}
  return Response.json({ data: body, message: '${routeName} created' }, { status: 201 });
}`;

  const content = `// Auto-generated by A.I.M.S. Scaffolder — by: ACHIEVEMOR
${paramType}
${getHandler}${postHandler}
`;

  return {
    path: filePath,
    content,
    type: 'api',
    description: `API route handler for ${route}`,
  };
}

// ---------------------------------------------------------------------------
// DB Model Generator
// ---------------------------------------------------------------------------

function generateDbModel(modelName: string, database: string): ScaffoldedFile {
  const pascal = toPascalCase(modelName);
  const camel = toCamelCase(modelName);
  const tableName = modelName.toLowerCase().replace(/([a-z])([A-Z])/g, '$1_$2').toLowerCase() + 's';

  const content = `// Auto-generated by A.I.M.S. Scaffolder — by: ACHIEVEMOR

export interface ${pascal} {
  id: string;
  createdAt: Date;
  updatedAt: Date;
  // TODO: Add ${pascal}-specific fields
}

export interface Create${pascal}Input {
  // TODO: Define creation fields for ${pascal}
}

export interface Update${pascal}Input {
  // TODO: Define update fields for ${pascal}
}

/**
 * ${pascal} data access layer.
 * Target database: ${database}
 * Table/collection: ${tableName}
 */
export const ${camel}Repository = {
  async findAll(): Promise<${pascal}[]> {
    // TODO: Implement query against ${database}
    return [];
  },

  async findById(id: string): Promise<${pascal} | null> {
    // TODO: Implement single-record lookup
    return null;
  },

  async create(input: Create${pascal}Input): Promise<${pascal}> {
    // TODO: Implement insert into ${tableName}
    throw new Error('Not implemented');
  },

  async update(id: string, input: Update${pascal}Input): Promise<${pascal} | null> {
    // TODO: Implement update on ${tableName}
    throw new Error('Not implemented');
  },

  async delete(id: string): Promise<boolean> {
    // TODO: Implement delete from ${tableName}
    return false;
  },
};
`;

  return {
    path: `src/models/${modelName.toLowerCase().replace(/([a-z])([A-Z])/g, '$1-$2').toLowerCase()}.ts`,
    content,
    type: 'model',
    description: `Database model and repository for ${pascal}`,
  };
}

// ---------------------------------------------------------------------------
// Component Generator (shared UI components)
// ---------------------------------------------------------------------------

function generateComponents(): ScaffoldedFile[] {
  const button: ScaffoldedFile = {
    path: 'src/components/ui/button.tsx',
    content: `// Auto-generated by A.I.M.S. Scaffolder — by: ACHIEVEMOR
import React from 'react';

interface ButtonProps extends React.ButtonHTMLAttributes<HTMLButtonElement> {
  variant?: 'primary' | 'secondary' | 'outline' | 'ghost';
  size?: 'sm' | 'md' | 'lg';
}

const variantStyles: Record<string, string> = {
  primary: 'bg-primary text-white hover:bg-primary-600 shadow-sm',
  secondary: 'bg-gray-100 text-gray-900 hover:bg-gray-200',
  outline: 'border border-gray-300 bg-white text-gray-700 hover:bg-gray-50',
  ghost: 'text-gray-700 hover:bg-gray-100',
};

const sizeStyles: Record<string, string> = {
  sm: 'px-3 py-1.5 text-sm',
  md: 'px-4 py-2 text-sm',
  lg: 'px-6 py-3 text-base',
};

export default function Button({
  variant = 'primary',
  size = 'md',
  className = '',
  children,
  ...props
}: ButtonProps) {
  return (
    <button
      className={\`inline-flex items-center justify-center rounded-md font-medium transition-colors focus-ring \${variantStyles[variant]} \${sizeStyles[size]} \${className}\`}
      {...props}
    >
      {children}
    </button>
  );
}
`,
    type: 'component',
    description: 'Reusable button component with variant and size props',
  };

  const card: ScaffoldedFile = {
    path: 'src/components/ui/card.tsx',
    content: `// Auto-generated by A.I.M.S. Scaffolder — by: ACHIEVEMOR
import React from 'react';

interface CardProps {
  title?: string;
  children: React.ReactNode;
  className?: string;
}

export default function Card({ title, children, className = '' }: CardProps) {
  return (
    <div className={\`rounded-lg border border-gray-200 bg-white p-6 shadow-sm \${className}\`}>
      {title && <h3 className="mb-4 text-lg font-semibold text-gray-900">{title}</h3>}
      {children}
    </div>
  );
}
`,
    type: 'component',
    description: 'Reusable card component',
  };

  const input: ScaffoldedFile = {
    path: 'src/components/ui/input.tsx',
    content: `// Auto-generated by A.I.M.S. Scaffolder — by: ACHIEVEMOR
import React from 'react';

interface InputProps extends React.InputHTMLAttributes<HTMLInputElement> {
  label?: string;
  error?: string;
}

export default function Input({ label, error, className = '', ...props }: InputProps) {
  return (
    <div className="space-y-1">
      {label && (
        <label className="block text-sm font-medium text-gray-700">{label}</label>
      )}
      <input
        className={\`block w-full rounded-md border px-3 py-2 text-sm shadow-sm transition-colors focus-ring \${
          error
            ? 'border-red-500 focus:ring-red-500'
            : 'border-gray-300 focus:border-primary focus:ring-primary'
        } \${className}\`}
        {...props}
      />
      {error && <p className="text-sm text-red-600">{error}</p>}
    </div>
  );
}
`,
    type: 'component',
    description: 'Reusable input component with label and error state',
  };

  return [button, card, input];
}

// ---------------------------------------------------------------------------
// Config Files Generator
// ---------------------------------------------------------------------------

function generateNextConfig(): ScaffoldedFile {
  return {
    path: 'next.config.js',
    content: `// Auto-generated by A.I.M.S. Scaffolder — by: ACHIEVEMOR
/** @type {import('next').NextConfig} */
const nextConfig = {
  reactStrictMode: true,
  experimental: {
    serverActions: true,
  },
};

module.exports = nextConfig;
`,
    type: 'config',
    description: 'Next.js configuration',
  };
}

function generateTsConfig(): ScaffoldedFile {
  return {
    path: 'tsconfig.json',
    content: `{
  "compilerOptions": {
    "target": "es2017",
    "lib": ["dom", "dom.iterable", "esnext"],
    "allowJs": true,
    "skipLibCheck": true,
    "strict": true,
    "noEmit": true,
    "esModuleInterop": true,
    "module": "esnext",
    "moduleResolution": "bundler",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "jsx": "preserve",
    "incremental": true,
    "plugins": [{ "name": "next" }],
    "paths": { "@/*": ["./src/*"] }
  },
  "include": ["next-env.d.ts", "**/*.ts", "**/*.tsx", ".next/types/**/*.ts"],
  "exclude": ["node_modules"]
}
`,
    type: 'config',
    description: 'TypeScript configuration for Next.js',
  };
}

function generatePackageJson(projectName: string): ScaffoldedFile {
  return {
    path: 'package.json',
    content: JSON.stringify(
      {
        name: projectName,
        version: '0.1.0',
        private: true,
        scripts: {
          dev: 'next dev',
          build: 'next build',
          start: 'next start',
          lint: 'next lint',
        },
        dependencies: {
          next: '^14.0.0',
          react: '^18.2.0',
          'react-dom': '^18.2.0',
        },
        devDependencies: {
          '@types/node': '^20.0.0',
          '@types/react': '^18.2.0',
          '@types/react-dom': '^18.2.0',
          autoprefixer: '^10.4.0',
          postcss: '^8.4.0',
          tailwindcss: '^3.4.0',
          typescript: '^5.3.0',
        },
      },
      null,
      2
    ) + '\n',
    type: 'config',
    description: 'Project package.json with Next.js dependencies',
  };
}

function generatePostcssConfig(): ScaffoldedFile {
  return {
    path: 'postcss.config.js',
    content: `// Auto-generated by A.I.M.S. Scaffolder — by: ACHIEVEMOR
module.exports = {
  plugins: {
    tailwindcss: {},
    autoprefixer: {},
  },
};
`,
    type: 'config',
    description: 'PostCSS configuration for Tailwind',
  };
}

function generateGitignore(): ScaffoldedFile {
  return {
    path: '.gitignore',
    content: `# Dependencies
node_modules/

# Next.js
.next/
out/

# Build
dist/
build/

# Environment
.env
.env.local
.env.*.local
!.env.example

# IDE
.vscode/
.idea/

# OS
.DS_Store
Thumbs.db

# Debug
npm-debug.log*
yarn-debug.log*

# Testing
coverage/
`,
    type: 'config',
    description: 'Git ignore rules',
  };
}

// ---------------------------------------------------------------------------
// Docker & Environment Generators
// ---------------------------------------------------------------------------

function generateDockerfile(_projectName: string): string {
  return `# Auto-generated by A.I.M.S. Scaffolder — by: ACHIEVEMOR
# ----- Stage 1: Dependencies -----
FROM node:20-alpine AS deps
WORKDIR /app
COPY package.json package-lock.json* ./
RUN npm ci --only=production

# ----- Stage 2: Build -----
FROM node:20-alpine AS builder
WORKDIR /app
COPY --from=deps /app/node_modules ./node_modules
COPY . .
RUN npm run build

# ----- Stage 3: Production -----
FROM node:20-alpine AS runner
WORKDIR /app
ENV NODE_ENV=production

RUN addgroup --system --gid 1001 nodejs \\
 && adduser  --system --uid 1001 nextjs

COPY --from=builder /app/public         ./public
COPY --from=builder /app/.next/standalone ./
COPY --from=builder /app/.next/static   ./.next/static

USER nextjs
EXPOSE 3000
ENV PORT=3000
CMD ["node", "server.js"]
`;
}

function generateDockerCompose(projectName: string, database: string): string {
  const dbService =
    database.toLowerCase() === 'postgresql'
      ? `
  db:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: \${DB_USER:-aims}
      POSTGRES_PASSWORD: \${DB_PASSWORD:-aims_secret}
      POSTGRES_DB: \${DB_NAME:-${projectName.replace(/-/g, '_')}}
    ports:
      - "\${DB_PORT:-5432}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:`
      : '';

  return `# Auto-generated by A.I.M.S. Scaffolder — by: ACHIEVEMOR
version: "3.9"

services:
  app:
    build: .
    restart: unless-stopped
    ports:
      - "\${APP_PORT:-3000}:3000"
    env_file:
      - .env
    depends_on:${database.toLowerCase() === 'postgresql' ? '\n      - db' : ' []'}
${dbService}
`;
}

function generateEnvTemplate(database: string): string {
  const dbVars =
    database.toLowerCase() === 'postgresql'
      ? `
# Database (PostgreSQL)
DB_HOST=localhost
DB_PORT=5432
DB_USER=aims
DB_PASSWORD=aims_secret
DB_NAME=aims_app
DATABASE_URL=postgresql://\${DB_USER}:\${DB_PASSWORD}@\${DB_HOST}:\${DB_PORT}/\${DB_NAME}
`
      : `
# Database (SQLite)
DATABASE_URL=file:./data/app.db
`;

  return `# Auto-generated by A.I.M.S. Scaffolder — by: ACHIEVEMOR
# Copy this file to .env and fill in real values.

# Application
NODE_ENV=development
APP_PORT=3000
NEXT_PUBLIC_APP_URL=http://localhost:3000
${dbVars}
# Authentication (if applicable)
AUTH_SECRET=change-me-to-a-random-string
# GOOGLE_CLIENT_ID=
# GOOGLE_CLIENT_SECRET=

# Email (if applicable)
# SENDGRID_API_KEY=

# Payments (if applicable)
# STRIPE_SECRET_KEY=
# STRIPE_WEBHOOK_SECRET=
# NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY=
`;
}

function generateReadme(
  projectName: string,
  spec: ProjectSpec,
  totalFiles: number
): string {
  const title = toTitleCase(projectName);
  const pages = spec.pages.map(p => `- \`/${p === 'home' ? '' : p}\` — ${toTitleCase(p)}`).join('\n');
  const routes = spec.apiRoutes.map(r => `- \`${r}\``).join('\n');

  return `# ${title}

> Built with **A.I.M.S.** — by: ACHIEVEMOR

## Overview

| Attribute | Value |
|-----------|-------|
| Archetype | ${spec.archetype} |
| Frontend  | ${spec.techStack.frontend} |
| Backend   | ${spec.techStack.backend} |
| Database  | ${spec.techStack.database} |
| Files     | ${totalFiles} |

## Pages

${pages}

## API Routes

${routes}

## Getting Started

\`\`\`bash
# Install dependencies
npm install

# Start development server
npm run dev

# Build for production
npm run build
npm start
\`\`\`

## Docker

\`\`\`bash
# Build and run with Docker Compose
docker compose up --build
\`\`\`

## Environment Variables

Copy \`.env.example\` to \`.env\` and configure:

\`\`\`bash
cp .env.example .env
\`\`\`

---

*Scaffolded by A.I.M.S. Plug Builder — by: ACHIEVEMOR*
`;
}

// ---------------------------------------------------------------------------
// Test Generator
// ---------------------------------------------------------------------------

function generateExampleTest(projectName: string): ScaffoldedFile {
  return {
    path: 'src/__tests__/home.test.tsx',
    content: `// Auto-generated by A.I.M.S. Scaffolder — by: ACHIEVEMOR
import { describe, it, expect } from '@jest/globals';

describe('${toTitleCase(projectName)} — Home Page', () => {
  it('should be defined', () => {
    expect(true).toBe(true);
  });

  // TODO: Add rendering and integration tests
});
`,
    type: 'test',
    description: 'Example test file for the home page',
  };
}

// ---------------------------------------------------------------------------
// Project Scaffolder
// ---------------------------------------------------------------------------

export class ProjectScaffolder {
  constructor() {
    logger.info('[Scaffolder] ProjectScaffolder initialized');
  }

  /**
   * Generate a complete file manifest for a project.
   *
   * @param spec       - The ProjectSpec describing pages, routes, models, etc.
   * @param projectName - Slug-friendly project name (e.g., "my-saas-app")
   * @param branding   - Optional branding overrides (colors, logo)
   * @returns A ScaffoldResult with every file the project needs.
   */
  scaffold(
    spec: ProjectSpec,
    projectName: string,
    branding?: BrandingOptions
  ): ScaffoldResult {
    logger.info(
      {
        projectName,
        archetype: spec.archetype,
        pages: spec.pages.length,
        apiRoutes: spec.apiRoutes.length,
        dbModels: spec.dbModels.length,
      },
      '[Scaffolder] Beginning scaffold'
    );

    const files: ScaffoldedFile[] = [];

    // ---- Pages ----
    for (const page of spec.pages) {
      files.push(generatePage(page, projectName));
    }

    // ---- Layout & Global Styles ----
    files.push(generateLayout(projectName, spec.pages, branding));
    files.push(generateGlobalCSS(branding));

    // ---- API Routes ----
    for (const route of spec.apiRoutes) {
      files.push(generateApiRoute(route));
    }

    // ---- DB Models ----
    for (const model of spec.dbModels) {
      files.push(generateDbModel(model, spec.techStack.database));
    }

    // ---- Shared UI Components ----
    files.push(...generateComponents());

    // ---- Config Files ----
    files.push(generateTailwindConfig(branding));
    files.push(generateNextConfig());
    files.push(generateTsConfig());
    files.push(generatePackageJson(projectName));
    files.push(generatePostcssConfig());
    files.push(generateGitignore());

    // ---- Test Stub ----
    files.push(generateExampleTest(projectName));

    // ---- Infrastructure ----
    const dockerConfig = generateDockerfile(projectName);
    const dockerComposeContent = generateDockerCompose(projectName, spec.techStack.database);
    const envTemplate = generateEnvTemplate(spec.techStack.database);
    const readmeContent = generateReadme(projectName, spec, files.length);

    // Add Dockerfile and docker-compose as files in the manifest
    files.push({
      path: 'Dockerfile',
      content: dockerConfig,
      type: 'config',
      description: 'Multi-stage Docker build for production',
    });
    files.push({
      path: 'docker-compose.yml',
      content: dockerComposeContent,
      type: 'config',
      description: 'Docker Compose service definitions',
    });
    files.push({
      path: '.env.example',
      content: envTemplate,
      type: 'config',
      description: 'Environment variable template',
    });
    files.push({
      path: 'README.md',
      content: readmeContent,
      type: 'config',
      description: 'Project README with setup instructions',
    });

    const result: ScaffoldResult = {
      projectName,
      totalFiles: files.length,
      files,
      techStack: { ...spec.techStack },
      dockerConfig,
      envTemplate,
      readmeContent,
    };

    logger.info(
      { projectName, totalFiles: result.totalFiles },
      '[Scaffolder] Scaffold complete'
    );

    return result;
  }
}

// ---------------------------------------------------------------------------
// Singleton
// ---------------------------------------------------------------------------

export const scaffolder = new ProjectScaffolder();
