//! ZKP-TS — Zero-Knowledge Threat Sharing (v1.6 §3.2 / P2 #8)
//!
//! Enables global threat intelligence across tenants WITHOUT leaking
//! tenant-specific data. When a threat is detected in Tenant A,
//! Privacy (Lil_Seal_Hawk) generates a Zero-Knowledge Proof capturing
//! the attack pattern signature — shared across the Shield Division —
//! while the underlying tenant identity, data, and business context
//! stay local.
//!
//! Ownership per v1.6 §3.2:
//!   - Generator: Privacy (Lil_Seal_Hawk) — constructs ZKPs at tenant edge
//!   - Curator:   Oracle (Lil_Omen_Hawk) — maintains threat-intel library
//!   - Distributor: Mirror (Lil_Veil_Hawk) — broadcasts across tenants
//!   - Translator: Tuner (Lil_Chord_Hawk) — converts signatures into
//!                 Sigma/YARA detection rules for Blue Squad
//!
//! Structural guarantee (the v1.6 §3.2 property):
//!   Every ZKP captures the attack pattern WITHOUT revealing:
//!     - which tenant was attacked
//!     - what specific data was targeted
//!     - exact IPs / accounts / resources
//!     - PII / PHI / business-sensitive information
//!
//! The `ThreatSignature` type enforces this STRUCTURALLY — it
//! carries only category/fingerprint/effectiveness fields. There is
//! no field for tenant ID, no field for raw data, no field that
//! could carry identifying information. If a future contributor
//! tries to add one, the type change is visible in code review.

// ─── closed vocabularies ──────────────────────────────────────────

/// IoC category tags — bounded enum. No free-text means no data
/// leakage via string content.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum IocCategory {
    NetworkSignature,
    FileHashPattern,
    BehavioralPattern,
    AuthAnomalyPattern,
    ProcessChainPattern,
    RegistryPattern,
    C2CommunicationPattern,
}

/// ATT&CK technique identifier, as a bounded integer (1..=1000
/// covers the current catalog with room). The integer is the
/// MITRE ATT&CK Tn number; no tenant context is encoded.
pub type AttackTechniqueId = u16;

// ─── the structural guarantee: ThreatSignature carries NO tenant-
//     identifying fields ────────────────────────────────────────────

/// What a ZKP shares across tenants. Every field is categorical or
/// fingerprint-shaped — no field carries raw data, no field carries
/// a tenant identifier, no field carries an IP/account/account-like
/// string.
///
/// **Structural guarantee:** this struct has NO member that can hold
/// tenant-identifying content. Adding one requires editing this type
/// and passing code review. The v1.6 §3.2 "global intel, local
/// privacy" property is enforced at the type boundary.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct ThreatSignature {
    /// Hash of the network-pattern fingerprint (OWASP pattern ID,
    /// port, UA-pattern, etc. hashed together). Categorical tag, not
    /// raw content.
    pub technique_fingerprint_hash: u64,

    /// MITRE ATT&CK technique identifier. Categorical.
    pub attack_technique_id: AttackTechniqueId,

    /// Bounded IoC categories observed. Bounded-length array; no
    /// open-ended string content.
    pub ioc_categories: [IocCategory; 4],

    /// Count of IoC categories actually observed (0..=4 — the rest
    /// of the array is padded with a default variant).
    pub ioc_count: u8,

    /// Did existing Shield controls mitigate? Single bit. No data
    /// about what the controls were or what the target was.
    pub mitigation_effective: bool,
}

// ─── ZKP proof envelope ───────────────────────────────────────────

/// The cryptographic proof envelope. Verifying Hawks see this; they
/// do not see the ThreatSignature directly without running the
/// verifier.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct ZkpProof {
    /// Hash of the statement the proof witnesses. In production this
    /// is a zk-SNARK or zk-STARK proof byte-blob; modeled as u64
    /// here for Kani tractability.
    pub statement_hash: u64,

    /// Whether the embedded proof verifies cryptographically.
    /// Populated at verification time by the verifier Hawk
    /// (typically Tuner via Sigma/YARA rule generation).
    pub proof_verifies: bool,

    /// Whether this proof was generated by a tenant-edge Privacy
    /// instance with the redaction pipeline active. If false, the
    /// emission is REFUSED — ZKPs must only originate from
    /// redaction-applied contexts.
    pub redaction_pipeline_active: bool,
}

// ─── emission + verification ──────────────────────────────────────

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum EmissionDecision {
    /// ZKP is approved for cross-tenant broadcast.
    Approved,
    /// Redaction pipeline was not active when the proof was
    /// generated; emission refused. This prevents ZKPs from being
    /// built from non-redacted data that might leak via proof-
    /// construction side channels.
    RedactionPipelineInactive,
    /// The cryptographic proof doesn't verify — likely tampering or
    /// misconfigured generator; refused.
    ProofDoesNotVerify,
}

/// Privacy emits a ZKP. Returns Approved iff the proof verifies AND
/// the redaction pipeline was active during generation.
///
/// The ThreatSignature parameter is what would be WITNESSED by the
/// proof; the emission doesn't carry the signature directly —
/// downstream tenants see only the ZkpProof envelope.
pub fn authorize_emission(proof: &ZkpProof) -> EmissionDecision {
    if !proof.redaction_pipeline_active {
        return EmissionDecision::RedactionPipelineInactive;
    }
    if !proof.proof_verifies {
        return EmissionDecision::ProofDoesNotVerify;
    }
    EmissionDecision::Approved
}

/// Tuner translates a verified ZKP statement into a detection rule.
/// Returns Some(rule_key) iff the proof was approved for emission.
/// The rule_key is the ATT&CK technique id plus fingerprint hash —
/// no tenant context.
pub fn derive_detection_rule_key(
    proof: &ZkpProof,
    signature: &ThreatSignature,
) -> Option<(AttackTechniqueId, u64)> {
    match authorize_emission(proof) {
        EmissionDecision::Approved => Some((
            signature.attack_technique_id,
            signature.technique_fingerprint_hash,
        )),
        _ => None,
    }
}

// ─── the tenant-leakage invariant (expressed as a function) ──────

/// Returns true iff the ThreatSignature structurally COULD contain
/// tenant-identifying data. Because ThreatSignature's fields are all
/// categorical / fingerprint-shaped, this is ALWAYS false —
/// invariant holds by type construction.
///
/// Defined as a function so Kani can discharge the biconditional as
/// a proof obligation: `!could_leak_tenant(sig)` for all `sig`.
pub fn could_leak_tenant(_sig: &ThreatSignature) -> bool {
    // The ThreatSignature struct has NO field that can carry a
    // tenant identifier. This predicate returns constant false by
    // construction. If a contributor adds a tenant-identifying
    // field to ThreatSignature, they must ALSO edit this function
    // to reflect that — which is itself caught in code review.
    false
}

// ─── tests ────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;

    fn signature() -> ThreatSignature {
        ThreatSignature {
            technique_fingerprint_hash: 0x1234,
            attack_technique_id: 1059,        // T1059 Command + Scripting Interpreter
            ioc_categories: [
                IocCategory::NetworkSignature,
                IocCategory::BehavioralPattern,
                IocCategory::C2CommunicationPattern,
                IocCategory::ProcessChainPattern,
            ],
            ioc_count: 4,
            mitigation_effective: true,
        }
    }

    fn valid_proof() -> ZkpProof {
        ZkpProof {
            statement_hash: 0xDEADBEEF,
            proof_verifies: true,
            redaction_pipeline_active: true,
        }
    }

    #[test]
    fn valid_proof_authorized_for_emission() {
        assert_eq!(
            authorize_emission(&valid_proof()),
            EmissionDecision::Approved
        );
    }

    #[test]
    fn redaction_pipeline_inactive_refuses() {
        let mut p = valid_proof();
        p.redaction_pipeline_active = false;
        assert_eq!(
            authorize_emission(&p),
            EmissionDecision::RedactionPipelineInactive
        );
    }

    #[test]
    fn proof_that_does_not_verify_refused() {
        let mut p = valid_proof();
        p.proof_verifies = false;
        assert_eq!(
            authorize_emission(&p),
            EmissionDecision::ProofDoesNotVerify
        );
    }

    #[test]
    fn detection_rule_key_derives_from_approved_proof() {
        let k = derive_detection_rule_key(&valid_proof(), &signature());
        assert_eq!(k, Some((1059, 0x1234)));
    }

    #[test]
    fn detection_rule_key_none_when_refused() {
        let mut p = valid_proof();
        p.redaction_pipeline_active = false;
        assert_eq!(derive_detection_rule_key(&p, &signature()), None);
    }

    #[test]
    fn threat_signature_cannot_leak_tenant_by_construction() {
        // No input signature yields true; the type has no tenant-
        // identifying fields.
        assert!(!could_leak_tenant(&signature()));
    }
}
