export interface Prospect {
  name: string;
  school: string;
  position: string;
  height: string | null;
  weight: string | null;
  classYear: string;
  overallRank: number;
  positionRank: number;
  projectedRound: number;
  grade: number;
  tieGrade: string;
  tieTier: string;
  trend: string;
  scoutingSummary: string;
  strengths: string;
  weaknesses: string;
  nflComparison: string;
  filmGrade: string;
  analystNotes: string;
}

/**
 * 2026 NFL Draft Big Board — 50 real prospects from Per|Form research.
 * Position ranks are computed by order within each position group.
 */

// Helper to compute position ranks
function assignPositionRanks(prospects: Omit<Prospect, 'positionRank'>[]): Prospect[] {
  const posCount: Record<string, number> = {};
  return prospects.map((p) => {
    const pos = p.position.split('/')[0]; // use primary position for ranking
    posCount[pos] = (posCount[pos] || 0) + 1;
    return { ...p, positionRank: posCount[pos] };
  });
}

function gradeToTieGrade(grade: number): string {
  if (grade >= 93) return 'Blue Chip';
  if (grade >= 88) return 'First Round Lock';
  if (grade >= 83) return 'Day 1 Starter';
  if (grade >= 80) return 'Solid Starter';
  if (grade >= 77) return 'Quality Starter';
  if (grade >= 75) return 'Rotational Player';
  return 'Developmental';
}

function gradeToTieTier(grade: number): string {
  if (grade >= 93) return 'Tier 1';
  if (grade >= 88) return 'Tier 2';
  if (grade >= 83) return 'Tier 3';
  if (grade >= 80) return 'Tier 4';
  if (grade >= 77) return 'Tier 5';
  if (grade >= 75) return 'Tier 6';
  return 'Tier 7';
}

const RAW_BOARD: Omit<Prospect, 'positionRank'>[] = [
  { name: 'Jeremiyah Love', school: 'Notre Dame', position: 'RB', height: '6-0', weight: '212', classYear: '2026', overallRank: 1, projectedRound: 1, grade: 93, tieGrade: gradeToTieGrade(93), tieTier: gradeToTieTier(93), trend: 'rising', scoutingSummary: 'Consensus #1 overall. Rare combination of speed, hands, and ball security. Three-down back from Day 1. Zero fumbles in 3 years is a superpower.', strengths: 'Speed 10/10; Ball security 10/10; Vision 9.5; Receiving 9.5; Contact balance 9.5', weaknesses: 'Durability 8.5; shared backfield usage', nflComparison: 'Jahmyr Gibbs', filmGrade: 'A+', analystNotes: '~7.0 YPC, 10.4 YPC as receiver, 0 fumbles in 3 seasons, 4.36 40' },
  { name: 'Fernando Mendoza', school: 'Indiana', position: 'QB', height: '6-5', weight: '236', classYear: '2026', overallRank: 2, projectedRound: 1, grade: 91, tieGrade: gradeToTieGrade(91), tieTier: gradeToTieTier(91), trend: 'rising', scoutingSummary: 'Cleanest QB prospect in the class. Elite size, accuracy, and decision-making. Proven winner with no red flags. Plug-and-play franchise QB.', strengths: 'Size/frame 9.5; Accuracy 9.5; Decision-making 9.5; Leadership 9.5; Clutch 9.5', weaknesses: 'Pocket presence 8.5; RPO-heavy system', nflComparison: 'Matt Ryan', filmGrade: 'A+', analystNotes: '73% completion (3rd FBS), 27 TD / 0 INT red zone, Heisman Winner' },
  { name: 'Sonny Styles', school: 'Ohio State', position: 'LB', height: '6-5', weight: '244', classYear: '2026', overallRank: 3, projectedRound: 1, grade: 90, tieGrade: gradeToTieGrade(90), tieTier: gradeToTieTier(90), trend: 'steady', scoutingSummary: 'Cleanest LB prospect in years. Former safety with LB size and elite athleticism. Day 1 starter and defensive leader.', strengths: 'Size/length 9.5; Athleticism 9.5; Coverage 9.5; Work ethic 9.5; Football IQ 9.0', weaknesses: 'Pass rush 8.5', nflComparison: 'Fred Warner', filmGrade: 'A+', analystNotes: '2 missed tackles (down from 17), 43.5" vertical, 6 sacks in 2024' },
  { name: 'Caleb Downs', school: 'Ohio State', position: 'S', height: '6-0', weight: '206', classYear: '2026', overallRank: 4, projectedRound: 1, grade: 89, tieGrade: gradeToTieGrade(89), tieTier: gradeToTieTier(89), trend: 'steady', scoutingSummary: 'Instinctive, versatile safety who elevates everyone. Makes up for average measurables with elite IQ. Plug-and-play starter.', strengths: 'Coverage 9.0; Versatility 9.0; Football IQ 9.5; Leadership 9.5; Character 9.5', weaknesses: 'Athleticism 7.5', nflComparison: 'Jessie Bates III', filmGrade: 'A', analystNotes: '2+ INT in 3 straight seasons, Thorpe + Lott IMPACT winner' },
  { name: 'Rueben Bain Jr.', school: 'Miami', position: 'EDGE', height: '6-2', weight: '263', classYear: '2026', overallRank: 5, projectedRound: 1, grade: 89, tieGrade: gradeToTieGrade(89), tieTier: gradeToTieTier(89), trend: 'steady', scoutingSummary: 'Dominant despite lacking ideal measurables. Elite technician with a non-stop motor. Teams may break the arm-length trend for his production.', strengths: 'Production 9.0; Pass rush plan 9.5; Motor 9.5; Toughness 9.5; Work ethic 9.5', weaknesses: 'Length 7.0; Run defense 8.5', nflComparison: 'Trent Cole', filmGrade: 'A', analystNotes: '9.5 sacks, ACC Defensive POY, 9 run stops, sub-31" arms' },
  { name: 'Olaivavega Ioane', school: 'Penn State', position: 'OG', height: '6-4', weight: '320', classYear: '2026', overallRank: 6, projectedRound: 1, grade: 89, tieGrade: gradeToTieGrade(89), tieTier: gradeToTieTier(89), trend: 'steady', scoutingSummary: 'Plug-and-play starter from Day 1. Highest-floor offensive lineman in the class. Instant upgrade to any OL room. Pro Bowl potential.', strengths: 'Pass protection 9.5; Power 9.0; Awareness 9.0; Reliability 9.5; Football IQ 9.0', weaknesses: 'Athleticism 7.5', nflComparison: 'Quenton Nelson (lite)', filmGrade: 'A', analystNotes: '0 sacks allowed in 2 seasons, 27 starts, 5 positions played' },
  { name: 'David Bailey', school: 'Texas Tech', position: 'EDGE', height: '6-4', weight: '251', classYear: '2026', overallRank: 7, projectedRound: 1, grade: 88, tieGrade: gradeToTieGrade(88), tieTier: gradeToTieTier(88), trend: 'rising', scoutingSummary: 'Elite pass-rush production with rare burst and bend. First-round lock. Needs to develop power element and run defense.', strengths: 'Get-off 9.5; Bend 9.5; Production 9.5; Hand usage 9.0; Motor 8.5', weaknesses: 'Run defense 8.0; Power element developing', nflComparison: 'Brian Burns', filmGrade: 'A', analystNotes: '14.5 sacks (tied FBS lead), 71 pressures, 3 forced fumbles' },
  { name: 'Makai Lemon', school: 'USC', position: 'WR', height: '5-11', weight: '192', classYear: '2026', overallRank: 8, projectedRound: 1, grade: 86, tieGrade: gradeToTieGrade(86), tieTier: gradeToTieTier(86), trend: 'steady', scoutingSummary: 'Elite slot receiver with vice-grip hands. Creates separation with technique, not speed. Contested catch ability despite size. Immediate NFL starter.', strengths: 'Hands 9.5; Route running 9.0; Contested catches 8.5; Competitiveness 9.5; Consistency 9.0', weaknesses: 'Size 7.0; Speed 7.5', nflComparison: 'Amon-Ra St. Brown', filmGrade: 'A', analystNotes: '79 receptions, 1,156 yards, 11 TD, 1 drop, 20 contested catches (2 seasons)' },
  { name: 'Carnell Tate', school: 'Ohio State', position: 'WR', height: '6-2', weight: '192', classYear: '2026', overallRank: 9, projectedRound: 1, grade: 86, tieGrade: gradeToTieGrade(86), tieTier: gradeToTieTier(86), trend: 'steady', scoutingSummary: 'Reliable possession receiver with elite hands. Not a burner but creates separation with size and technique. Immediate red-zone threat.', strengths: 'Hands 9.5; Contested catches 9.0; Consistency 9.0; Route running 8.5; Size 8.5', weaknesses: 'YAC 7.5; Speed 8.0 (4.53 40)', nflComparison: 'Tee Higgins', filmGrade: 'A', analystNotes: '79.5 YPG, 9 TD, 17.2 YPR, 1 drop, 10 contested catches, 10.25" hands' },
  { name: 'Mansoor Delane', school: 'LSU', position: 'CB', height: '6-0', weight: '187', classYear: '2026', overallRank: 10, projectedRound: 1, grade: 85, tieGrade: gradeToTieGrade(85), tieTier: gradeToTieTier(85), trend: 'steady', scoutingSummary: 'Technician who locks down his side. Doesn\'t gamble for stats. Matches all receiver types. Speed concerns need verification at pro day.', strengths: 'Coverage 9.0; Fluidity 9.0; Consistency 9.5; Press/zone 8.5; Toughness 8.5', weaknesses: 'Ball skills 8.0; Speed 7.5', nflComparison: 'Derek Stingley Jr.', filmGrade: 'A', analystNotes: '27.7% completion rate when targeted (3rd lowest FBS)' },
  { name: 'Dillon Thieneman', school: 'Oregon', position: 'S', height: '6-0', weight: '201', classYear: '2026', overallRank: 11, projectedRound: 1, grade: 85, tieGrade: gradeToTieGrade(85), tieTier: gradeToTieTier(85), trend: 'rising', scoutingSummary: 'Ball-hawking safety with elite speed. Tackling concerns addressed in 2025. Versatile coverage weapon. Highly coveted skill set.', strengths: 'Ball skills 9.5; Speed 9.5; Versatility 8.5; Improvement 9.0; Football IQ 9.0', weaknesses: 'Tackling 8.0; Size 7.5', nflComparison: 'Justin Simmons', filmGrade: 'A', analystNotes: '4.35 40, 6 INT (2023), reduced missed tackles from 22 to 8' },
  { name: 'Monroe Freeling', school: 'Georgia', position: 'OT', height: '6-7', weight: '315', classYear: '2026', overallRank: 12, projectedRound: 1, grade: 83, tieGrade: gradeToTieGrade(83), tieTier: gradeToTieTier(83), trend: 'rising', scoutingSummary: 'Highest-upside tackle in the class. Elite athletic profile but raw. Needs development time. Franchise LT potential if he puts it together.', strengths: 'Size/length 9.5; Athleticism 9.0; Upside 9.5; Improvement trajectory 9.0', weaknesses: 'Technique 7.0; Experience 7.0', nflComparison: 'Tristan Wirfs (early career)', filmGrade: 'A-', analystNotes: '18 career starts, 34.75" arms, 4.93 40, 33.5" vertical' },
  { name: 'Akheem Mesidor', school: 'Auburn', position: 'EDGE', height: '6-3', weight: '259', classYear: '2026', overallRank: 13, projectedRound: 1, grade: 83, tieGrade: gradeToTieGrade(83), tieTier: gradeToTieTier(83), trend: 'steady', scoutingSummary: 'Production machine who destroys interior OL when reduced inside. Age pushes him down boards but he\'s NFL-ready. Better version of Nic Scourton.', strengths: 'Production 9.0; Inside rush 9.5; First step 8.5; Versatility 8.5; Reliability 8.5', weaknesses: 'Age 7.0; Length 7.5', nflComparison: 'Cameron Heyward', filmGrade: 'A-', analystNotes: '12.5 sacks, 5.5 sacks in 4 CFP games, 23.9% pressure rate as DT' },
  { name: 'Spencer Fano', school: 'Utah', position: 'OT/OG', height: '6-6', weight: '311', classYear: '2026', overallRank: 14, projectedRound: 1, grade: 84, tieGrade: gradeToTieGrade(84), tieTier: gradeToTieTier(84), trend: 'steady', scoutingSummary: 'Versatile lineman who can play anywhere. Likely best inside due to length. Zone scheme fit with excellent lateral movement. High-floor prospect.', strengths: 'Versatility 9.5; Foot quickness 9.0; Pass protection 8.5; Football IQ 9.0; Toughness 9.0', weaknesses: 'Length 7.0; Power 8.0', nflComparison: 'Joel Bitonio', filmGrade: 'A-', analystNotes: '13 pressures, 1 sack allowed (2 seasons), 32.125" arms, center reps at combine' },
  { name: 'Arvell Reese', school: 'Ohio State', position: 'EDGE/LB', height: '6-4', weight: '241', classYear: '2026', overallRank: 15, projectedRound: 1, grade: 87, tieGrade: gradeToTieGrade(87), tieTier: gradeToTieTier(87), trend: 'rising', scoutingSummary: 'Athletic freak with massive upside. Chess piece who can play multiple positions. Boom-or-bust prospect with top-10 potential if he develops technique.', strengths: 'Athleticism 9.5; Versatility 9.0; Bend 9.0; Upside 9.5; Work ethic 9.0', weaknesses: 'Power 8.0; Production 8.5; Learning curve 7.5', nflComparison: 'Jalon Walker', filmGrade: 'A', analystNotes: '6.5 sacks in first 8 games, 97 pass-rush snaps (up from 17 in 2024)' },
  { name: 'Omar Cooper Jr.', school: 'Indiana', position: 'WR', height: '6-0', weight: '199', classYear: '2026', overallRank: 16, projectedRound: 2, grade: 82, tieGrade: gradeToTieGrade(82), tieTier: gradeToTieTier(82), trend: 'steady', scoutingSummary: 'Complete receiver who does everything well. Elite YAC ability for his size. Fits exact model of WRs finding immediate NFL success.', strengths: 'YAC 9.0; Route running 8.5; Clutch 9.0; Competitiveness 9.0; Character 8.5', weaknesses: 'Size 7.5; Speed 7.5', nflComparison: 'Chris Olave', filmGrade: 'B+', analystNotes: '13 receiving TD, 7.28 YAC average' },
  { name: 'Emmanuel McNeil-Warren', school: 'Toledo', position: 'S', height: null, weight: null, classYear: '2026', overallRank: 17, projectedRound: 2, grade: 82, tieGrade: gradeToTieGrade(82), tieTier: gradeToTieTier(82), trend: 'rising', scoutingSummary: 'Most exciting small-school prospect in years. Every tape shows production and energy. Level of competition is only concern. Late bloomer with starter upside.', strengths: 'Range 9.0; Athleticism 8.5; Energy 9.0; Upside 9.0; Work ethic 8.5', weaknesses: 'Competition level 6.5; Level jump 7.5', nflComparison: 'Tariq Carpenter', filmGrade: 'B+', analystNotes: 'MAC dominance — big hits, ball plays, high energy' },
  { name: 'Keldric Faulk', school: 'Auburn', position: 'EDGE', height: '6-6', weight: '276', classYear: '2026', overallRank: 18, projectedRound: 2, grade: 81, tieGrade: gradeToTieGrade(81), tieTier: gradeToTieTier(81), trend: 'steady', scoutingSummary: 'Traits-based prospect with elite size and length. Production doesn\'t match tools. Youngest edge in class with massive upside if developed properly.', strengths: 'Size/length 9.5; Run defense 8.5; Youth 9.0; Upside 9.5; Age 9.5', weaknesses: 'Production 5.5; Get-off 6.5; Rush plan 6.5', nflComparison: 'Travon Walker', filmGrade: 'B+', analystNotes: '2.0 sacks (2025), 7.0 sacks (2024), 82" wingspan' },
  { name: 'Jordyn Tyson', school: 'Arizona State', position: 'WR', height: '6-2', weight: '203', classYear: '2026', overallRank: 19, projectedRound: 2, grade: 81, tieGrade: gradeToTieGrade(81), tieTier: gradeToTieTier(81), trend: 'falling', scoutingSummary: 'Top-5 talent when healthy. Elite route runner with after-catch ability. Major durability concerns drop him slightly. High-risk, high-reward.', strengths: 'Playmaking 9.5; Route running 9.0; Ball tracking 9.0; YAC 9.0', weaknesses: 'Durability 6.0; Risk factor 6.5', nflComparison: 'Keenan Allen', filmGrade: 'B+', analystNotes: 'Final 6 games 2024: 50 rec, 732 yds, 6 TD. Hamstring injury 2025' },
  { name: 'CJ Allen', school: 'Georgia', position: 'LB', height: null, weight: null, classYear: '2026', overallRank: 20, projectedRound: 2, grade: 81, tieGrade: gradeToTieGrade(81), tieTier: gradeToTieTier(81), trend: 'steady', scoutingSummary: 'Productive, instinctive linebacker from Georgia pipeline. Won\'t wow with measurables but makes every play. NFL-ready mentally.', strengths: 'Instincts 9.0; Production 8.5; Football IQ 9.0; Leadership 9.0; Work ethic 8.5', weaknesses: 'Athleticism 7.0; Size 7.5', nflComparison: 'Nakobe Dean', filmGrade: 'B+', analystNotes: 'Georgia\'s defensive QB. Highly productive, instinctive.' },
  { name: 'Francis Mauigoa', school: 'Miami', position: 'OT', height: '6-6', weight: '329', classYear: '2026', overallRank: 21, projectedRound: 1, grade: 83, tieGrade: gradeToTieGrade(83), tieTier: gradeToTieTier(83), trend: 'steady', scoutingSummary: 'Massive RT with elite pass-protection numbers. May fit better at guard long-term due to limited athleticism. Safe pick with high floor.', strengths: 'Size 9.0; Pass protection 9.5; Run blocking 9.0; Durability 9.0; Consistency 8.5', weaknesses: 'Athleticism 7.5; Length 8.0; Leadership 7.0', nflComparison: 'Dion Dawkins', filmGrade: 'A-', analystNotes: '2 sacks allowed in 2 seasons, 1.2% pressure rate (lowest FBS tackles 2025)' },
  { name: 'Kadyn Proctor', school: 'Alabama', position: 'OT', height: '6-7', weight: '352', classYear: '2026', overallRank: 22, projectedRound: 2, grade: 80, tieGrade: gradeToTieGrade(80), tieTier: gradeToTieTier(80), trend: 'steady', scoutingSummary: 'Massive RT with elite run-blocking ability. Developmental upside due to youth. Concerns about handling NFL speed rushers.', strengths: 'Size 9.0; Run blocking 9.5; Power 8.5; Durability 9.5; Experience 8.5', weaknesses: 'Athleticism 6.5; Pass protection 7.0; Leverage 7.0', nflComparison: 'Orlando Brown Jr.', filmGrade: 'B+', analystNotes: '40 consecutive career starts, 32" vertical, 5.22 40' },
  { name: 'Jermod McCoy', school: 'Tennessee', position: 'CB', height: '6-1', weight: '188', classYear: '2026', overallRank: 23, projectedRound: 2, grade: 80, tieGrade: gradeToTieGrade(80), tieTier: gradeToTieTier(80), trend: 'falling', scoutingSummary: 'Elite man-coverage corner when healthy. Major medical red flag drops his stock. Day 1 starter if medicals check out.', strengths: 'Man coverage 9.0; Ball skills 8.5; Length 8.5; Press coverage 8.5', weaknesses: 'Medical 5.0; Run support 6.5', nflComparison: 'Jalen Ramsey (pre-injury)', filmGrade: 'B+', analystNotes: 'Missed entire 2025 with ACL tear. 2024: 4 INT, 7 PBU, 77" wingspan' },
  { name: 'Kenyon Sadiq', school: 'Oregon', position: 'TE', height: '6-3', weight: '241', classYear: '2026', overallRank: 24, projectedRound: 2, grade: 80, tieGrade: gradeToTieGrade(80), tieTier: gradeToTieTier(80), trend: 'rising', scoutingSummary: 'Rare speed for the position. Mismatch nightmare if he cleans up drops. Limited by height but makes up for it with athleticism.', strengths: 'Speed 10.0; Separation 9.0; YAC 8.5; Upside 9.0; Competitiveness 8.5', weaknesses: 'Size 6.5; Hands 6.5; Blocking 7.5', nflComparison: 'Dallas Goedert', filmGrade: 'B+', analystNotes: '8 receiving TD (led FBS TEs), 4.39 40, 6 drops' },
  { name: 'R Mason Thomas', school: 'Oklahoma', position: 'EDGE', height: '6-2', weight: '241', classYear: '2026', overallRank: 25, projectedRound: 2, grade: 80, tieGrade: gradeToTieGrade(80), tieTier: gradeToTieTier(80), trend: 'steady', scoutingSummary: 'Production and power undeniable despite length concerns. Similar profile to Bain but less heralded. Can set edge and rush inside.', strengths: 'Power 9.0; Run defense 8.5; Production 8.0; Burst 8.0; Toughness 8.5', weaknesses: 'Length 6.5; Size 7.0', nflComparison: 'Yaya Diaby', filmGrade: 'B+', analystNotes: '6.5 sacks, 23 pressures in 173 snaps (10 games, injury-limited), 21 run stops (2 seasons)' },
  { name: 'Peter Woods', school: 'Clemson', position: 'DT', height: '6-3', weight: '298', classYear: '2026', overallRank: 26, projectedRound: 2, grade: 79, tieGrade: gradeToTieGrade(79), tieTier: gradeToTieTier(79), trend: 'steady', scoutingSummary: 'High-upside interior disruptor who hasn\'t put it together yet. Quickness and hands are there. Needs to maximize potential at next level.', strengths: 'Quickness 9.0; Hand usage 8.5; Diagnostic ability 8.5; Upside 9.0', weaknesses: 'Production 6.5; Length 7.0; Power 7.0', nflComparison: 'Christian Wilkins', filmGrade: 'B', analystNotes: '5 sacks (3 seasons), 31.25" arms, 20 pressures (2024), 11 pressures (2025)' },
  { name: 'Zion Young', school: 'Missouri', position: 'EDGE', height: '6-6', weight: '262', classYear: '2026', overallRank: 27, projectedRound: 2, grade: 79, tieGrade: gradeToTieGrade(79), tieTier: gradeToTieTier(79), trend: 'steady', scoutingSummary: 'Heavy-handed edge setter with limited pass-rush production. Better as a run defender who can kick inside. Intriguing versatility.', strengths: 'Size 8.5; Run defense 8.5; Hands 8.0; Versatility 8.0; Toughness 8.5', weaknesses: 'Pass rush 6.5; Quickness 7.5; Production 7.0', nflComparison: 'Carl Lawson', filmGrade: 'B', analystNotes: 'Excellent edge-setting. Transferred from Michigan State.' },
  { name: 'A.J. Haulcy', school: 'LSU', position: 'S', height: null, weight: null, classYear: '2026', overallRank: 28, projectedRound: 2, grade: 79, tieGrade: gradeToTieGrade(79), tieTier: gradeToTieTier(79), trend: 'steady', scoutingSummary: 'Ball-hawking safety with playmaking instincts. Physical but needs to improve consistency. LSU pipeline safety.', strengths: 'Ball skills 9.0; Physicality 8.0; Instincts 8.5; Playmaking 9.0; Toughness 8.5', weaknesses: 'Tackling 7.0; Coverage 7.5; Consistency 7.0', nflComparison: 'Marcus Williams', filmGrade: 'B', analystNotes: 'Changes games with takeaways. Physical playmaker.' },
  { name: 'Skyler Bell', school: 'UConn', position: 'WR', height: null, weight: null, classYear: '2026', overallRank: 29, projectedRound: 2, grade: 79, tieGrade: gradeToTieGrade(79), tieTier: gradeToTieTier(79), trend: 'rising', scoutingSummary: 'Small-school standout with elite testing. Production and preparation are there. Shouldn\'t make it out of Day 2. High-upside developmental WR.', strengths: 'Production 8.0; Testing 8.5; Athleticism 8.0; Preparation 9.0; Work ethic 8.5; Character 8.0', weaknesses: 'Competition 6.0; Route running 6.5; Size 7.0', nflComparison: 'Darius Slayton', filmGrade: 'B', analystNotes: 'Combine standout. Small-school production elite.' },
  { name: 'Germie Bernard', school: 'Alabama', position: 'WR', height: null, weight: null, classYear: '2026', overallRank: 30, projectedRound: 2, grade: 78, tieGrade: gradeToTieGrade(78), tieTier: gradeToTieTier(78), trend: 'steady', scoutingSummary: 'Reliable, willing target who does everything asked. Not flashy but dependable. High-floor, low-ceiling prospect.', strengths: 'Reliability 8.0; Hands 7.5; Route running 7.5; Preparation 9.0; Work ethic 9.0; Character 8.5', weaknesses: 'Size 7.0; Speed 7.0; YAC 6.5', nflComparison: 'Jarvis Landry', filmGrade: 'B', analystNotes: 'Reliable, willing target. Does everything asked.' },
  { name: 'Cashius Howell', school: 'Texas A&M', position: 'EDGE', height: null, weight: null, classYear: '2026', overallRank: 31, projectedRound: 2, grade: 78, tieGrade: gradeToTieGrade(78), tieTier: gradeToTieTier(78), trend: 'steady', scoutingSummary: 'Fascinating outlier who wins with effort and speed despite lacking length. Bet-on character and athleticism. Developmental edge.', strengths: 'Intensity 9.0; Speed 8.0; Heart 9.0; Work ethic 9.0; Toughness 9.0', weaknesses: 'Length 6.0; Run defense 6.5; Production 7.0; Technique 7.0', nflComparison: 'Darrell Taylor', filmGrade: 'B', analystNotes: 'Plays with intensity and speed despite lacking length.' },
  { name: "D'Angelo Ponds", school: 'Indiana', position: 'CB', height: null, weight: null, classYear: '2026', overallRank: 32, projectedRound: 2, grade: 78, tieGrade: gradeToTieGrade(78), tieTier: gradeToTieTier(78), trend: 'steady', scoutingSummary: 'Fascinating outlier. Elite play speed and competitiveness despite lacking size. High-risk, high-reward prospect.', strengths: 'Speed 8.5; Physicality 8.0; Competitiveness 8.0; Heart 9.5; Toughness 9.0', weaknesses: 'Size 5.5; Length 6.0; Upside 7.0', nflComparison: 'Emmanuel Forbes', filmGrade: 'B', analystNotes: 'Speed and physicality standout despite lacking size.' },
  { name: 'Colton Hood', school: 'Tennessee', position: 'CB', height: null, weight: null, classYear: '2026', overallRank: 33, projectedRound: 3, grade: 77, tieGrade: gradeToTieGrade(77), tieTier: gradeToTieTier(77), trend: 'steady', scoutingSummary: 'Physical corner with man coverage skills. Less heralded than McCoy but similar upside. Tennessee secondary produces NFL talent.', strengths: 'Coverage 8.0; Physicality 8.0; Toughness 8.5; Competitiveness 8.0', weaknesses: 'Speed 7.5; Ball skills 7.0; Experience 7.0', nflComparison: 'Roger McCreary', filmGrade: 'B', analystNotes: 'Part of talented Tennessee CB duo with McCoy.' },
  { name: 'Malachi Lawrence', school: 'UCF', position: 'EDGE', height: null, weight: null, classYear: '2026', overallRank: 34, projectedRound: 3, grade: 77, tieGrade: gradeToTieGrade(77), tieTier: gradeToTieTier(77), trend: 'steady', scoutingSummary: 'Athletic edge rusher with production at UCF. Needs technical refinement. Upside play with development time.', strengths: 'Production 8.0; Athleticism 8.0; Upside 8.5; Work ethic 8.0', weaknesses: 'Technique 7.0; Competition 6.5; Run defense 7.0', nflComparison: 'Trevis Gipson', filmGrade: 'B', analystNotes: 'High-level edge production at UCF.' },
  { name: 'Jonah Coleman', school: 'Washington', position: 'RB', height: null, weight: null, classYear: '2026', overallRank: 35, projectedRound: 3, grade: 77, tieGrade: gradeToTieGrade(77), tieTier: gradeToTieTier(77), trend: 'steady', scoutingSummary: 'Underappreciated complete back. Runs hard, catches naturally, and wears down defenses. Could lead NFL backfield for years.', strengths: 'Running style 8.0; Receiving 7.5; Durability 8.0; Toughness 8.5; Work ethic 8.0', weaknesses: 'Size 6.5; Speed 7.0', nflComparison: 'Elijah Mitchell', filmGrade: 'B', analystNotes: 'Complete back — runs hard, natural hands, wears down defenses.' },
  { name: 'Blake Miller', school: 'Clemson', position: 'OT', height: null, weight: null, classYear: '2026', overallRank: 36, projectedRound: 2, grade: 79, tieGrade: gradeToTieGrade(79), tieTier: gradeToTieTier(79), trend: 'steady', scoutingSummary: 'Remarkable durability with 54 consecutive starts. Wrestling background shows in strength and leverage. Ideal RT profile who can start immediately.', strengths: 'Durability 10.0; Size 8.5; Strength 8.0; Reliability 9.5; Toughness 9.0', weaknesses: 'Pass protection 7.5; Athleticism 6.5', nflComparison: 'Braden Smith', filmGrade: 'B', analystNotes: '54 consecutive starts. Wrestling background.' },
  { name: 'Caleb Lomu', school: 'Utah', position: 'OT', height: null, weight: null, classYear: '2026', overallRank: 37, projectedRound: 3, grade: 75, tieGrade: gradeToTieGrade(75), tieTier: gradeToTieTier(75), trend: 'steady', scoutingSummary: 'Developing tackle with pass-protection upside. Utah OL pipeline prospect. Needs time to develop run blocking.', strengths: 'Pass protection 8.0; Athleticism 8.0; Upside 8.5; Work ethic 8.0', weaknesses: 'Run blocking 7.0; Length 7.0; Experience 7.0', nflComparison: 'Abraham Lucas', filmGrade: 'B-', analystNotes: 'Developing as run blocker. Movement skills show upside.' },
  { name: 'Christen Miller', school: 'Georgia', position: 'DT', height: null, weight: null, classYear: '2026', overallRank: 38, projectedRound: 3, grade: 75, tieGrade: gradeToTieGrade(75), tieTier: gradeToTieTier(75), trend: 'steady', scoutingSummary: 'Tough interior lineman from Georgia pipeline. Brings power and attitude. Rotational player with limited pass-rush upside.', strengths: 'Toughness 8.0; Run defense 7.5; Mentality 8.5; Work ethic 7.5', weaknesses: 'Pass rush 7.0; Athleticism 7.0; Upside 7.0', nflComparison: 'Devonte Wyatt', filmGrade: 'B-', analystNotes: 'Interior disruptor from Georgia\'s DL room.' },
  { name: 'TJ Parker', school: 'Clemson', position: 'EDGE', height: null, weight: null, classYear: '2026', overallRank: 39, projectedRound: 3, grade: 75, tieGrade: gradeToTieGrade(75), tieTier: gradeToTieTier(75), trend: 'steady', scoutingSummary: 'Technical edge rusher with good hand usage. Consistent but not dynamic. Clemson developmental prospect.', strengths: 'Consistency 8.0; Hand usage 7.5; Technique 7.5; Work ethic 8.0', weaknesses: 'Run defense 7.0; Production 7.0; Upside 7.5', nflComparison: 'Austin Bryant', filmGrade: 'B-', analystNotes: 'Consistent edge presence for Clemson.' },
  { name: 'Lee Hunter', school: 'Texas Tech', position: 'DT', height: null, weight: null, classYear: '2026', overallRank: 40, projectedRound: 3, grade: 75, tieGrade: gradeToTieGrade(75), tieTier: gradeToTieTier(75), trend: 'steady', scoutingSummary: 'Run-stuffing nose tackle who can anchor the middle. Takes on double teams and frees up linebackers. Two-down player.', strengths: 'Run defense 8.5; Size 8.0; Strength 8.0; Toughness 8.0; Role acceptance 8.0', weaknesses: 'Pass rush 6.5; Athleticism 6.5; Upside 6.5', nflComparison: 'Derrick Nnadi', filmGrade: 'B-', analystNotes: 'Run-stuffing nose tackle. Takes on double teams.' },
];

// Add 10 more prospects (ranks 41-50) to reach the full 50-player board
const EXTENDED_BOARD: Omit<Prospect, 'positionRank'>[] = [
  ...RAW_BOARD,
  { name: 'Josh Conerly Jr.', school: 'Oregon', position: 'OT', height: '6-5', weight: '305', classYear: '2026', overallRank: 41, projectedRound: 3, grade: 74, tieGrade: gradeToTieGrade(74), tieTier: gradeToTieTier(74), trend: 'steady', scoutingSummary: 'Athletic tackle with upside from Oregon\'s zone-blocking scheme. Needs to add mass and improve anchor.', strengths: 'Athleticism 8.5; Feet 8.0; Zone blocking 8.0; Upside 8.0', weaknesses: 'Power 6.5; Anchor 6.5; Mass 7.0', nflComparison: 'Kolton Miller (early)', filmGrade: 'B-', analystNotes: 'Oregon zone-scheme tackle. Athletic but needs development.' },
  { name: 'Princely Umanmielen', school: 'Ole Miss', position: 'EDGE', height: '6-4', weight: '253', classYear: '2026', overallRank: 42, projectedRound: 3, grade: 74, tieGrade: gradeToTieGrade(74), tieTier: gradeToTieTier(74), trend: 'steady', scoutingSummary: 'Versatile defender who can rush from multiple spots. Transferred from Florida and improved production. Solid Day 2 value.', strengths: 'Versatility 8.0; Motor 8.5; Athleticism 8.0; Improvement 8.0', weaknesses: 'Pass rush plan 6.5; Power 7.0; Consistency 7.0', nflComparison: 'Josh Sweat', filmGrade: 'B-', analystNotes: 'Transfer from Florida. Improved production at Ole Miss.' },
  { name: 'Donovan Ezeiruaku', school: 'Boston College', position: 'EDGE', height: '6-2', weight: '250', classYear: '2026', overallRank: 43, projectedRound: 3, grade: 74, tieGrade: gradeToTieGrade(74), tieTier: gradeToTieTier(74), trend: 'rising', scoutingSummary: 'High-motor pass rusher with impressive production. Concerns about level of competition but motor and effort are undeniable.', strengths: 'Motor 9.0; Production 8.5; Effort 9.0; Toughness 8.5', weaknesses: 'Competition 6.5; Length 6.5; Run defense 7.0', nflComparison: 'Matt Judon (lite)', filmGrade: 'B-', analystNotes: 'ACC sack leader. Non-stop motor.' },
  { name: 'Benjamin Morrison', school: 'Notre Dame', position: 'CB', height: '6-0', weight: '190', classYear: '2026', overallRank: 44, projectedRound: 3, grade: 74, tieGrade: gradeToTieGrade(74), tieTier: gradeToTieTier(74), trend: 'falling', scoutingSummary: 'Ball-hawking corner with INT production. Injury concerns after knee issue. When healthy, a lockdown corner with playmaking upside.', strengths: 'Ball skills 9.0; Coverage 8.0; Instincts 8.5; Competitiveness 8.0', weaknesses: 'Medical 6.0; Speed 7.0; Physicality 7.0', nflComparison: 'Xavien Howard', filmGrade: 'B-', analystNotes: 'Multiple INTs per season. Knee injury concern.' },
  { name: 'Emeka Egbuka', school: 'Ohio State', position: 'WR', height: '6-1', weight: '205', classYear: '2026', overallRank: 45, projectedRound: 3, grade: 74, tieGrade: gradeToTieGrade(74), tieTier: gradeToTieTier(74), trend: 'steady', scoutingSummary: 'Polished route runner with reliable hands. Fourth-year senior with extensive production. Safe pick with limited explosive upside.', strengths: 'Route running 8.5; Hands 8.5; Reliability 8.5; Experience 9.0', weaknesses: 'Speed 7.0; YAC 6.5; Upside 7.0', nflComparison: 'Allen Lazard', filmGrade: 'B-', analystNotes: 'Four-year starter. Consistent production at Ohio State.' },
  { name: 'Jahdae Barron', school: 'Texas', position: 'CB', height: '6-0', weight: '196', classYear: '2026', overallRank: 46, projectedRound: 3, grade: 73, tieGrade: gradeToTieGrade(73), tieTier: gradeToTieTier(73), trend: 'steady', scoutingSummary: 'Versatile defensive back who can play corner or nickel. Physical tackler with experience in multiple schemes. Solid starter potential.', strengths: 'Versatility 8.5; Tackling 8.0; Physicality 8.0; Experience 8.5', weaknesses: 'Speed 7.0; Hip fluidity 7.0; Ball skills 7.0', nflComparison: 'Chauncey Gardner-Johnson', filmGrade: 'B-', analystNotes: 'Texas defensive leader. Nickel/corner versatility.' },
  { name: 'Jaylen Reed', school: 'Penn State', position: 'S', height: '6-0', weight: '205', classYear: '2026', overallRank: 47, projectedRound: 3, grade: 73, tieGrade: gradeToTieGrade(73), tieTier: gradeToTieTier(73), trend: 'steady', scoutingSummary: 'Physical safety with run-support ability. Productive in Penn State\'s defense. Limited range but makes up for it with physicality.', strengths: 'Run support 8.5; Physicality 8.5; Tackling 8.0; Toughness 8.5', weaknesses: 'Range 6.5; Coverage 7.0; Speed 7.0', nflComparison: 'Jordan Poyer', filmGrade: 'B-', analystNotes: 'Penn State defensive leader. Physical run-support safety.' },
  { name: 'Kelvin Banks Jr.', school: 'Texas', position: 'OT', height: '6-4', weight: '320', classYear: '2026', overallRank: 48, projectedRound: 3, grade: 73, tieGrade: gradeToTieGrade(73), tieTier: gradeToTieTier(73), trend: 'falling', scoutingSummary: 'Once a top-10 prospect who has slid due to inconsistent 2025. Still has the tools to be a starting LT. Needs coaching and consistency.', strengths: 'Size 8.5; Power 8.0; Experience 8.5; Upside 8.0', weaknesses: 'Consistency 6.0; Technique 6.5; Athleticism 7.0', nflComparison: 'Cam Robinson', filmGrade: 'B-', analystNotes: 'Former top prospect. Inconsistent 2025 season at Texas.' },
  { name: 'Tyler Warren', school: 'Penn State', position: 'TE', height: '6-6', weight: '260', classYear: '2026', overallRank: 49, projectedRound: 3, grade: 73, tieGrade: gradeToTieGrade(73), tieTier: gradeToTieTier(73), trend: 'steady', scoutingSummary: 'Swiss-army-knife tight end who lined up everywhere at Penn State. Elite versatility but may not have one elite skill. Offensive weapon.', strengths: 'Versatility 9.5; Football IQ 9.0; Hands 8.0; Route running 8.0', weaknesses: 'Speed 6.5; Blocking 7.0; Athleticism 7.0', nflComparison: 'Kyle Pitts (lite)', filmGrade: 'B-', analystNotes: 'Lined up at WR, RB, and in-line TE at Penn State.' },
  { name: 'Dontay Corleone', school: 'Cincinnati', position: 'DT', height: '6-2', weight: '305', classYear: '2026', overallRank: 50, projectedRound: 3, grade: 73, tieGrade: gradeToTieGrade(73), tieTier: gradeToTieTier(73), trend: 'rising', scoutingSummary: 'Powerful interior lineman returning from blood clot issues. When healthy, a dominant run defender with pass-rush upside. Medical is the only question.', strengths: 'Power 9.0; Run defense 8.5; Quickness 8.0; Upside 8.5', weaknesses: 'Medical 5.0; Conditioning 6.5; Snap count 7.0', nflComparison: 'Poona Ford', filmGrade: 'B-', analystNotes: 'Returning from blood clot scare. Dominant when healthy.' },
];

export const BOARD_2026: Prospect[] = assignPositionRanks(EXTENDED_BOARD);
