/**
 * Per|Form Curated Prospect Seed Data
 *
 * This is the initial seed database of prospects with full P.A.I. scoring,
 * adversarial debate results, and scouting memos. These are the "day 1"
 * prospects that populate the Big Board before Brave Search enrichment.
 *
 * Once seeded to the database, these can be enriched with live data via
 * the /api/perform/enrich endpoint using Brave Search.
 */

export interface SeedProspect {
  firstName: string;
  lastName: string;
  position: string;
  classYear: string;
  school: string;
  state: string;
  pool: string;
  height?: string;
  weight?: number;
  gpa?: number;
  paiScore: number;
  tier: string;
  performance: number;
  athleticism: number;
  intangibles: number;
  nationalRank: number;
  stateRank: number;
  positionRank: number;
  trend: string;
  previousRank?: number;
  nilEstimate: string;
  scoutMemo: string;
  tags: string[];
  comparisons: string[];
  stats: Record<string, string | number>;
  bullCase: string;
  bearCase: string;
  mediationVerdict: string;
  debateWinner: string;
  stars?: number;
  enrichedBy?: string;
}

export const SEED_PROSPECTS: SeedProspect[] = [
  {
    firstName: 'Cameron',
    lastName: 'Price',
    position: 'QB',
    classYear: "'26",
    school: 'IMG Academy',
    state: 'FL',
    pool: 'HIGH_SCHOOL',
    height: "6'4\"",
    weight: 220,
    gpa: 3.7,
    paiScore: 95,
    tier: 'ELITE',
    performance: 93,
    athleticism: 96,
    intangibles: 96,
    nationalRank: 1,
    stateRank: 1,
    positionRank: 1,
    trend: 'STEADY',
    previousRank: 1,
    nilEstimate: '$1M+',
    scoutMemo: "The consensus #1 prospect in the 2026 class. Prototypical size, elite arm talent, and a football mind that rivals college seniors. IMG Academy's schedule means he's been tested against national-level talent every week. Already has major NIL deals and 500K+ social following. The rare prospect who lives up to the hype.",
    tags: ['#1-overall', 'prototypical', 'arm-talent', 'football-iq', 'national-schedule'],
    comparisons: ['Trevor Lawrence coming out of HS', 'Peyton Manning processing'],
    stats: { 'Pass Yards': '4,120', 'Pass TD': 42, 'Rush Yards': 520, 'Rush TD': 8, 'Comp %': '71.5%', 'INT': 3 },
    bullCase: "Price is a generational talent — full stop. 42 TDs with only 3 INTs against the toughest schedule in HS football. His film shows throws that college QBs can't make. At IMG, every game is a showcase against future P5 players. His social media presence and brand awareness are already elite-level.",
    bearCase: "The hype machine is real but so is the pressure. IMG Academy QBs have underwhelmed at the next level before. His rushing numbers (520 yards) suggest he relies on legs when pressured. At $1M+ NIL before college, the distraction factor is a legitimate concern.",
    mediationVerdict: "Bull wins overwhelmingly. Bear's concerns are theoretical and not supported by film. The IMG track record concern is fair historically but Price's tape is different — he makes NFL-level reads pre-snap. P.A.I. locked at 95, PRIME PLAYER territory.",
    debateWinner: 'BULL',
    stars: 5,
    enrichedBy: 'manual',
  },
  {
    firstName: 'Marcus',
    lastName: 'Johnson',
    position: 'QB',
    classYear: "'26",
    school: 'Oakwood HS',
    state: 'TX',
    pool: 'HIGH_SCHOOL',
    height: "6'2\"",
    weight: 205,
    gpa: 3.8,
    paiScore: 92,
    tier: 'ELITE',
    performance: 88,
    athleticism: 94,
    intangibles: 95,
    nationalRank: 3,
    stateRank: 1,
    positionRank: 2,
    trend: 'UP',
    previousRank: 5,
    nilEstimate: '$500K–$1M',
    scoutMemo: "Dual-threat QB with elite arm talent and leadership presence. Film shows consistent deep ball accuracy under pressure. Plays beyond his years in the pocket. Commands the offense like a coordinator on the field.",
    tags: ['dual-threat', 'leader', 'deep-ball', 'pocket-presence'],
    comparisons: ['Young Russell Wilson', 'Jalen Hurts mobility with Justin Herbert arm'],
    stats: { 'Pass Yards': '3,420', 'Pass TD': 34, 'Rush Yards': 680, 'Rush TD': 12, 'Comp %': '68.2%', 'INT': 4 },
    bullCase: "Marcus Johnson's arm talent is generational. Film shows consistent deep ball accuracy under pressure. The stats don't capture how he elevates everyone around him. His 68% completion rate with 34 TDs against a schedule that included 4 playoff teams is elite.",
    bearCase: "Johnson's competition level is a concern. 5A Texas is strong but the top opponents accounted for 3 of his 4 losses. His rushing numbers are inflated by designed runs — he's not a natural scrambler. Needs to prove it against Power 5 speed.",
    mediationVerdict: "Bull makes the stronger case on film evidence. Bear raises a valid concern on schedule strength. GROC adjusted +2 for film, Luke -1 for competition. Net: P.A.I. holds at 92.",
    debateWinner: 'BULL',
    stars: 5,
    enrichedBy: 'manual',
  },
  {
    firstName: 'Damien',
    lastName: 'Brooks',
    position: 'DE',
    classYear: "'26",
    school: 'Riverside HS',
    state: 'SC',
    pool: 'HIGH_SCHOOL',
    height: "6'4\"",
    weight: 245,
    gpa: 3.9,
    paiScore: 91,
    tier: 'ELITE',
    performance: 90,
    athleticism: 93,
    intangibles: 89,
    nationalRank: 4,
    stateRank: 1,
    positionRank: 1,
    trend: 'UP',
    previousRank: 6,
    nilEstimate: '$400K–$800K',
    scoutMemo: "Freakish edge rusher with a motor that never stops. His first step is the fastest in this class regardless of position. Destroys offensive tackles with speed-to-power conversion. Excellent character — team captain, 3.9 GPA, and volunteers at youth football camps.",
    tags: ['edge-rusher', 'motor', 'first-step', 'character'],
    comparisons: ['Young Myles Garrett', 'Chase Young explosiveness'],
    stats: { 'Sacks': 18, 'TFL': 26, 'Tackles': 68, 'FF': 6, 'QB Hurries': 32, 'Blocked Kicks': 2 },
    bullCase: "Brooks is a once-in-a-generation pass rusher. 18 sacks and 32 QB hurries means he's affecting the play even when he doesn't finish. His 6'4\" 245 frame with 4.55 speed is an NFL-ready physical profile. Character and academics are flawless.",
    bearCase: "South Carolina competition is mid-tier compared to Texas, Georgia, or Florida. His run defense is secondary to his pass rush — 68 tackles for a DE who plays every snap is low. He wins with speed but what happens when he faces NFL OTs?",
    mediationVerdict: "Bull dominates this debate. Bear's competition concern is offset by combine-verified measurables. Run defense concern is schematic — he's being used as a pure rusher. P.A.I. elevated to 91.",
    debateWinner: 'BULL',
    stars: 5,
    enrichedBy: 'manual',
  },
  {
    firstName: 'Khalil',
    lastName: 'Robinson',
    position: 'CB',
    classYear: "'26",
    school: 'St. Augustine Prep',
    state: 'NJ',
    pool: 'HIGH_SCHOOL',
    height: "6'0\"",
    weight: 180,
    paiScore: 88,
    tier: 'BLUE_CHIP',
    performance: 85,
    athleticism: 92,
    intangibles: 87,
    nationalRank: 8,
    stateRank: 1,
    positionRank: 2,
    trend: 'STEADY',
    previousRank: 7,
    nilEstimate: '$300K–$600K',
    scoutMemo: "Lockdown corner with elite ball skills and mirror technique. His 8 INTs led the state and included 3 pick-sixes. Smooth hips and recovery speed allow him to play press or off coverage. Already has NIL deals with two regional brands.",
    tags: ['lockdown', 'ball-skills', 'press-coverage', 'pick-six'],
    comparisons: ['Sauce Gardner technique', 'Jalen Ramsey confidence'],
    stats: { 'INT': 8, 'PBU': 18, 'Pick-6': 3, 'Tackles': 48, 'FR': 2 },
    bullCase: "Robinson is the most technically sound DB in this class. 8 INTs with 3 pick-sixes means he's not just covering — he's creating turnovers. His film shows he erases the opponent's #1 receiver.",
    bearCase: "New Jersey competition level is a question mark. His size at 6'0\" 180 is concerning against physical SEC receivers. INTs can be fluky — pass breakups (18) are the more stable metric.",
    mediationVerdict: "Bull wins on film evidence. Bear's size concern is valid but his frame can carry 190+ without losing speed. Competition adjustment is minor — NJ Prep is high quality. P.A.I. holds at 88.",
    debateWinner: 'BULL',
    stars: 4,
    enrichedBy: 'manual',
  },
  {
    firstName: 'Isaiah',
    lastName: 'Torres',
    position: 'OT',
    classYear: "'26",
    school: 'Don Bosco Prep',
    state: 'NJ',
    pool: 'HIGH_SCHOOL',
    height: "6'6\"",
    weight: 295,
    gpa: 3.6,
    paiScore: 86,
    tier: 'BLUE_CHIP',
    performance: 84,
    athleticism: 88,
    intangibles: 86,
    nationalRank: 10,
    stateRank: 2,
    positionRank: 2,
    trend: 'UP',
    previousRank: 14,
    nilEstimate: '$200K–$450K',
    scoutMemo: "Mauling offensive tackle with rare footwork for his size. Anchors against power rushers and mirrors speed rushers with ease. His wrestling background shows in his hand placement and leverage. Projects as a 4-year starter at a Power 5 program.",
    tags: ['mauler', 'footwork', 'wrestling-background', 'anchor'],
    comparisons: ['Penei Sewell technique', 'Trent Williams athleticism'],
    stats: { 'Pancakes': 62, 'Sacks Allowed': 1, 'Penalties': 3, 'Starts': 30 },
    bullCase: "Torres is the most NFL-ready offensive lineman in this class. 1 sack allowed in 30 starts against NJ Prep competition — which produces NFL talent annually.",
    bearCase: "OTs from NJ Prep have had mixed results at the next level. At 295, he may need to add weight and could lose the athleticism that makes him special.",
    mediationVerdict: "Bull wins on film dominance. Bear's weight concern is standard developmental — his frame can carry 315+. P.A.I. rises to 86.",
    debateWinner: 'BULL',
    stars: 4,
    enrichedBy: 'manual',
  },
  {
    firstName: 'DeShawn',
    lastName: 'Williams',
    position: 'WR',
    classYear: "'26",
    school: 'Central HS',
    state: 'GA',
    pool: 'HIGH_SCHOOL',
    height: "6'1\"",
    weight: 185,
    gpa: 3.4,
    paiScore: 85,
    tier: 'BLUE_CHIP',
    performance: 82,
    athleticism: 90,
    intangibles: 83,
    nationalRank: 12,
    stateRank: 3,
    positionRank: 4,
    trend: 'UP',
    previousRank: 18,
    nilEstimate: '$250K–$500K',
    scoutMemo: "Explosive playmaker with elite speed and body control. Consistently wins contested catches and creates separation at the top of routes. Reliable hands and fearless over the middle. Social media presence is growing — 85K followers and rising after playoff run.",
    tags: ['speed', 'contested-catch', 'route-runner', 'social-media'],
    comparisons: ['Garrett Wilson route-running', "Ja'Marr Chase contested catch ability"],
    stats: { 'Receptions': 78, 'Rec Yards': '1,340', 'Rec TD': 16, 'YPC': 17.2, '100+ Yd Games': 8 },
    bullCase: "Williams is the most explosive receiver in the class. His 4.38 laser-timed speed combined with 6'1\" frame gives him an elite catch radius. His 17.2 yards per catch proves he's not just a deep threat.",
    bearCase: "His route tree is limited — primarily go routes and slants. The 78 receptions are solid but he disappears in games where he's not the primary read.",
    mediationVerdict: "Bull wins on raw talent assessment. Bear raises legitimate route-running concerns. Film shows route tree is broader than stats suggest. P.A.I. confirmed at 85.",
    debateWinner: 'BULL',
    stars: 4,
    enrichedBy: 'manual',
  },
  {
    firstName: 'Andre',
    lastName: 'Washington',
    position: 'S',
    classYear: "'26",
    school: 'Cass Tech',
    state: 'MI',
    pool: 'HIGH_SCHOOL',
    height: "6'1\"",
    weight: 200,
    paiScore: 82,
    tier: 'BLUE_CHIP',
    performance: 80,
    athleticism: 86,
    intangibles: 80,
    nationalRank: 15,
    stateRank: 2,
    positionRank: 3,
    trend: 'STEADY',
    previousRank: 16,
    nilEstimate: '$150K–$350K',
    scoutMemo: "Versatile safety who can play deep, in the box, or as a nickel. His football IQ is advanced — he reads routes before the ball is thrown. Physical tackler who rarely misses. Quiet leader who lets his play speak.",
    tags: ['versatile', 'football-iq', 'sure-tackler', 'range'],
    comparisons: ['Derwin James versatility', 'Kyle Hamilton range'],
    stats: { 'Tackles': 92, 'INT': 5, 'PBU': 12, 'FF': 3, 'TFL': 8, 'Sacks': 2 },
    bullCase: "Washington is the most versatile defensive back in this class. His 92 tackles, 5 INTs, and 2 sacks show a player who impacts every level of the defense.",
    bearCase: "His 4.52 forty raises concerns about deep safety viability at the next level. The versatility could be a negative — is he elite at anything or just good at everything?",
    mediationVerdict: "Bull wins on production breadth. Bear's speed concern is real but his instincts compensate. He profiles as a strong safety / nickel hybrid. P.A.I. at 82.",
    debateWinner: 'SPLIT',
    stars: 4,
    enrichedBy: 'manual',
  },
  {
    firstName: 'Jaylen',
    lastName: 'Carter',
    position: 'RB',
    classYear: "'27",
    school: 'Summit Prep',
    state: 'FL',
    pool: 'HIGH_SCHOOL',
    height: "5'11\"",
    weight: 195,
    paiScore: 78,
    tier: 'PROSPECT',
    performance: 80,
    athleticism: 82,
    intangibles: 72,
    nationalRank: 28,
    stateRank: 7,
    positionRank: 5,
    trend: 'STEADY',
    nilEstimate: '$100K–$250K',
    scoutMemo: "Patient runner with excellent vision and decisive cuts. Shows maturity beyond his age in pass protection. Still a junior — upside is significant. Needs to add bulk for the next level but his lateral quickness is special.",
    tags: ['vision', 'patient-runner', 'pass-protection', 'upside'],
    comparisons: ['Saquon Barkley patience', 'Nick Chubb between the tackles'],
    stats: { 'Rush Yards': '1,680', 'Rush TD': 18, 'YPC': 7.2, 'Receptions': 32, 'Rec Yards': 380, 'Fumbles': 1 },
    bullCase: "Carter is only a junior and already producing at an elite level. His 7.2 YPC against a Florida schedule is outstanding. His fumble rate (1 in 233 carries) shows ball security that coaches covet.",
    bearCase: "Florida HS competition is strong but Summit Prep's schedule was mid-tier. His breakaway speed isn't elite — 4.52 forty. In the modern spread, his receiving skills need development.",
    mediationVerdict: "Split decision. Bull is correct on production floor. Bear is correct on speed concerns. Carter is a true prospect — high floor, needs development to reach ceiling. P.A.I. set at 78.",
    debateWinner: 'SPLIT',
    stars: 4,
    enrichedBy: 'manual',
  },
  {
    firstName: 'Trevor',
    lastName: 'Mitchell',
    position: 'LB',
    classYear: "'26",
    school: 'Heritage Academy',
    state: 'AL',
    pool: 'HIGH_SCHOOL',
    height: "6'2\"",
    weight: 225,
    paiScore: 68,
    tier: 'SLEEPER',
    performance: 70,
    athleticism: 72,
    intangibles: 62,
    nationalRank: 85,
    stateRank: 14,
    positionRank: 12,
    trend: 'UP',
    previousRank: 120,
    nilEstimate: '$10K–$50K',
    scoutMemo: "Physical downhill linebacker with sideline-to-sideline range. Late bloomer who's added 20 lbs of muscle in the last year. His film from the state semifinals showed elite instincts against the run.",
    tags: ['physical', 'run-stopper', 'late-bloomer', 'instincts'],
    comparisons: ['Micah Parsons physicality', 'Roquan Smith instincts'],
    stats: { 'Tackles': 142, 'TFL': 22, 'Sacks': 8, 'FF': 4, 'INT': 2, 'FR': 3 },
    bullCase: "Mitchell is the biggest riser on the board. 142 tackles with 22 TFL in Alabama 6A is no joke. His frame has room for another 15 lbs without losing speed.",
    bearCase: "Coverage skills are a liability — only 2 INTs and QBs target him in space. His 4.65 forty is concerning for modern LB play.",
    mediationVerdict: "Bull wins on trajectory and upside. Bear correctly identifies coverage as the development priority. P.A.I. at 68 with SLEEPER tag indicating high ceiling.",
    debateWinner: 'BULL',
    stars: 3,
    enrichedBy: 'manual',
  },
  {
    firstName: 'Xavier',
    lastName: 'Coleman',
    position: 'WR',
    classYear: "'26",
    school: 'Mater Dei',
    state: 'CA',
    pool: 'HIGH_SCHOOL',
    height: "6'3\"",
    weight: 195,
    paiScore: 58,
    tier: 'DEVELOPMENTAL',
    performance: 55,
    athleticism: 68,
    intangibles: 50,
    nationalRank: 180,
    stateRank: 42,
    positionRank: 35,
    trend: 'NEW',
    nilEstimate: '$5K–$15K',
    scoutMemo: "Raw athlete who transferred to Mater Dei mid-season. Limited snaps but the physical tools jump off the screen — 4.4 speed, 38\" vertical. Needs route-running development and game experience.",
    tags: ['raw', 'speed', 'project', 'transfer', 'upside'],
    comparisons: ['Raw DK Metcalf tools'],
    stats: { 'Receptions': 18, 'Rec Yards': 380, 'Rec TD': 4, 'YPC': 21.1 },
    bullCase: "Coleman has the highest athletic ceiling of any WR in this class. His 4.4 speed at 6'3\" 195 is an NFL prototype. His 21.1 YPC in limited snaps shows big-play ability.",
    bearCase: "18 receptions is not a sample size. He transferred mid-season which raises questions. His route-running is remedial — he wins purely on athleticism.",
    mediationVerdict: "Bear wins this debate. The tools are undeniable but the production isn't there yet. P.A.I. set at 58 — DEVELOPMENTAL with re-evaluation after spring practice.",
    debateWinner: 'BEAR',
    stars: 3,
    enrichedBy: 'manual',
  },
];
